export type StarterLesson = {
 question: string; meaning: string; phrase: string; translation: string; tip: string;
 frame: string; answer: string; explanation: string;
 audio: string; listeningQuestion: string; listeningOptions: string[]; listeningAnswer: string;
 reading: string; readingQuestion: string; readingOptions: string[]; readingAnswer: string;
};
export const a1Starter: Record<number, StarterLesson> = {
 1: {question:'Wie heißt du?',meaning:'What is your name?',phrase:'Ich heiße Lina.',translation:'My name is Lina.',tip:'Keep “Ich heiße” and replace Lina with your name.',frame:'Ich ___ Lina.',answer:'heiße',explanation:'Ich heiße means “my name is”. You can also introduce yourself with Ich bin.',audio:'Hallo! Ich heiße Ben.',listeningQuestion:'What is his name?',listeningOptions:['Lina','Ben','Mia'],listeningAnswer:'Ben',reading:'Hallo! Ich heiße Mia.',readingQuestion:'Who wrote this message?',readingOptions:['Mia','Ben','Lina'],readingAnswer:'Mia'},
 2: {question:'Woher kommst du?',meaning:'Which country are you from?',phrase:'Ich komme aus Indien.',translation:'I come from India.',tip:'Use “Ich komme aus” with your country. Some countries need an article: aus der Schweiz, aus der Türkei, aus den USA.',frame:'Ich komme ___ Indien.',answer:'aus',explanation:'Aus means “from” here. Deutschland = Germany; Indien = India.',audio:'Hallo! Ich heiße Eva. Ich komme aus Deutschland.',listeningQuestion:'Which country is Eva from?',listeningOptions:['India','Germany','Switzerland'],listeningAnswer:'Germany',reading:'Ich heiße Ali. Ich komme aus der Türkei.',readingQuestion:'Which country is Ali from?',readingOptions:['Germany','India','Turkey'],readingAnswer:'Turkey'},
 3: {question:'Wo wohnst du?',meaning:'Where do you live?',phrase:'Ich wohne in Bonn.',translation:'I live in Bonn.',tip:'Keep “Ich wohne in” and add your town or city. Wo asks where; woher asks where you come from.',frame:'Ich wohne ___ Bonn.',answer:'in',explanation:'Use in before a city: in Bonn, in Berlin, in Delhi.',audio:'Ich heiße Leo. Ich komme aus Deutschland. Ich wohne in Köln.',listeningQuestion:'Where does Leo live?',listeningOptions:['Bonn','Berlin','Cologne (Köln)'],listeningAnswer:'Cologne (Köln)',reading:'Hallo! Ich bin Sara. Ich wohne in Berlin.',readingQuestion:'Where does Sara live?',readingOptions:['Bonn','Berlin','Cologne (Köln)'],readingAnswer:'Berlin'},
 4: {question:'Stell dich kurz vor.',meaning:'Introduce yourself briefly.',phrase:'Ich heiße Lina. Ich wohne in Bonn.',translation:'My name is Lina. I live in Bonn.',tip:'Give your name and city. Two short sentences are enough. You can add your country if you want.',frame:'Ich heiße Lina. Ich ___ in Bonn.',answer:'wohne',explanation:'Use heiße for your name, komme aus for your country and wohne in for your city.',audio:'Hallo, ich heiße Alex. Ich komme aus Indien und wohne in Hamburg.',listeningQuestion:'Which introduction did you hear?',listeningOptions:['Alex, lives in Hamburg','Alex, lives in Bonn','Lina, lives in Hamburg'],listeningAnswer:'Alex, lives in Hamburg',reading:'Hallo zusammen! Ich heiße Noa. Ich komme aus Deutschland. Ich wohne in Wien.',readingQuestion:'What does Noa tell the group?',readingOptions:['Name and favourite food','Name, country and city','Only a name'],readingAnswer:'Name, country and city'},
};
export function isGuidedStarter(id: string) { return /^active-a1-m01-l0[1-4]-v1$/.test(id); }
