import type { VocabularyCategory, VocabularyWord } from "@/app/vocabulary/data";

// Editorial A2 placements: everyday people, places, actions and descriptions.
// This is a learning sequence, not a claim of official exam certification.
// Match headwords, never row positions, so existing progress IDs stay stable.
const EVERYDAY_TOPICS: [VocabularyCategory, string][] = [
  ["Familie & Menschen", "Heimat|Geburt|Herkunft|Humor|Geschlecht|Kumpel|Angehörige|Erziehung|Betreuung|Persönlichkeit|Angestellte|Verwandte|Begleitung|Trauer|Mitleid|Schwangerschaft|Kita|Dating|Benehmen|Witwe|Teen|Geste|Heirat|Freundeskreis|Begegnung|Schönheit|Schneider|Kerl|Mädel|Migrant|Künstlerin|Freiwillige|Kamerad|Glaube|Harmonie|Kompliment|Neid|Jahrestag|Lebensweise|alleinerziehend|weiblich|männlich|schwanger|treu|verheiraten|aufwachsen|umarmen|verabschieden|begegnen"],
  ["Zuhause & Wohnen", "Neubau|Haushalt|Villa|Heim|Umbau|Kammer|Staub|Dunkelheit|Beleuchtung|Faden|Öffnung|Rohr|Wohnraum|Reinigung|Beton|Kram|Container|Hülle|Balken|Stange|Quadratmeter|Bude|Einbrecher|Schmuck|Plastik|Sorte|Fass|Klappe|Wärme|Metall|Eisen|Kälte|vermieten|reinigen|räumen|umbauen|beleuchten|aufbewahren|saugen|bohren|schmücken|schmelzen|abdecken|einbauen|befestigen|verschließen|einrichten|abschalten|anschließen|einlegen"],
  ["Essen & Trinken", "Nahrung|Geruch|Genuss|Duft|Brauerei|Wirt|Pilz|Korn|Flüssigkeit|Becken|Geschmack|rühren|zubereiten|kühlen|vermischen|leeren|schlucken|ernähren|fasten|schneiden|abschneiden|haltbar|pur|fett|frisch|süß|bitter"],
  ["Einkaufen & Kleidung", "Händler|Käufer|Katalog|Gutschein|Bezahlung|Laden|Empfang|Kredit|Luxus|Budget|Filiale|Versand|Porto|Label|Trikot|Uniform|Einzelhandel|Kombi|Salon|Zubehör|Kabine|Kopftuch|Tarif|Kleinanzeige|Kollektion|Registrierung|Cap|Währung|Handel|Gewicht|Menge|Mangel|Umtausch|ausverkauft|gratis|inklusive|schick|defekt|kostenfrei|netto|brutto|passend|kassieren|verpacken|verschenken|verschicken|auszahlen|zurückgeben|vergrößern|abgeben|besorgen|anprobieren"],
  ["Schule & Lernen", "Übersetzung|Schwierigkeit|Hochschule|Lehre|Vortrag|Vorbereitung|Schrift|Chemie|Definition|Mathematik|Motivation|Unterlage|Dialog|Abitur|Handbuch|Eintrag|Experiment|Gedächtnis|Seminar|Tagebuch|Lücke|Belohnung|Einleitung|Exemplar|Übersetzer|Aufsatz|Diplom|Abwesenheit|Anweisung|Überschrift|Akzent|Dialekt|Aussprache|Handschrift|Jahrbuch|Realschule|Untertitel|Vorwort|Schulzeit|Abkürzung|Fortschritt|Korrektur|Aufnahme|Beispiel|schriftlich|mündlich|verständlich|unverständlich|deutschsprachig|elektrisch|notieren|nachfragen|nachlesen|beibringen|erlernen|unterstreichen|übersetzen|ergänzen|mitteilen|benutzen|aufpassen|blättern|ausprobieren|erraten"],
  ["Arbeit & Beruf", "Leiter|Tätigkeit|Teilnahme|Manager|Besitzer|Unternehmer|Anfrage|Anbieter|Messe|Sitzung|Beratung|Berater|Fabrik|Handwerk|Architekt|Designer|Verdienst|Veranstalter|Ingenieur|Ruhestand|Techniker|Zimmermann|Workshop|Krankenkasse|Kurier|Ansprechpartner|Arbeitsbedingung|Bezahlung|Auftrag|Planung|Kontakt|Schicht|Team|tätig|pünktlich|zuständig|beruflich|beschäftigen|benötigen|erledigen|kontrollieren|leiten|produzieren|veranstalten|vorbereiten|organisieren|eintragen|einteilen|aufteilen|weiterhelfen|weitergeben|zusagen|nachholen"],
  ["Stadt & Verkehr", "Gegend|Umgebung|Entfernung|Hafen|Radfahrer|Route|Kennzeichen|Bundesland|Helm|Denkmal|Passagier|Hubschrauber|Rückseite|Flieger|Straßenverkehr|Ortsteil|Landstraße|Heimatstadt|Stadtgebiet|Landung|Allee|Fahrbahn|Pfad|Südwesten|Maut|Strecke|Kreuzung|Stau|Stufe|Übergang|Ampel|verkehrt|städtisch|ländlich|regional|nah|fern|zentral|landen|überholen|überfahren|anfahren|zurückkehren|hingehen|zurückgehen|einsteigen|umrechnen|abwarten|schieben|steigen|betreten|verlassen"],
  ["Reisen & Unterkunft", "Aufenthalt|Tourismus|Ausrüstung|Wüste|Orientierung|Camp|Alarm|Mittelmeer|Ostsee|Panorama|Bucht|Nationalpark|Reisepass|Erholung|Horizont|Siedlung|Quartier|Erlaubnis|Reiseleiter|Gepäck|Besichtigung|Aussicht|Abenteuer|international|ausländisch|einheimisch|sehenswert|jährlich|reisen|tauchen|segeln|erholen|unterbringen|verpassen|einpacken|auspacken|erkunden"],
  ["Gesundheit & Körper", "Medizin|Knochen|Zunge|Kugel|Zelle|Faust|Rettung|Unglück|Hintern|Blase|Stich|Gift|Sturz|Nacken|Nagel|Sauerstoff|Leber|Organ|Puls|Dosis|Entspannung|Pille|Hygiene|Lunge|Biss|Haut|Schmerzen|Besserung|Körper|schmerzhaft|ärztlich|rezeptfrei|blind|taub|blass|körperlich|betrunken|heil|gesund|verletzen|sterben|retten|leiden|heilen|pflegen|jucken|schmerzen|erkranken|kratzen|schonen|zittern|ausruhen"],
  ["Freizeit, Kultur & Sport", "Kultur|Saison|Runde|Serie|Show|Künstler|Interview|Szene|Star|Liga|Finale|Stil|Stimmung|Zuschauer|Auftritt|Sammlung|Design|Figur|Sieger|Studio|Unterhaltung|Pop|Kapitän|Spannung|Schriftsteller|Klang|Profi|Halbfinale|Weltmeister|Pokal|Talent|Spieltag|Gesang|Halbzeit|Platte|Wette|Jazz|Sportler|Rätsel|Reiter|Sprung|Rekord|Malerei|Marathon|Boxen|Weltmeisterschaft|Medaille|Musical|Applaus|Komödie|Krimi|Läufer|Karneval|Schauspiel|Wettkampf|Feuerwerk|Klassik|Thriller|Sammler|Atelier|freizeit|romantisch|kreativ|sportlich|musikalisch|filmen|basteln|siegen|wetten|loben|jubeln|streamen"],
  ["Natur, Wetter & Umwelt", "Natur|Schatten|Frühjahr|Landwirtschaft|Wurzel|Ufer|Adler|Höhle|Planet|Universum|Hügel|Fantasie|Flamme|Erdbeben|Insekt|Ernte|Buche|Feder|Forst|Hirsch|Dschungel|Leine|Männchen|Teich|Weide|Niederschlag|Damm|Kiefer|Berg|Wald|Wiese|windig|feucht|eiskalt|flach|steil|nördlich|südlich|westlich|östlich|wehen|fließen|ernten|anbauen|verbrennen|bedecken"],
  ["Medien & Digitales", "Werbung|Inhalt|Sender|Blog|User|Kanal|Server|Netzwerk|Chat|Account|Logo|Update|Web|Akku|Klick|Filter|Gaming|Hardware|Internetseite|Speicher|Abo|Audio|Tageszeitung|Lautsprecher|Newsletter|Elektronik|Spam|Router|Format|Code|Forum|online|offline|mobil|technisch|digital|herunterladen|hochladen|speichern|eingeben|installieren|programmieren|weiterleiten|einfügen|senden|anschalten"],
  ["Dienstleistungen & Behörden", "Sicherheit|Gefahr|Verbot|Botschaft|Antrag|Steuer|Beamte|Ausweis|Rechtsanwalt|Sparkasse|Bürgermeister|Gemeinde|Post|Recht|Polizei|Strafe|Wache|Absage|Unterschrift|Bestätigung|gültig|ungültig|offiziell|legal|illegal|verlängern|beachten|anzeigen|ausfüllen|unterschreiben|bestrafen"],
  ["Zeit, Zahlen & Mengen", "Nähe|Höhe|Anzahl|Zeitpunkt|Summe|Drittel|Gegenwart|Weile|Tempo|Spielzeit|Vorjahr|Quartal|Periode|Minimum|Jahrestag|Viertel|Hälfte|einig|gesamt|meist|einzeln|knapp|übrig|notwendig|zahlreich|vollständig|komplett|selten|häufig|täglich|wöchentlich|monatlich|kurzfristig|damals|bisher|irgendwann|niemals|momentan|spätestens|anfangs|nochmals|beinahe|jederzeit|rechtzeitig|demnächst|umsonst|kürzlich|vorhin|neulich|dauernd|woanders|nirgendwo|herunter|circa|zwischendurch|hinauf|tagsüber"],
  ["Adjektive & Adverbien", "ernst|ehrlich|wahr|tot|unglaublich|extra|real|unterschiedlich|witzig|zufällig|speziell|ordentlich|locker|dicht|herzlich|übel|fair|verrückt|peinlich|fein|streng|seltsam|riesig|schief|hilfreich|ideal|kompliziert|berühmt|kräftig|niedrig|wütend|herrlich|gemein|schlau|heimlich|attraktiv|furchtbar|gewöhnlich|friedlich|lebendig|unangenehm|grob|geheim|logisch|anwesend|nervös|sinnlos|gründlich|sanft|aggressiv|feucht|unschuldig|harmlos|liebevoll|unzufrieden|schmal|nervig|unfair|ärgerlich|frech|bescheiden|ekelhaft|schüchtern|nutzlos|neidisch|hilflos|feige|albern|alltäglich|schädlich|elegant|winzig|eifersüchtig|munter|optimistisch|wundervoll|nun|wohl|dazu|dafür|davon|sonst|kaum|überhaupt|eher|darum|insgesamt|völlig|irgendwie|dagegen|ebenso|unbedingt|dahin|außerhalb|mitten|sowieso|dahinter|hinterher|nebenbei|dazwischen|durcheinander|glücklicherweise"],
  ["Verben", "stimmen|schaffen|gefallen|reichen|bieten|stecken|erleben|überraschen|behalten|hassen|kümmern|überlegen|trennen|verschwinden|enttäuschen|beantworten|klappen|nachdenken|schweigen|spenden|unterhalten|gewöhnen|spüren|verlieben|ansprechen|auffallen|aufheben|berühren|stehlen|aufregen|abnehmen|schreien|fürchten|heben|nerven|streichen|wundern|trauen|blasen|beruhigen|mitbekommen|einfallen|übertreiben|beschweren|schalten|ausfallen|zusehen|austauschen|herausfinden|ruhen|verwechseln|lecken|heulen|ausdenken|stinken|zunehmen|schütteln|staunen|bewundern|sortieren|wegnehmen|abstellen|flirten|anzünden|erschrecken|rutschen|umarmen|streicheln|einstecken"],
];

const B1_TOPICS: [VocabularyCategory, string][] = [
  ["Dienstleistungen & Behörden", "Politik|Regierung|Krieg|Partei|König|Opfer|Bevölkerung|Politiker|Präsident|Schuld|Gewalt|Freiheit|Volk|Schutz|Union|Amt|Soldat|Armee|Waffe|Religion|Angriff|Frieden|Kommission|Parlament|Förderung|Republik|Minister|Anwalt|Strafe|Verbrechen|Gefängnis|Tat|Bezirk|Beamte|Gerechtigkeit|Regelung|Verteidigung|Nation|Militär|Priester|Befehl|Kloster|Provinz|Protest|Muslim|Katastrophe|Versammlung|Botschafter|Erbe|Demonstrant|Kanzler|Kommune|Demonstration|Anordnung|Testament|Stadtrat|Einbruch|Offizier|Moschee|Gottesdienst|Kommissar|Herrscher|Steuerzahler|Bundeskanzler|Pastor|Ermittler|Streik|Räuber|Taufe|Dieb|Profit|Betrüger"],
  ["Arbeit & Beruf", "Wirtschaft|Leistung|Industrie|Leitung|Verwendung|Produktion|Bedarf|Handel|Gewinn|Anwendung|Nutzung|Posten|Unternehmer|Management|Strategie|Struktur|Konkurrenz|Kampagne|Agentur|Betreiber|Ressource|Kongress|Entwickler|Kaufmann|Lizenz|Konsum|Vertretung|Priorität|Produzent|Entlassung|Export|Transfer|Spezialist|Installation|Arbeitsbedingung"],
  ["Schule & Lernen", "Begriff|Studie|Technik|Forschung|Grundlage|Wissenschaft|Einführung|Institut|Prinzip|Theorie|Verständnis|Experte|Kategorie|Niveau|Formel|Journalist|Statistik|Wissenschaftler|Archiv|Element|Umfrage|Perspektive|Edition|Forscher|Bachelor|Faktor|Technologie|Aspekt|Objekt|Symbol|Argument|Dokumentation|Intelligenz|Entdeckung|Beobachtung|Erfindung|Fakultät|Herausgeber|Campus|Maßstab|Abbildung|Verzeichnis|Publikation|Anmerkung|Ratgeber|Inspiration|Kontrast|Erfinder|Verleger"],
  ["Freizeit, Kultur & Sport", "Meister|Werk|Verlag|Finale|Presse|Stil|Tradition|Vorstellung|Auftritt|Design|Anhänger|Figur|Sieger|Trend|Motto|Vorbild|Game|Pop|Held|Kapitän|Cup|Drama|Jagd|Halbfinale|Fassung|Arena|Motiv|Regisseur|Legende|Model|Champion|Fortsetzung|Pirat|Treffer|DJ|Sound|Tempel|Vergnügen|Dom|Moderator|Reiter|Coach|Episode|Jury|Bronze|Duo|Malerei|Disziplin|Leinwand|Marathon|Crew|Kapelle|Match|Viertelfinale|Bass|Künstlerin|Amateur|Fantasy|Dance|Medaille|Musical|Favorit|Rapper|Trio|Orgel|Anime|Stürmer|Takt|Komponist|Horror|Schiedsrichter|Trailer|Comedy|Drache|Charme|Darsteller|Heimspiel|Punk|Country|Blues|Porträt|Feuerwerk|Jersey|Klassik|Thriller|Wellness|Bestseller|Casino|Statue|Atelier"],
  ["Natur, Wetter & Umwelt", "Kreis|Kraft|Gebiet|Silber|Schwanz|Kern|Brand|Landwirtschaft|Wesen|Kohle|Oberfläche|Flügel|Gipfel|Planet|Metall|Ufer|Adler|Alpe|Horn|Rasse|Echo|Explosion|Flamme|Erdbeben|Europäer|Schäfer|Glanz|Ernte|Horizont|Buche|Hang|Mühle|Feder|Forst|Grube|Niederschlag|Damm|Hirsch|Korn|Kiefer|Dschungel|Teich|Weide"],
  ["Medien & Digitales", "Medium|System|Version|Funktion|Inhalt|Interview|News|Code|Forum|Blog|Sender|User|Kanal|Server|Community|Netzwerk|Chat|Account|Logo|Update|Web|Stream|Funk|Empfänger|Klick|Feedback|Filter|Gaming|Hardware|Player|Rundfunk|Speicher|Tweet|URL|Audio|Channel|Tageszeitung|Redakteur|Hacker|Lautsprecher|Banner|Cam|Newsletter|Elektronik|Spam|Router"],
];

export function applyVocabularyPlacement(words: VocabularyWord[]): VocabularyWord[] {
  const placements = new Map<string, VocabularyCategory>();
  for (const [topic, text] of EVERYDAY_TOPICS) for (const word of text.split("|")) if (!placements.has(word)) placements.set(word, topic);
  const available = new Set(words.filter((word) => word.id.startsWith("lexicon-b1-")).map((word) => word.german.replace(/^(der|die|das) /, "").split(",")[0]));
  const a2 = new Set<string>();
  const perTopic = new Map<VocabularyCategory, number>();
  for (const [headword, topic] of placements) {
    if (available.has(headword) && (perTopic.get(topic) ?? 0) < 34) {
      a2.add(headword);
      perTopic.set(topic, (perTopic.get(topic) ?? 0) + 1);
    }
  }
  for (const [topic, text] of B1_TOPICS) for (const word of text.split("|")) if (!placements.has(word)) placements.set(word, topic);
  return words.map((word) => {
    const headword = word.german.replace(/^(der|die|das) /, "").split(",")[0];
    const category = placements.get(headword);
    return category && word.id.startsWith("lexicon-b1-") ? { ...word, level: a2.has(headword) ? "A2" : "B1", category } : word;
  });
}
