type VerbHeadword = {
  english: string;
  german: string;
};

const VERB_FORM_HEADWORDS: Record<string, VerbHeadword> = {
  "ändert": { english: "to change", german: "ändern" },
  "antwortet": { english: "to answer", german: "antworten" },
  "arbeitet": { english: "to work", german: "arbeiten" },
  "aufsteht": { english: "to get up", german: "aufstehen" },
  "backt": { english: "to bake", german: "backen" },
  "bedankt": { english: "to thank", german: "danken" },
  "begann": { english: "to begin", german: "beginnen" },
  "beginnt": { english: "to begin", german: "beginnen" },
  "bekommt": { english: "to get / receive", german: "bekommen" },
  "benutzt": { english: "to use", german: "benutzen" },
  "besprach": { english: "to discuss", german: "besprechen" },
  "bewegt": { english: "to move", german: "bewegen" },
  "bezahlt": { english: "to pay", german: "bezahlen" },
  "bin": { english: "to be", german: "sein" },
  "bittet": { english: "to ask / request", german: "bitten" },
  "bleibt": { english: "to stay", german: "bleiben" },
  "blieb": { english: "to stay", german: "bleiben" },
  "braucht": { english: "to need", german: "brauchen" },
  "bringt": { english: "to bring", german: "bringen" },
  "dankt": { english: "to thank", german: "danken" },
  "deckt": { english: "to set / cover", german: "decken" },
  "druckt": { english: "to print", german: "drucken" },
  "empfiehlt": { english: "to recommend", german: "empfehlen" },
  "endet": { english: "to end", german: "enden" },
  "endete": { english: "to end", german: "enden" },
  "entsteht": { english: "to arise", german: "entstehen" },
  "ergab": { english: "to result", german: "ergeben" },
  "erinnert": { english: "to remember", german: "sich erinnern" },
  "erklärt": { english: "to explain", german: "erklären" },
  "erwartet": { english: "to expect", german: "erwarten" },
  "fährt": { english: "to travel / drive", german: "fahren" },
  "fängt": { english: "to start", german: "anfangen" },
  "fehlt": { english: "to be missing", german: "fehlen" },
  "folgt": { english: "to follow", german: "folgen" },
  "fragt": { english: "to ask", german: "fragen" },
  "fragte": { english: "to ask", german: "fragen" },
  "freut": { english: "to be happy", german: "sich freuen" },
  "frühstückt": { english: "to eat breakfast", german: "frühstücken" },
  "funktioniert": { english: "to work / function", german: "funktionieren" },
  "geprüft": { english: "to check", german: "prüfen" },
  "geschnitten": { english: "to cut", german: "schneiden" },
  "gewinnt": { english: "to win", german: "gewinnen" },
  "geworden": { english: "to become", german: "werden" },
  "gibt": { english: "to give", german: "geben" },
  "ging": { english: "to go", german: "gehen" },
  "glaubte": { english: "to believe", german: "glauben" },
  "grüßt": { english: "to greet", german: "grüßen" },
  "hält": { english: "to stop / hold", german: "halten" },
  "hat": { english: "to have", german: "haben" },
  "hatte": { english: "to have", german: "haben" },
  "hatten": { english: "to have", german: "haben" },
  "heiße": { english: "to be called", german: "heißen" },
  "heißt": { english: "to be called", german: "heißen" },
  "hilft": { english: "to help", german: "helfen" },
  "hört": { english: "to hear / listen", german: "hören" },
  "isst": { english: "to eat", german: "essen" },
  "ist": { english: "to be", german: "sein" },
  "kam": { english: "to come", german: "kommen" },
  "kann": { english: "to be able to", german: "können" },
  "kannte": { english: "to know", german: "kennen" },
  "kannten": { english: "to know", german: "kennen" },
  "kauft": { english: "to buy", german: "kaufen" },
  "klingelt": { english: "to ring", german: "klingeln" },
  "kocht": { english: "to cook", german: "kochen" },
  "kommt": { english: "to come", german: "kommen" },
  "kostet": { english: "to cost", german: "kosten" },
  "lächelt": { english: "to smile", german: "lächeln" },
  "lacht": { english: "to laugh", german: "lachen" },
  "lädt": { english: "to invite", german: "einladen" },
  "läuft": { english: "to run / walk", german: "laufen" },
  "lebt": { english: "to live", german: "leben" },
  "leiht": { english: "to borrow", german: "leihen" },
  "lernt": { english: "to learn", german: "lernen" },
  "liegt": { english: "to lie / be located", german: "liegen" },
  "liest": { english: "to read", german: "lesen" },
  "macht": { english: "to do / make", german: "machen" },
  "mag": { english: "to like", german: "mögen" },
  "markiert": { english: "to mark", german: "markieren" },
  "merkt": { english: "to notice", german: "merken" },
  "muss": { english: "to have to", german: "müssen" },
  "musst": { english: "to have to", german: "müssen" },
  "nannte": { english: "to name", german: "nennen" },
  "nimmt": { english: "to take", german: "nehmen" },
  "öffnet": { english: "to open", german: "öffnen" },
  "passt": { english: "to fit", german: "passen" },
  "plant": { english: "to plan", german: "planen" },
  "probiert": { english: "to try", german: "probieren" },
  "redeten": { english: "to talk", german: "reden" },
  "ruft": { english: "to call", german: "anrufen" },
  "sagt": { english: "to say", german: "sagen" },
  "sah": { english: "to see", german: "sehen" },
  "schaut": { english: "to look", german: "schauen" },
  "scheint": { english: "to seem / shine", german: "scheinen" },
  "schickt": { english: "to send", german: "schicken" },
  "schienen": { english: "to seem", german: "scheinen" },
  "schläft": { english: "to sleep", german: "schlafen" },
  "schließt": { english: "to close", german: "schließen" },
  "schneidet": { english: "to cut", german: "schneiden" },
  "schreibt": { english: "to write", german: "schreiben" },
  "schrieb": { english: "to write", german: "schreiben" },
  "sei": { english: "to be", german: "sein" },
  "setzt": { english: "to set / place", german: "setzen" },
  "sieht": { english: "to see", german: "sehen" },
  "sind": { english: "to be", german: "sein" },
  "singt": { english: "to sing", german: "singen" },
  "sitzt": { english: "to sit", german: "sitzen" },
  "spielt": { english: "to play", german: "spielen" },
  "sprach": { english: "to speak", german: "sprechen" },
  "spricht": { english: "to speak", german: "sprechen" },
  "stand": { english: "to stand", german: "stehen" },
  "steht": { english: "to stand", german: "stehen" },
  "steigt": { english: "to get on", german: "einsteigen" },
  "studiert": { english: "to study", german: "studieren" },
  "sucht": { english: "to search", german: "suchen" },
  "tanzt": { english: "to dance", german: "tanzen" },
  "trägt": { english: "to carry / wear", german: "tragen" },
  "trifft": { english: "to meet", german: "treffen" },
  "trinkt": { english: "to drink", german: "trinken" },
  "tut": { english: "to do / hurt", german: "tun" },
  "unterschieden": { english: "to distinguish", german: "unterscheiden" },
  "verändert": { english: "to change", german: "verändern" },
  "versteht": { english: "to understand", german: "verstehen" },
  "wählt": { english: "to choose", german: "wählen" },
  "war": { english: "to be", german: "sein" },
  "wartet": { english: "to wait", german: "warten" },
  "will": { english: "to want", german: "wollen" },
  "wird": { english: "to become", german: "werden" },
  "wirft": { english: "to throw", german: "werfen" },
  "wohnt": { english: "to live", german: "wohnen" },
  "wollte": { english: "to want", german: "wollen" },
  "zeichnet": { english: "to draw", german: "zeichnen" },
  "zeigt": { english: "to show", german: "zeigen" },
  "zieht": { english: "to move / pull", german: "ziehen" },
};

export function verbHeadwordForForm(german: string) {
  return VERB_FORM_HEADWORDS[german.toLocaleLowerCase("de").trim()] ?? null;
}

export function germanVerbLemma(german: string) {
  return verbHeadwordForForm(german)?.german ?? german;
}
