import type { Story, Unit } from "@/app/curriculum/types";

export type A1Story = Story;
export type A1Unit = Unit;

type Seed = [title: string, text: string];

type UnitSeed = {
  title: string;
  shortTitle: string;
  description: string;
  grammar: string;
  canDo: string;
  color: string;
  stories: Seed[];
};

const UNIT_SEEDS: UnitSeed[] = [
  {
    title: "Hallo! Ich bin …",
    shortTitle: "Ich & Hallo",
    description: "Menschen begrüßen, persönliche Angaben machen und einfache Fragen stellen.",
    grammar: "sein · Personalpronomen · W-Fragen",
    canDo: "Ich kann mich vorstellen und einfache persönliche Fragen stellen.",
    color: "#e55f45",
    stories: [
      ["Guten Morgen, Mia!", "Mia ist neu in Berlin. Am Morgen geht sie in ein Café. Der Kellner sagt: „Guten Morgen! Wie heißen Sie?“ Mia antwortet: „Ich heiße Mia. Und Sie?“ Der Kellner heißt Paul. Jetzt kennt Mia ihre erste Person in Berlin."],
      ["Der Name auf dem Becher", "Im Sprachkurs steht ein Becher auf dem Tisch. Auf dem Becher steht „Leo“. Ein Mann kommt und fragt: „Ist das mein Becher?“ Sara sagt: „Ja. Bist du Leo?“ Der Mann lacht. „Ja, ich bin Leo. Danke!“"],
      ["Meine neue Nachbarin", "An der Tür steht eine Frau. Sie sagt: „Hallo, ich bin Eva. Ich wohne nebenan.“ Tom antwortet: „Ich heiße Tom. Woher kommst du?“ Eva kommt aus Wien. Tom kommt aus Köln. Beide sprechen Deutsch und ein bisschen Englisch."],
      ["Eine Nummer zu viel", "Nora schreibt ihre Telefonnummer auf einen Zettel. Die Nummer ist 0176 458 320. Ben liest die Nummer, aber er sagt 0176 485 320. Nora lächelt und sagt: „Nein, vier-fünf-acht.“ Jetzt ist die Nummer richtig."],
      ["Heute ist mein Geburtstag", "Lina hat heute Geburtstag. Sie ist neunzehn Jahre alt. Im Kurs fragt der Lehrer: „Wann ist dein Geburtstag?“ Lina sagt: „Heute!“ Alle sagen: „Alles Gute!“ Lina ist überrascht und sehr froh."],
      ["Im Deutschkurs", "Im Kurs sitzen acht Personen. Frau Sommer ist die Lehrerin. Sie fragt: „Wie heißen Sie und woher kommen Sie?“ Omar kommt aus Ägypten, Ana aus Spanien und Ken aus Japan. Alle lernen zusammen Deutsch."],
      ["Drei Länder, drei Sprachen", "Mila kommt aus Polen und spricht Polnisch. Ihr Freund Luca kommt aus Italien und spricht Italienisch. Zu Hause sprechen sie oft Englisch. Jetzt lernen beide Deutsch, denn sie leben in Hamburg."],
      ["Das Foto", "Auf dem Foto sind drei Personen. Links ist Amira, rechts ist Jonas und in der Mitte ist Ben. „Wer ist Ben?“, fragt Lea. Jonas zeigt auf den Jungen mit der roten Jacke. „Das ist Ben.“"],
      ["An der Rezeption", "Herr Kim ist im Hotel. Die Frau an der Rezeption fragt nach seinem Namen und seiner Adresse. Er sagt: „Kim, Minho Kim. Ich wohne in Bonn.“ Sein Zimmer ist Nummer zwölf. Herr Kim sagt: „Danke und gute Nacht.“"],
      ["Ein kurzes Gespräch", "Im Bus sitzt eine neue Studentin. Max fragt: „Hallo, wie heißt du?“ Sie heißt Aylin und studiert Musik. Max studiert auch Musik. Die beiden haben heute denselben Kurs. Der Bus kommt, und sie gehen zusammen zur Universität."],
    ],
  },
  {
    title: "Familie & Menschen",
    shortTitle: "Familie",
    description: "Über Familie, Alter, Berufe, Aussehen und Beziehungen sprechen.",
    grammar: "haben · Possessivartikel · Singular & Plural",
    canDo: "Ich kann meine Familie und bekannte Personen beschreiben.",
    color: "#8d6bd1",
    stories: [
      ["Das Familienfoto", "Sofia zeigt ihrem Freund ein Foto. „Das ist meine Mutter, und das ist mein Vater. Hier sind meine zwei Brüder.“ Ihr Freund fragt: „Hast du auch eine Schwester?“ Sofia sagt: „Ja, aber sie ist heute nicht auf dem Foto.“"],
      ["Oma wird siebzig", "Am Sonntag hat Oma Klara Geburtstag. Sie wird siebzig Jahre alt. Ihre drei Kinder und fünf Enkel kommen. Klara hat einen großen Kuchen. Auf dem Kuchen stehen sieben Kerzen, denn siebzig Kerzen sind zu viele."],
      ["Mein Bruder ist Koch", "Davids Bruder heißt Leon. Er ist Koch in einem kleinen Restaurant. Er arbeitet am Abend und schläft am Morgen. David ist Student und arbeitet nur am Samstag. Die Brüder haben sehr verschiedene Tage."],
      ["Die neue Kollegin", "Im Büro arbeitet eine neue Kollegin. Ihr Name ist Rania. Sie ist klein, hat dunkle Haare und trägt eine grüne Brille. Rania ist freundlich und spricht drei Sprachen. Alle Kollegen mögen sie."],
      ["Ein Baby in der Familie", "Mara hat eine neue Nichte. Das Baby heißt Ella und ist drei Wochen alt. Ella schläft viel und trinkt Milch. Ihr Bruder ist jetzt Vater. Mara ist sehr glücklich: Sie ist zum ersten Mal Tante."],
      ["Unser Hund Bruno", "Die Familie Wolf hat einen Hund. Sein Name ist Bruno. Er ist braun, groß und sehr lieb. Am Morgen geht Herr Wolf mit Bruno spazieren. Am Abend spielen die Kinder mit ihm im Garten."],
      ["Wer ist älter?", "Nina ist zwanzig und ihr Bruder Tim ist achtzehn. Tim sagt: „Ich bin größer, also bin ich älter!“ Nina lacht. „Nein, du bist nur größer. Ich bin zwei Jahre älter als du.“"],
      ["Zwei Schwestern", "Emma und Laura sind Schwestern. Emma hat blonde Haare und Laura hat schwarze Haare. Emma liest gern, Laura macht gern Sport. Beide lieben Musik und gehen am Freitag zusammen auf ein Konzert."],
      ["Der Arzt aus dem dritten Stock", "Herr Weber wohnt im dritten Stock. Er ist Arzt und arbeitet im Krankenhaus. Seine Frau ist Lehrerin. Ihre Tochter geht in die Schule. Die Familie grüßt jeden Morgen freundlich im Treppenhaus."],
      ["Viele Namen", "Bei Familie Nguyen ist heute ein Fest. Minh stellt alle vor: „Das sind meine Eltern, das ist mein Onkel und das sind meine Cousinen.“ Paul hört viele Namen. Am Ende weiß er nur noch: Alle sind sehr nett."],
    ],
  },
  {
    title: "Zuhause & Wohnen",
    shortTitle: "Zuhause",
    description: "Räume und Möbel benennen und sagen, wo sich Dinge befinden.",
    grammar: "der/die/das · ein/eine · es gibt · Akkusativ",
    canDo: "Ich kann eine Wohnung und Alltagsgegenstände beschreiben.",
    color: "#278071",
    stories: [
      ["Mein kleines Zimmer", "Jans Zimmer ist klein, aber hell. Es gibt ein Bett, einen Tisch und einen Stuhl. Das Bett steht links. Der Tisch steht am Fenster. Auf dem Tisch liegt ein Buch. Jan mag sein Zimmer."],
      ["Wo ist der Schlüssel?", "Mila sucht ihren Schlüssel. Er ist nicht in der Tasche und nicht auf dem Tisch. Sie schaut unter das Sofa. Dort liegt nur eine Socke. Dann sieht sie den Schlüssel in der Tür. Mila lacht."],
      ["Die rote Küche", "Annas Küche ist rot und weiß. Der Kühlschrank ist weiß, aber die Schränke sind rot. Auf dem Herd steht eine Suppe. Anna kocht gern, und ihre Freunde essen gern bei ihr."],
      ["Ein Tisch für vier", "Leo kauft einen neuen Tisch. Der Tisch ist rund und hat vier Stühle. In seiner Küche ist aber wenig Platz. Leo stellt den Tisch ins Wohnzimmer. Dort passt er gut neben das Fenster."],
      ["Das Fenster ist offen", "Es ist Winter und das Fenster im Schlafzimmer ist offen. Paula fragt: „Warum ist es hier so kalt?“ Ihr Bruder schließt das Fenster. Dann macht er die Heizung an. Bald ist das Zimmer wieder warm."],
      ["Im neuen Haus", "Familie Acar zieht heute um. Das neue Haus hat fünf Zimmer und einen Garten. Die Kinder wählen ihre Zimmer. Ela nimmt das Zimmer oben, denn es hat einen Balkon. Can nimmt das Zimmer neben dem Bad."],
      ["Ein Paket vor der Tür", "Vor der Wohnungstür steht ein großes Paket. Auf dem Paket steht der Name „Frau Klein“. Aber Frau Klein wohnt im zweiten Stock. Ben trägt das Paket nach oben. Frau Klein bedankt sich."],
      ["Der Schrank ist zu groß", "Nora hat einen schönen alten Schrank. Der Schrank ist aber zu groß für die Tür. Zwei Freunde helfen. Sie tragen den Schrank durch den Garten und durch die Balkontür. Jetzt steht er im Wohnzimmer."],
      ["Blumen auf dem Balkon", "Auf Emils Balkon stehen viele Pflanzen. Es gibt rote Blumen, grüne Kräuter und eine kleine Tomatenpflanze. Emil gibt ihnen jeden Morgen Wasser. Im Sommer isst er Tomaten vom eigenen Balkon."],
      ["Bei meiner Nachbarin", "Frau Kurz lädt Mia zum Tee ein. Ihre Wohnung ist gemütlich. An der Wand hängen viele Fotos. Im Regal stehen Bücher und kleine Figuren. Mia sieht ein Foto von Frau Kurz als junge Frau in Paris."],
    ],
  },
  {
    title: "Mein Tag & die Zeit",
    shortTitle: "Mein Tag",
    description: "Uhrzeiten nennen, Pläne machen und den Tagesablauf beschreiben.",
    grammar: "Präsens · Verbzweit · trennbare Verben · Zeit",
    canDo: "Ich kann über meinen Alltag, Termine und einfache Pläne sprechen.",
    color: "#d28a25",
    stories: [
      ["Der Wecker klingelt", "Um sieben Uhr klingelt der Wecker. Ida steht auf, öffnet das Fenster und macht Kaffee. Um halb acht frühstückt sie. Um acht Uhr fährt sie mit dem Fahrrad zur Arbeit."],
      ["Ein langer Montag", "Montags beginnt Toms Arbeit um neun Uhr. Am Vormittag schreibt er E-Mails. Um zwölf macht er Mittagspause. Am Nachmittag hat er drei Termine. Um sechs Uhr geht er müde nach Hause."],
      ["Der Bus um 8:15", "Leni muss um acht Uhr fünfzehn den Bus nehmen. Heute steht sie spät auf. Sie zieht sich schnell an und läuft zur Haltestelle. Der Bus kommt gerade. Leni steigt ein und findet noch einen Platz."],
      ["Mittwoch ist Kurstag", "Jeden Mittwoch lernt Karim Deutsch. Der Kurs fängt um achtzehn Uhr an und hört um neunzehn Uhr dreißig auf. Danach geht Karim mit zwei Freunden etwas trinken. Um zehn ist er zu Hause."],
      ["Am Wochenende", "Samstags schläft Julia lange. Dann kauft sie auf dem Markt ein. Am Nachmittag ruft sie ihre Eltern an. Sonntags macht sie Sport und liest. Am Sonntagabend plant sie die neue Woche."],
      ["Ein Termin beim Friseur", "Paul ruft beim Friseur an. „Haben Sie am Freitag Zeit?“ Die Frau sagt: „Ja, um Viertel nach drei.“ Paul schreibt den Termin in seinen Kalender. Am Freitag kommt er fünf Minuten früher."],
      ["Heute oder morgen?", "Mina möchte ihren Freund treffen. Er hat heute keine Zeit, aber morgen ist er frei. Sie treffen sich morgen um fünf im Park. Mina bringt Kaffee mit, und ihr Freund bringt Kuchen mit."],
      ["Der erste Mai", "Heute ist der erste Mai. In der Stadt ist ein Fest. Viele Geschäfte sind geschlossen. Familie Roth fährt nicht zur Arbeit. Sie geht in den Park und macht dort ein Picknick."],
      ["Zu spät im Kino", "Der Film beginnt um zwanzig Uhr. Alex kommt um fünf nach acht. Seine Freunde warten schon vor dem Kino. Sie kaufen schnell Popcorn und gehen hinein. Der Film hat gerade angefangen."],
      ["Gute Nacht, Stadt", "Um Mitternacht ist die Straße ruhig. Nur ein Taxi fährt vorbei. In der Bäckerei beginnt schon die Arbeit für den Morgen. Der Bäcker macht Brot, während die meisten Menschen noch schlafen."],
    ],
  },
  {
    title: "Essen & Trinken",
    shortTitle: "Essen",
    description: "Essen bestellen, Lebensmittel einkaufen und Vorlieben ausdrücken.",
    grammar: "mögen/möchten · Akkusativ · kein/nicht · Mengen",
    canDo: "Ich kann einfache Speisen bestellen und sagen, was ich mag.",
    color: "#d55369",
    stories: [
      ["Frühstück für zwei", "Mara macht Frühstück. Sie kocht zwei Eier und schneidet Brot. Tom möchte Kaffee, aber Mara trinkt lieber Tee. Es gibt auch Käse und Marmelade. Beide sitzen lange am Küchentisch."],
      ["Auf dem Markt", "Ben kauft ein Kilo Äpfel, zwei Tomaten und einen Salat. Die Verkäuferin sagt: „Das macht sechs Euro.“ Ben bezahlt und bekommt eine kleine Birne gratis. Die Birne isst er sofort."],
      ["Im Café", "Lea bestellt einen Cappuccino und ein Stück Kuchen. Ihr Freund möchte nur ein Wasser. Der Kellner fragt: „Mit oder ohne Eis?“ Der Freund sagt: „Ohne Eis, bitte.“"],
      ["Eine Suppe ohne Salz", "Nico kocht Gemüsesuppe. Er nimmt Kartoffeln, Karotten und Zwiebeln. Beim Essen sagt seine Schwester: „Die Suppe ist gut, aber es fehlt Salz.“ Nico bringt das Salz und beide lachen."],
      ["Pizza am Freitag", "Am Freitag bestellen drei Freunde Pizza. Jana möchte eine Pizza mit Käse. Luis nimmt eine Pizza mit Schinken. Eli möchte keine Pizza. Er bestellt einen Salat und Orangensaft."],
      ["Der leere Kühlschrank", "Im Kühlschrank ist fast nichts: eine Flasche Milch, ein Ei und eine Zitrone. Kim schreibt eine Einkaufsliste. Sie braucht Brot, Butter, Obst, Gemüse und Reis. Dann geht sie zum Supermarkt."],
      ["Ein Geburtstagskuchen", "Omar backt einen Kuchen für seine Mutter. Er braucht Mehl, Zucker, Eier und Schokolade. Der Kuchen ist klein, aber sehr süß. Seine Mutter freut sich und nimmt gleich ein zweites Stück."],
      ["Vegetarisch, bitte", "Im Restaurant fragt die Kellnerin: „Was möchten Sie essen?“ Nila sagt: „Ich esse kein Fleisch. Haben Sie etwas Vegetarisches?“ Die Kellnerin empfiehlt Nudeln mit Gemüse. Nila bestellt die Nudeln."],
      ["Drei Kugeln Eis", "Es ist heiß. Vor der Eisdiele wartet eine lange Reihe. Felix möchte drei Kugeln: Schokolade, Vanille und Erdbeere. Seine Freundin nimmt nur eine Kugel Zitrone. Sie setzen sich in den Schatten."],
      ["Das gemeinsame Abendessen", "Heute kochen alle zusammen. Ana macht Reis, Ben schneidet Gemüse und Salim deckt den Tisch. Um sieben ist das Essen fertig. Sie sagen „Guten Appetit“ und erzählen von ihrem Tag."],
    ],
  },
  {
    title: "Einkaufen & Kleidung",
    shortTitle: "Einkaufen",
    description: "Nach Preisen, Größen und Farben fragen und Alltagsdinge kaufen.",
    grammar: "dieser/diese · Adjektive · Zahlen & Preise · Fragen",
    canDo: "Ich kann einfache Dinge kaufen und Preise verstehen.",
    color: "#3977c4",
    stories: [
      ["Die blaue Jacke", "Mira sucht eine Jacke. Die schwarze Jacke ist schön, aber zu teuer. Die blaue Jacke kostet nur vierzig Euro. Sie passt gut. Mira kauft die blaue Jacke und trägt sie sofort."],
      ["Welche Größe?", "Im Geschäft fragt der Verkäufer: „Welche Größe haben Sie?“ Sam weiß es nicht. Er probiert Größe M. Das Hemd ist zu klein. Größe L passt. Sam nimmt das weiße Hemd."],
      ["Ein Geschenk für Papa", "Lia sucht ein Geschenk für ihren Vater. Eine Uhr kostet hundert Euro. Das ist zu teuer. Sie findet ein Buch über Musik für zwanzig Euro. Ihr Vater liest und hört gern Musik."],
      ["Auf dem Flohmarkt", "Auf dem Flohmarkt sieht Noah eine alte Lampe. Die Frau möchte fünfzehn Euro. Noah fragt: „Geht auch zehn Euro?“ Die Frau sagt: „Zwölf.“ Noah bezahlt zwölf Euro und nimmt die Lampe."],
      ["Bargeld oder Karte?", "An der Kasse kostet alles dreiundzwanzig Euro achtzig. Elena möchte mit Karte bezahlen. Das Gerät funktioniert nicht. Zum Glück hat sie dreißig Euro bar. Sie bekommt sechs Euro zwanzig zurück."],
      ["Die falschen Schuhe", "Ein Paket kommt für Alex. Darin sind rote Schuhe in Größe 38. Alex hat aber Größe 43 und bestellt schwarze Schuhe. Er bringt das Paket zur Post und schickt es zurück."],
      ["Ein Regenschirm", "Draußen regnet es stark. Vor dem Bahnhof gibt es einen kleinen Laden. Tarek kauft dort einen gelben Regenschirm. Er kostet acht Euro. Jetzt bleibt Tarek trocken und findet die Farbe lustig."],
      ["Nur noch ein T-Shirt", "Im Laden ist heute Schlussverkauf. Viele T-Shirts kosten fünf Euro. Es gibt nur noch ein grünes T-Shirt in Annas Größe. Grün ist nicht ihre Lieblingsfarbe, aber das T-Shirt passt sehr gut."],
      ["Die lange Einkaufsliste", "Frau Berg braucht Papier, Seife, Batterien und eine Zahnbürste. Im ersten Geschäft gibt es kein Papier. Im zweiten gibt es keine Batterien. Am Ende findet sie alles in einem großen Kaufhaus."],
      ["Kann ich das umtauschen?", "Jonas hat eine Hose gekauft. Zu Hause merkt er: Die Hose ist zu kurz. Am nächsten Tag geht er zurück. Er hat den Kassenbon dabei. Die Verkäuferin gibt ihm eine längere Hose."],
    ],
  },
  {
    title: "In der Stadt",
    shortTitle: "Stadt & Wege",
    description: "Orte finden, Wegbeschreibungen verstehen und öffentliche Angebote nutzen.",
    grammar: "lokale Präpositionen · Imperativ · Dativ · wo/wohin",
    canDo: "Ich kann nach dem Weg fragen und kurze Wegbeschreibungen verstehen.",
    color: "#2f8d9b",
    stories: [
      ["Wo ist der Bahnhof?", "Ein Tourist fragt: „Entschuldigung, wo ist der Bahnhof?“ Mia erklärt: „Gehen Sie geradeaus und dann links. Der Bahnhof ist neben der Post.“ Der Tourist bedankt sich und geht los."],
      ["Mit dem Bus zur Arbeit", "Ravi fährt jeden Morgen mit Bus 12. Er steigt am Marktplatz ein und am Krankenhaus aus. Heute fährt der Bus eine andere Straße. Ravi fragt den Fahrer und kommt trotzdem pünktlich an."],
      ["Die Apotheke", "Lena braucht eine Apotheke. Sie sieht eine Bank und einen Supermarkt, aber keine Apotheke. Eine Frau sagt: „Die Apotheke ist hinter der Kirche.“ Lena geht um die Kirche und findet sie."],
      ["Ein Brief nach Wien", "Paul schreibt einen Brief an seine Tante in Wien. Auf der Post kauft er eine Briefmarke. Er schreibt die Adresse auf den Umschlag und wirft den Brief in den gelben Briefkasten."],
      ["Geld am Automaten", "Nora braucht zwanzig Euro. Vor der Bank steht ein Geldautomat. Sie steckt ihre Karte ein, gibt ihre Nummer ein und wählt zwanzig Euro. Dann nimmt sie Geld und Karte."],
      ["Links, rechts, geradeaus", "Im Park sucht Emil den See. Ein Mann sagt: „Gehen Sie am Café vorbei. Dann rechts und immer geradeaus.“ Emil folgt dem Weg. Nach fünf Minuten sieht er den See und viele Enten."],
      ["Die Bibliothek", "Sara möchte ein deutsches Buch lesen. Die Bibliothek ist gegenüber der Schule. Dort zeigt sie ihren Ausweis und bekommt eine Karte. Sie leiht ein leichtes Buch mit kurzen Geschichten aus."],
      ["Hilfe bei der Polizei", "Ein Kind findet seine Mutter nicht. Es geht mit einer Frau zur Polizei. Der Polizist fragt nach dem Namen der Mutter. Kurz danach kommt die Mutter. Sie ist sehr froh und dankt allen."],
      ["An der Haltestelle", "An der Haltestelle steht: „Bus 6 kommt heute nicht.“ Zwei Personen warten dort. Eine Studentin liest die Information und sagt: „Wir können die Straßenbahn nehmen. Sie hält dort vorne.“"],
      ["Ein Plan der Stadt", "Im Hotel bekommt Ken einen Stadtplan. Er markiert das Museum, den Park und ein Restaurant. Zuerst geht er zum Museum, dann durch den Park und am Abend ins Restaurant. Der Plan hilft ihm sehr."],
    ],
  },
  {
    title: "Arbeit, Schule & Alltag",
    shortTitle: "Arbeit & Schule",
    description: "Einfache Aufgaben bei der Arbeit, in der Schule und bei Dienstleistungen bewältigen.",
    grammar: "können/müssen/wollen · Sie-Form · Satzklammer",
    canDo: "Ich kann einfache Aufgaben und Bitten im Alltag bewältigen.",
    color: "#6c7388",
    stories: [
      ["Mein erster Arbeitstag", "Heute arbeitet Elif zum ersten Mal im Hotel. Sie muss um sieben Uhr da sein. Ihre Kollegin zeigt ihr die Rezeption und die Zimmer. Elif kann gut Englisch sprechen. Das hilft bei vielen Gästen."],
      ["Eine Aufgabe im Kurs", "Herr Klein sagt: „Öffnen Sie bitte das Buch auf Seite zehn.“ Die Lernenden lesen einen kurzen Text. Danach müssen sie drei Fragen beantworten. Lea versteht eine Frage nicht und bittet um Hilfe."],
      ["Der Drucker geht nicht", "Im Büro möchte Ben ein Dokument drucken. Der Drucker funktioniert nicht. Er fragt seine Kollegin: „Kannst du mir helfen?“ Sie öffnet eine kleine Tür am Drucker und nimmt das Papier heraus. Jetzt geht er wieder."],
      ["Pause um zehn", "In der Bäckerei beginnt die Arbeit sehr früh. Um zehn Uhr machen alle Pause. Sie trinken Kaffee und essen ein Brötchen. Nach fünfzehn Minuten müssen sie wieder arbeiten, denn viele Kunden kommen."],
      ["Eine E-Mail an die Lehrerin", "Mina ist krank und kann heute nicht zum Kurs kommen. Sie schreibt: „Guten Morgen Frau Stein, ich bin leider krank. Kann ich die Hausaufgabe per E-Mail bekommen? Viele Grüße, Mina.“"],
      ["Das neue Wörterbuch", "Im Deutschkurs darf jedes Team ein Wörterbuch benutzen. Tim sucht das Wort „pünktlich“. Er findet die Bedeutung und erklärt sie seinem Partner. Dann schreiben beide einen einfachen Satz mit dem Wort."],
      ["Im Kindergarten", "Lea arbeitet im Kindergarten. Sie spielt mit Kindern, liest Geschichten und hilft beim Essen. Heute wollen die Kinder draußen spielen. Es regnet aber. Deshalb malen sie zusammen ein großes Bild."],
      ["Termin bei der Bank", "Herr Ali möchte ein Konto öffnen. Er hat um elf Uhr einen Termin. Die Mitarbeiterin braucht seinen Ausweis und seine Adresse. Herr Ali muss zwei Formulare unterschreiben. Dann ist das Konto fertig."],
      ["Eine Stelle im Café", "Nora sucht Arbeit. Im Fenster eines Cafés liest sie: „Hilfe gesucht.“ Sie geht hinein und spricht mit dem Chef. Nora kann am Wochenende arbeiten und spricht Deutsch und Spanisch. Am Samstag beginnt sie."],
      ["Feierabend", "Um siebzehn Uhr macht Jonas seinen Computer aus. Er räumt den Tisch auf und sagt den Kollegen „Tschüss“. Heute will er nicht direkt nach Hause. Er trifft einen Freund vor dem Kino."],
    ],
  },
  {
    title: "Freizeit, Wetter & Gesundheit",
    shortTitle: "Freizeit",
    description: "Über Hobbys, Wetter, Jahreszeiten und einfache Beschwerden sprechen.",
    grammar: "gern/lieber · war/hatte · Körper · deshalb",
    canDo: "Ich kann Hobbys, Wetter und einfache Beschwerden beschreiben.",
    color: "#4f9b52",
    stories: [
      ["Fußball im Park", "Am Samstag spielt eine Gruppe im Park Fußball. Luis spielt gern im Tor. Heute fehlt ein Spieler. Eine Frau fragt: „Kann ich mitspielen?“ Natürlich kann sie. Ihr Team gewinnt drei zu zwei."],
      ["Regen am Sonntag", "Mia will am Sonntag wandern. Am Morgen regnet es und der Himmel ist grau. Sie bleibt zu Hause, macht Tee und liest. Am Nachmittag kommt die Sonne. Mia geht noch eine Stunde spazieren."],
      ["Mein Lieblingsbuch", "Karim liest jeden Abend zehn Seiten. Sein Lieblingsbuch ist eine kurze Geschichte über einen Hund. Das Deutsch ist leicht. Neue Wörter schreibt Karim in ein Heft und liest sie laut."],
      ["Im Schwimmbad", "Es ist Sommer und sehr heiß. Nila und ihre Freunde gehen ins Schwimmbad. Nila kann gut schwimmen, aber Tom lernt noch. Er bleibt im kleinen Becken. Danach essen alle ein Eis."],
      ["Der Kopf tut weh", "Seit dem Morgen hat Ben Kopfschmerzen. Er trinkt Wasser und macht eine Pause. Am Nachmittag tut der Kopf noch weh. Ben ruft beim Arzt an und bekommt einen Termin für sechzehn Uhr."],
      ["Ein kalter Wintertag", "Draußen sind minus fünf Grad. Ava trägt einen Mantel, eine Mütze und warme Schuhe. Ihr Hund möchte trotzdem in den Park. Nach zehn Minuten wollen beide schnell wieder nach Hause."],
      ["Musik am Fenster", "Jeden Abend spielt Herr Costa Gitarre am Fenster. Die Nachbarn hören gern zu. Heute spielt er ein bekanntes Lied. Ein Kind singt im Hof mit. Am Ende klatschen alle an ihren Fenstern."],
      ["Gestern war ich krank", "Lena war gestern krank. Sie hatte Fieber und war sehr müde. Heute geht es ihr besser. Sie isst eine Suppe und bleibt noch zu Hause. Morgen möchte sie wieder arbeiten."],
      ["Ein Ausflug im Frühling", "Im April fährt Familie Kim an einen See. Die Sonne scheint, aber der Wind ist kühl. Sie machen ein Picknick und sehen viele Vögel. Die Kinder sammeln kleine Steine am Wasser."],
      ["Lieber tanzen", "Tara macht nicht gern Fitness. Sie findet das Training langweilig. Ihre Freundin lädt sie zum Tanzen ein. Die Musik ist toll, und Tara bewegt sich gern. Jetzt tanzt sie jeden Donnerstag."],
    ],
  },
  {
    title: "Reisen & A1 im echten Leben",
    shortTitle: "Reisen & Rückblick",
    description: "Reisen, im Hotel übernachten und alles aus A1 miteinander verbinden.",
    grammar: "und/aber/deshalb/dann · Wiederholung · Alltagssprache",
    canDo: "Ich kann einfache Reise- und Alltagssituationen bewältigen.",
    color: "#b7683b",
    stories: [
      ["Eine Fahrkarte nach Bonn", "Am Bahnhof sagt Eva: „Eine Fahrkarte nach Bonn, bitte.“ Der Mitarbeiter fragt: „Einfach oder hin und zurück?“ Eva braucht nur eine einfache Fahrt. Der Zug fährt um vierzehn Uhr von Gleis fünf."],
      ["Der schwere Koffer", "Omars Koffer ist sehr schwer. Er hat zu viele Schuhe und Bücher dabei. Am Bahnhof hilft ihm eine Frau. Zusammen tragen sie den Koffer in den Zug. Omar bedankt sich und findet seinen Platz."],
      ["Zimmer Nummer 24", "Im Hotel hat Niko ein Zimmer reserviert. Die Rezeptionistin fragt nach seinem Namen und Ausweis. Sein Zimmer ist Nummer vierundzwanzig im zweiten Stock. Das Frühstück gibt es von sieben bis zehn."],
      ["Der Zug hat Verspätung", "Der Zug nach Köln hat zwanzig Minuten Verspätung. Lea schreibt ihrem Freund eine Nachricht: „Ich komme später. Bitte warte im Café.“ Sie kauft Wasser und wartet am Gleis."],
      ["Eine Postkarte", "Mina schreibt aus München eine Postkarte: „Liebe Oma, die Stadt ist schön und das Wetter ist warm. Heute besuche ich ein Museum. Morgen fahre ich nach Hause. Viele Grüße, Mina.“"],
      ["Im Ferienhaus", "Vier Freunde mieten ein kleines Ferienhaus am Meer. Es hat zwei Schlafzimmer und eine Küche. Am Morgen schwimmen sie, am Nachmittag kochen sie. Abends sitzen sie vor dem Haus und hören das Meer."],
      ["Das falsche Gleis", "Ben wartet auf Gleis drei. Sein Zug fährt aber von Gleis acht. Er hört die Durchsage und läuft schnell. Eine Mitarbeiterin zeigt ihm den Weg. Ben erreicht den Zug in letzter Minute."],
      ["Ein Anruf von unterwegs", "Sofia ruft ihre Mutter an. „Hallo Mama, ich bin jetzt in Zürich. Die Reise war gut. Mein Hotel liegt direkt am See.“ Die Mutter fragt nach dem Wetter. Sofia sagt: „Kalt, aber sonnig.“"],
      ["Einladung zum Abendessen", "Luca schreibt an seine neuen Freunde: „Hallo! Ich koche am Freitag um sieben bei mir. Habt ihr Zeit? Bitte bringt Getränke mit.“ Alle antworten ja. Am Freitag sitzen sechs Personen an Lucas Tisch."],
      ["Hundert kleine Schritte", "Ana liest heute Geschichte Nummer hundert. Am Anfang konnte sie nur „Hallo“ sagen. Jetzt versteht sie kurze Texte über Familie, Arbeit, Essen und Reisen. Sie spricht langsam, aber sie spricht. Ana lächelt und beginnt die Geschichte noch einmal."],
    ],
  },
];

const UNIT_FLOW: string[][] = [
  [
    `{name} bleibt noch eine Weile im Café und hört den Menschen am Nachbartisch zu. Zwei Personen begrüßen sich, nennen ihre Namen und sprechen über ihre Länder. Die Sätze sind kurz, aber {name} versteht immer mehr. Dann kommt eine junge Frau und fragt, ob der Platz frei ist. {name} antwortet freundlich und stellt sich noch einmal vor. Beide schreiben ihre Telefonnummern in ein kleines Heft. Bevor sie gehen, bestellen sie Tee und üben zusammen: „Wie heißt du? Wo wohnst du? Welche Sprachen sprichst du?“ Am Anfang spricht {name} langsam. Nach einigen Minuten klingt das Gespräch schon leichter.`,
    `Später geht {name} zum Deutschkurs. Heute sitzen Menschen aus vielen Ländern im Raum. Die Lehrerin zeichnet eine Weltkarte an die Tafel und jede Person zeigt ihr Land. Danach arbeiten immer zwei Personen zusammen. Sie fragen nach Name, Alter, Adresse, Beruf und Sprache. {name} macht zuerst einen kleinen Fehler, verbessert den Satz und versucht es noch einmal. Der Partner hört geduldig zu und antwortet deutlich. In der Pause sprechen alle weiter. Niemand benutzt lange Sätze, trotzdem lernen sie viel voneinander. Als der Kurs endet, kann {name} drei neue Personen mit Namen begrüßen und ihnen eine einfache Frage stellen.`,
    `{name} möchte die neuen deutschen Wörter nicht vergessen. Zu Hause nimmt {name} zehn kleine Karten. Auf die Vorderseite kommt eine Frage, auf die Rückseite eine passende Antwort. Eine Karte sagt: „Woher kommst du?“ Eine andere fragt: „Wie ist deine Telefonnummer?“ Dann spricht {name} alle Fragen laut und antwortet ohne Hilfe. Manchmal fehlt ein Wort. Dann schaut {name} kurz ins Buch und beginnt den ganzen Satz neu. Am Abend ruft ein Freund an. {name} erzählt von den Menschen im Kurs und stellt auch dem Freund einige Fragen. So wird aus einer Übung ein richtiges Gespräch.`,
  ],
  [
    `{name} nimmt später das Familienfoto noch einmal in die Hand. Hinter jedem Gesicht steht eine kleine Geschichte. Die Mutter arbeitet am Vormittag, der Vater kocht am Wochenende, und die Kinder helfen im Garten. {name} beschreibt die Personen langsam: ihre Haare, ihre Augen, ihre Kleidung und ihren Charakter. Dann fragt ein Freund: „Wer ist die Frau neben deinem Bruder?“ {name} kennt die Antwort und erklärt die Beziehung. Gemeinsam vergleichen sie ihre Familien. Eine Familie ist groß, die andere klein, aber beide treffen sich gern zum Essen. Am Ende kennt der Freund nicht nur die Namen, sondern auch die wichtigsten Personen im Leben von {name}.`,
    `Am Sonntag kommt die ganze Familie zusammen. Schon am Morgen deckt {name} den Tisch und stellt Teller, Gläser und Blumen bereit. Ein Onkel bringt Brot, eine Tante bringt Salat, und die Cousinen haben einen Kuchen dabei. Beim Essen sprechen alle über Arbeit, Schule und Freizeit. Die Großeltern erzählen eine alte Geschichte, und die Kinder hören aufmerksam zu. Später machen sie ein neues Gruppenfoto. Es ist nicht leicht, denn ein Kind lacht, jemand schaut zur Seite und der Hund läuft vor die Kamera. Nach drei Versuchen gelingt das Bild. {name} sieht es an und denkt: Jede Person ist anders, aber zusammen sind wir eine Familie.`,
    `{name} schreibt für den Sprachkurs einen kurzen Text über wichtige Menschen. Zuerst entsteht eine Liste mit Namen, Alter und Beruf. Danach werden daraus ganze Sätze: „Meine Schwester heißt … Sie ist … Sie hat …“ {name} achtet auf mein, dein, sein und ihr. Diese kleinen Wörter sind manchmal schwierig. Ein Freund liest den Text und stellt zusätzliche Fragen. So ergänzt {name} Informationen über Hobbys, Wohnorte und gemeinsame Aktivitäten. Am Abend liest {name} den fertigen Text der Familie vor. Alle hören gern zu. Nur der Bruder sagt lachend, dass seine Haare nicht kurz, sondern sehr kurz sind. {name} verbessert das Wort sofort.`,
  ],
  [
    `{name} geht langsam durch alle Zimmer und macht eine Liste. Im Flur steht eine kleine Kommode, im Wohnzimmer liegen Bücher auf dem Tisch, und in der Küche fehlen noch zwei Stühle. {name} zeichnet einen einfachen Plan der Wohnung. Neben jedes Zimmer schreibt {name} die Möbel und die Farben. Danach hilft ein Freund beim Aufräumen. Sie stellen die Lampe neben das Sofa, hängen ein Bild an die Wand und legen den Teppich vor das Bett. Nicht alles passt sofort. Der Schrank ist zu breit und der Tisch steht im Weg. Gemeinsam finden sie für jeden Gegenstand einen guten Platz. Am Abend wirkt die Wohnung hell, ruhig und wirklich gemütlich.`,
    `Heute besucht {name} eine Nachbarin im Haus. Ihre Wohnung sieht ganz anders aus. Es gibt viele Pflanzen, bunte Kissen und alte Fotos. In der Küche steht ein großer Holztisch, an dem sechs Personen sitzen können. Die Nachbarin zeigt den Balkon und erklärt, welche Blumen Sonne brauchen. Danach trinken beide Tee im Wohnzimmer. {name} fragt: „Woher ist diese schöne Lampe?“ Die Nachbarin erzählt von einem Markt in Wien. Während des Gesprächs hört {name} viele Ortsangaben: auf dem Regal, unter dem Fenster, zwischen den Stühlen und hinter der Tür. Auf dem Heimweg wiederholt {name} die Ausdrücke leise und schaut dabei auf die Dinge im Treppenhaus.`,
    `{name} erwartet am Nachmittag Besuch und möchte alles vorbereiten. Zuerst öffnet {name} die Fenster, dann räumt {name} das Wohnzimmer auf. Die Tassen kommen in den Schrank, die Zeitung liegt auf dem Regal, und frische Blumen stehen jetzt auf dem Tisch. Plötzlich ist der Wohnungsschlüssel weg. {name} sucht in der Jacke, unter dem Sofa und neben der Haustür. Dort ist er nicht. Schließlich klingelt das Telefon. Beim Suchen findet {name} den Schlüssel direkt neben dem Telefonbuch. Kurz danach kommen die Gäste. Sie bringen Kuchen mit und fragen nach der neuen Wohnung. {name} zeigt ihnen jedes Zimmer und kann genau sagen, wo alles steht.`,
  ],
  [
    `{name} plant den nächsten Tag schon am Abend. Auf einem Blatt stehen Uhrzeiten und Aufgaben: um sieben aufstehen, um acht den Bus nehmen, am Vormittag arbeiten und um halb eins Mittagspause machen. Nach der Arbeit möchte {name} einkaufen und einen Freund treffen. Der Kalender ist voll, deshalb muss alles gut passen. Am Morgen läuft zunächst alles nach Plan. Dann kommt der Bus zehn Minuten später. {name} schreibt eine kurze Nachricht und erklärt die Verspätung. Niemand ist böse. In der Pause prüft {name} noch einmal den Kalender und verschiebt einen Termin. So bleibt am Abend sogar eine freie Stunde für Musik und ein ruhiges Essen.`,
    `Unter der Woche hat {name} einen festen Rhythmus. Montags und donnerstags ist Sprachkurs, dienstags wird Sport gemacht, und freitags endet die Arbeit früher. Heute fragt eine Freundin nach einem Treffen. Gemeinsam suchen sie einen passenden Tag. Mittwoch geht nicht, denn {name} hat einen Termin beim Arzt. Samstagvormittag ist auch voll, aber am Nachmittag haben beide Zeit. Sie verabreden sich um Viertel nach vier vor dem Kino. {name} schreibt Ort und Uhrzeit sofort ins Handy. Später erzählt {name} den Tagesplan laut auf Deutsch. Die Verben stehen an der richtigen Stelle, und bei aufstehen, anrufen und einkaufen hört man deutlich die zwei Teile.`,
    `Am Wochenende möchte {name} nicht jede Minute planen. Trotzdem gibt es einige Dinge zu tun. Nach einem langen Frühstück wird die Wäsche gemacht und die Küche aufgeräumt. Danach ruft {name} die Eltern an. Das Gespräch dauert fast eine Stunde, weil es viele Neuigkeiten gibt. Am Nachmittag scheint die Sonne. {name} fährt mit dem Fahrrad in den Park und trifft dort zufällig zwei Freunde. Sie kaufen Kaffee, sitzen am See und überlegen, was sie am Abend machen können. Schließlich kochen sie gemeinsam. Als {name} spät nach Hause kommt, zeigt die Uhr kurz vor Mitternacht. Der Tag war ungeplant, aber schön und voller kleiner Gespräche.`,
  ],
  [
    `{name} möchte heute nicht nur schnell essen, sondern das Gericht selbst vorbereiten. Auf dem Küchentisch liegen Gemüse, Brot, Käse und frische Kräuter. Zuerst wird alles gewaschen und geschnitten. Dann kommt etwas Öl in die Pfanne. Ein Freund liest das Rezept vor und {name} arbeitet Schritt für Schritt. Einmal fehlt Salz, ein anderes Mal ist der Herd zu heiß. Trotzdem riecht die Küche bald wunderbar. Während das Essen kocht, decken beide den Tisch und sprechen über ihre Lieblingsgerichte. Der Freund isst kein Fleisch, deshalb gibt es eine vegetarische Mahlzeit. Am Ende probieren sie gemeinsam. Es schmeckt besser als erwartet, und für morgen bleibt sogar eine kleine Portion übrig.`,
    `Am Samstag geht {name} früh auf den Markt. Vor den Ständen liegen rote Äpfel, gelbe Birnen, Kartoffeln, Tomaten und viele andere Lebensmittel. {name} fragt nach Preisen und kauft genau die Menge auf der Liste. Bei einem Stand darf {name} eine Erdbeere probieren. Sie ist süß, also kommt auch eine Schale in den Korb. Danach geht es zur Bäckerei. Dort duftet es nach warmem Brot. Die Verkäuferin empfiehlt ein dunkles Brot und erklärt die Zutaten. {name} hört aufmerksam zu und bestellt außerdem zwei Brötchen. Zu Hause werden alle Einkäufe sortiert. Kalte Produkte kommen in den Kühlschrank, Obst bleibt in einer Schüssel auf dem Tisch.`,
    `Am Abend kommen drei Freunde zum Essen. {name} fragt vorher, was alle gern mögen und ob jemand etwas nicht essen kann. Eine Person mag keine Zwiebeln, eine andere trinkt keinen Kaffee. Deshalb gibt es mehrere kleine Speisen und Wasser mit Zitrone. Beim Essen reichen sie Schüsseln weiter und sagen höflich: „Möchtest du noch etwas?“ oder „Kannst du mir bitte das Brot geben?“ Danach bewertet jeder das beste Gericht. Die Suppe gewinnt, aber auch der Salat ist fast leer. Gemeinsam räumen sie den Tisch ab. {name} schreibt später die neuen Wörter aus dem Rezept in ein Heft und erinnert sich dabei an jedes Gespräch.`,
  ],
  [
    `{name} geht mit einer klaren Einkaufsliste in die Stadt. Zuerst wird ein Geschenk gesucht, danach Kleidung für den Winter. Im ersten Laden ist die Auswahl groß, aber die Preise sind zu hoch. {name} fragt eine Verkäuferin nach einem günstigeren Modell. Sie zeigt eine andere Farbe und erklärt, dass es heute zwanzig Prozent Rabatt gibt. In der Umkleidekabine probiert {name} zwei Größen an. Eine ist zu eng, die andere passt gut. An der Kasse wird mit Karte bezahlt und der Kassenbon sicher in die Tasche gelegt. Vor dem Geschäft prüft {name} die Liste. Das Geschenk fehlt noch, also geht die Suche weiter.`,
    `Auf dem Flohmarkt entdeckt {name} viele alte und besondere Dinge. Zwischen Büchern, Tassen und Bildern steht eine kleine blaue Lampe. Der Verkäufer möchte fünfundzwanzig Euro, aber {name} hat nur zwanzig dabei. Beide sprechen freundlich über den Preis und einigen sich schließlich auf achtzehn Euro. Der Verkäufer packt die Lampe vorsichtig in Papier. Am nächsten Stand findet {name} ein fast neues Wörterbuch und eine warme Jacke. Vor dem Kauf werden alle Seiten und Taschen geprüft. Zu Hause zeigt {name} die Sachen einem Freund. Er findet den Einkauf gut, fragt aber lachend: „Wo willst du jetzt noch eine Lampe hinstellen?“`,
    `Ein Paket bringt {name} zuerst große Freude und dann ein kleines Problem. Das bestellte Produkt sieht anders aus als auf dem Foto und hat außerdem die falsche Größe. {name} liest die Rechnung und die Information zur Rückgabe. Am nächsten Morgen geht es mit Paket und Kassenbon zur Post. Die Mitarbeiterin wiegt den Karton, druckt ein Etikett und erklärt den weiteren Weg. {name} stellt einige Fragen, damit nichts falsch läuft. Danach wird im Geschäft ein passender Ersatz gesucht. Dieses Mal prüft {name} Farbe, Größe und Preis ganz genau. Am Ende kostet das neue Produkt etwas weniger, und der Unterschied kommt zurück auf die Karte.`,
  ],
  [
    `{name} hat heute mehrere Wege in der Stadt. Zuerst muss ein Brief zur Post, dann ein Buch zurück in die Bibliothek, und zuletzt fehlt noch etwas aus der Apotheke. Auf dem Stadtplan markiert {name} alle Orte. Der kürzeste Weg führt über den Marktplatz und durch einen kleinen Park. An einer Kreuzung ist die Straße gesperrt. {name} fragt einen Polizisten nach einer anderen Route. Er erklärt: „Gehen Sie bis zur Kirche, dort rechts und dann an der Bank vorbei.“ {name} wiederholt die Richtung, damit alles richtig ist. Nach einer Stunde sind alle Aufgaben erledigt, und sogar Zeit für einen Kaffee bleibt.`,
    `Eine Freundin besucht die Stadt zum ersten Mal. {name} wartet am Bahnhof und zeigt ihr die wichtigsten Orte. Gemeinsam nehmen sie die Straßenbahn bis zum Zentrum. Dort sehen sie das Rathaus, die alte Kirche und einen großen Platz mit vielen Cafés. Die Freundin möchte ein Museum besuchen, aber zuerst braucht sie Geld. {name} erklärt den Weg zum nächsten Automaten. Später verlieren sie kurz die Orientierung. Sie schauen auf den Plan und fragen einen Mann an der Haltestelle. Seine Erklärung ist langsam und deutlich. Am Nachmittag können beide den Weg schon ohne Karte finden. Sie merken: Eine Stadt wird schnell vertraut, wenn man zu Fuß geht und Fragen stellt.`,
    `Am Abend fährt {name} mit öffentlichen Verkehrsmitteln nach Hause. Auf der Anzeige steht eine Verspätung von fünfzehn Minuten. Viele Menschen warten und lesen die neuen Informationen. Plötzlich wechselt das Gleis. {name} hört die Durchsage nicht ganz und fragt eine andere Person: „Fährt der Zug jetzt von Gleis vier?“ Die Person bestätigt es und zeigt zur Treppe. Beide gehen schnell hinüber. Im Zug sitzen sie zufällig nebeneinander und sprechen über ihren Tag. {name} erzählt von Post, Bibliothek und Markt. Als der Zug ankommt, kennt {name} nicht nur den richtigen Weg, sondern auch einen neuen freundlichen Menschen aus der Nachbarschaft.`,
  ],
  [
    `{name} bekommt am Morgen eine neue Aufgabe. Zuerst erklärt die Kollegin jeden Schritt langsam. {name} hört zu, macht kurze Notizen und fragt bei einem schwierigen Wort noch einmal nach. Danach beginnt die Arbeit. Eine Datei muss geöffnet, ein Formular ausgefüllt und eine Nachricht geschrieben werden. Fast alles klappt. Nur der Drucker zeigt plötzlich eine rote Lampe. {name} bleibt ruhig und bittet um Hilfe. Gemeinsam finden beide das Problem. In der Pause sprechen die Kollegen über ihre Aufgaben und Termine. {name} kann schon erklären, was heute fertig ist und was morgen noch gemacht werden muss. Das gibt Sicherheit für den nächsten Arbeitstag.`,
    `Im Sprachkurs arbeitet {name} heute mit einer Partnerin. Beide lesen zuerst einen längeren Text und markieren unbekannte Wörter. Dann vergleichen sie ihre Ideen. Einige Bedeutungen verstehen sie aus dem Satz, andere finden sie im Wörterbuch. Die Lehrerin gibt anschließend eine praktische Aufgabe: Sie sollen eine kurze E-Mail schreiben, um einen Termin zu verschieben. {name} achtet auf Anrede, Grund und Gruß. Die Partnerin prüft den Text und entdeckt zwei kleine Fehler. Nach der Verbesserung liest {name} die Nachricht laut vor. Sie klingt höflich und klar. Am Ende des Kurses kann jeder die Aufgabe ohne Muster noch einmal selbst schreiben.`,
    `Heute muss {name} mehrere Menschen um etwas bitten. Ein Kunde braucht Information, eine Kollegin sucht ein Dokument, und der Chef möchte bis Mittag eine Antwort. {name} ordnet zuerst die Aufgaben nach Zeit. Dann folgen kurze, freundliche Gespräche: „Können Sie bitte warten?“, „Kannst du mir helfen?“ und „Ich schicke die Datei gleich.“ Nicht jede Antwort kommt sofort. Deshalb notiert {name}, wer später zurückrufen will. Kurz vor Feierabend ist fast alles erledigt. {name} räumt den Arbeitsplatz auf und schreibt eine Liste für morgen. Der Tag war anstrengend, aber {name} hat viele echte Sätze benutzt und jede Situation selbst gelöst.`,
  ],
  [
    `{name} möchte nach einer vollen Woche etwas für Körper und Kopf tun. Am Morgen wird das Wetter geprüft: Es ist kühl, aber trocken. Deshalb zieht {name} eine warme Jacke an und geht in den Park. Dort laufen Menschen, fahren Fahrrad oder spielen mit ihren Kindern. {name} beginnt langsam und macht nach zwanzig Minuten eine Pause am See. Ein Freund kommt vorbei und schlägt ein gemeinsames Spiel vor. Später trinken beide Wasser und sprechen über Sportarten, die sie gern oder nicht gern machen. {name} merkt, dass Bewegung mit Gesellschaft leichter ist. Am Abend ist der Körper müde, aber der Kopf fühlt sich ruhig und frei an.`,
    `Draußen regnet es den ganzen Nachmittag. {name} ändert deshalb den Plan und bleibt zu Hause. Zuerst wird Musik gehört, dann liest {name} einige Seiten in einem leichten deutschen Buch. Neue Wörter werden markiert, aber nicht jedes Wort muss sofort gesucht werden. Viele Bedeutungen werden durch die Geschichte klar. Später ruft eine Freundin an und schlägt einen Filmabend vor. Sie bringt Popcorn mit, {name} macht Tee. Vor dem Film beschreiben beide das Wetter und erzählen von der Woche. Der Abend ist anders als geplant, aber nicht langweilig. Bevor die Freundin geht, verabreden sie sich für einen Spaziergang, sobald wieder die Sonne scheint.`,
    `Seit dem Morgen fühlt sich {name} nicht ganz gut. Der Kopf tut weh, der Hals ist trocken und die Arbeit fällt schwer. {name} trinkt viel Wasser und misst die Temperatur. Weil es nicht besser wird, folgt ein Anruf beim Arzt. Die Mitarbeiterin fragt nach den Beschwerden und bietet einen Termin am Nachmittag an. Im Wartezimmer sitzt {name} mit Abstand zu den anderen Personen. Der Arzt hört aufmerksam zu und empfiehlt Ruhe, warme Suppe und zwei Tage zu Hause. Auf dem Rückweg holt {name} alles Nötige aus der Apotheke. Am Abend geht es schon etwas besser, und eine Freundin bringt ein Buch vorbei.`,
  ],
  [
    `{name} bereitet die Reise mehrere Tage vorher vor. Auf dem Bett liegen Kleidung, Schuhe, ein Buch und wichtige Dokumente. Nicht alles passt in den Koffer, deshalb muss {name} auswählen. Die Fahrkarte und der Ausweis kommen in eine kleine Tasche, die immer erreichbar bleibt. Danach wird die Verbindung geprüft: Abfahrt, Gleis, Umstieg und Ankunft. {name} schreibt die wichtigsten Informationen auf Papier, falls das Handy keinen Strom mehr hat. Am Reisetag geht {name} früh zum Bahnhof. Dort zeigt die Anzeige eine kleine Verspätung. Das ist kein Problem, denn genug Zeit ist eingeplant. Mit Kaffee und Koffer beginnt schließlich die Fahrt.`,
    `Im Hotel begrüßt {name} die Person an der Rezeption und nennt den reservierten Namen. Für die Anmeldung werden Ausweis und Adresse gebraucht. Die Rezeptionistin erklärt Frühstückszeit, Internet und den Weg zum Zimmer. {name} hört genau zu und fragt wegen eines ruhigen Zimmers noch einmal nach. Oben funktioniert die Zimmerkarte zuerst nicht. Ein Mitarbeiter kommt mit und hilft. Danach stellt {name} den Koffer ab, öffnet das Fenster und schaut auf die fremde Stadt. Auf dem Tisch liegt ein Plan. {name} markiert ein Museum, einen Park und ein Restaurant. So entsteht ein einfacher Plan für den ersten Urlaubstag.`,
    `Am letzten Reisetag denkt {name} an viele kleine Erlebnisse zurück. Es gab eine verspätete Bahn, einen schweren Koffer und einmal den falschen Weg. Es gab aber auch freundliche Menschen, gutes Essen und interessante Gespräche. {name} kauft Postkarten und ein kleines Geschenk für die Familie. Im Café schreibt {name} einige Sätze über Wetter, Unterkunft und Ausflüge. Danach geht es zum Bahnhof. Dieses Mal findet {name} das Gleis sofort und versteht die Durchsage. Im Zug wird noch einmal im deutschen Buch gelesen. Viele Wörter wirken jetzt bekannt. Die Reise war nicht immer einfach, aber {name} konnte jede wichtige Situation mit einfachem Deutsch bewältigen.`,
  ],
];

const STORY_ENDINGS = [
  `{name} schreibt am Abend fünf neue Wörter mit Beispielsätzen auf. Danach erzählt {name} die Geschichte noch einmal laut, zuerst mit dem Text und dann ohne ihn. Einige Details fehlen, aber Anfang, Problem und Ende sind klar. Genau das ist heute der wichtigste Erfolg.`,
  `Bevor der Tag endet, sendet {name} einem Freund eine kurze Nachricht darüber. Der Freund antwortet mit zwei Fragen. {name} liest sie langsam, versteht beide und schreibt ganze Sätze zurück. Aus einer kleinen Alltagssituation ist so eine echte Sprachübung geworden.`,
  `{name} denkt noch einmal an das Gespräch. Welche Frage war wichtig, welche Antwort hat geholfen, und welches Wort war neu? Im Heft entsteht eine kleine Zusammenfassung. Am nächsten Morgen liest {name} sie beim Frühstück laut und versteht den Ablauf sofort wieder.`,
  `Zu Hause erzählt {name} alles in der richtigen Reihenfolge: zuerst, dann, danach und am Ende. Diese Wörter verbinden die einzelnen Momente. Die Geschichte klingt dadurch nicht mehr wie eine Liste, sondern wie ein zusammenhängendes Erlebnis mit einem klaren Ergebnis.`,
  `Später übt {name} die wichtigsten Sätze vor dem Spiegel. Beim zweiten Versuch wird die Stimme sicherer, beim dritten kommt die Antwort ohne lange Pause. {name} merkt: Die Wörter bleiben besser im Kopf, wenn sie zu einer Situation und zu einem Gefühl gehören.`,
  `{name} markiert im Text bekannte Wörter grün und neue Wörter orange. Die grüne Gruppe ist größer als erwartet. Von den neuen Wörtern wählt {name} nur sechs für heute. Mit jedem Wort entsteht ein eigener kurzer Satz aus dem Alltag.`,
  `Am nächsten Tag begegnet {name} einer ähnlichen Situation. Dieses Mal kommen die passenden Wörter schneller. Nicht jeder Satz ist perfekt, doch die andere Person versteht alles. {name} fragt nach, antwortet ruhig und beendet das Gespräch mit einem Lächeln.`,
  `Für den Kurs nimmt {name} eine kleine Sprachnachricht auf. Darin dauert die Erzählung fast zwei Minuten. Nach dem ersten Hören verbessert {name} drei Stellen und nimmt sie noch einmal auf. Die zweite Version ist klarer und natürlicher.`,
  `{name} stellt sich danach drei einfache Fragen zum Text: Wer war dabei? Was ist passiert? Warum war das wichtig? Die Antworten werden etwas länger als früher. So wächst aus kurzen A1-Sätzen Schritt für Schritt eine flüssige Erzählung.`,
  `Zum Schluss liest {name} die ganze Geschichte noch einmal langsam. Jetzt sind die Verbindungen zwischen den Sätzen deutlich. Bekannte Wörter geben Sicherheit, neue Wörter bringen mehr Details. {name} schließt das Heft und freut sich schon auf die nächste Geschichte.`,
];

const LEARNING_BRIDGES = [
  `Währenddessen achtet {name} auf kleine Verbindungswörter. Mit und, aber, dann und deshalb wird klar, wie eine Handlung zur nächsten führt.`,
  `Im Gespräch hört {name} einige Wörter mehrmals. Durch diese Wiederholung werden sie vertraut, und der Sinn des ganzen Satzes wird schneller verständlich.`,
  `{name} versucht nicht, jeden Satz sofort zu übersetzen. Zuerst helfen Situation und bekannte Wörter, danach werden nur die wirklich wichtigen Lücken geprüft.`,
  `Ein kurzer Dialog bringt neue Bewegung in den Tag. Frage und Antwort passen zusammen, und {name} kann dem Gespräch ohne lange Pause folgen.`,
  `Dabei verändert sich auch die Stimmung. Erst ist {name} unsicher, später neugierig und am Ende zufrieden, weil die Aufgabe mit Deutsch gelingt.`,
  `{name} bemerkt, dass dieselben Wörter in verschiedenen Sätzen anders wirken. Der Zusammenhang zeigt, welche Bedeutung in diesem Moment am besten passt.`,
  `Ein kleines Problem macht die Geschichte interessanter. {name} sucht eine Lösung, bittet um Hilfe und versteht die Antwort durch den gemeinsamen Zusammenhang.`,
  `Zwischendurch wiederholt {name} einen wichtigen Satz leise. Beim nächsten Mal kommt die gleiche Struktur schon leichter und klingt ein wenig natürlicher.`,
  `Die einzelnen Ereignisse bilden jetzt eine klare Kette. {name} kann erklären, was vorher war, was gerade passiert und was danach kommen soll.`,
  `So bleibt nicht nur eine Liste von Wörtern im Kopf. {name} erinnert sich an Menschen, Orte, Gefühle und an den Weg durch die ganze Situation.`,
];

const KNOWN_LEADS = [
  "Mia", "Leo", "Eva", "Nora", "Ben", "Lina", "Omar", "Ana", "Ken", "Max", "Sofia", "Klara", "David", "Rania", "Mara", "Ella", "Bruno", "Nina", "Tim", "Emma", "Laura", "Jan", "Mila", "Anna", "Paula", "Ela", "Can", "Emil", "Ida", "Tom", "Leni", "Karim", "Julia", "Paul", "Mina", "Alex", "Nila", "Tarek", "Ravi", "Sara", "Elif", "Lea", "Jonas", "Luis", "Ava", "Lena", "Tara", "Niko",
];

function storyLead(text: string) {
  return KNOWN_LEADS.find((name) => text.includes(name)) ?? "Die Hauptperson";
}

function longStoryText(base: string, unitIndex: number, storyIndex: number) {
  const name = storyLead(base);
  const middle = UNIT_FLOW[unitIndex][storyIndex % UNIT_FLOW[unitIndex].length];
  const bridge = LEARNING_BRIDGES[storyIndex];
  const ending = STORY_ENDINGS[storyIndex];
  return [base, middle, bridge, ending].map((part) => part.replaceAll("{name}", name)).join("\n\n");
}

let storyNumber = 0;

export const A1_UNITS: A1Unit[] = UNIT_SEEDS.map((unit, unitIndex) => ({
  id: unitIndex + 1,
  title: unit.title,
  shortTitle: unit.shortTitle,
  description: unit.description,
  grammar: unit.grammar,
  canDo: unit.canDo,
  color: unit.color,
  stories: unit.stories.map(([title, text], storyIndex) => {
    storyNumber += 1;
    return {
      id: `a1-${String(storyNumber).padStart(3, "0")}`,
      number: storyNumber,
      unitId: unitIndex + 1,
      title,
      text: longStoryText(text, unitIndex, storyIndex),
      grammar: unit.grammar,
      canDo: unit.canDo,
      theme: unit.shortTitle,
      color: unit.color,
    };
  }),
}));

export const A1_STORIES = A1_UNITS.flatMap((unit) => unit.stories);

export const GLOSSARY: Record<string, string> = {
  aber: "but", abend: "evening", acht: "eight", adresse: "address", alle: "all / everyone",
  als: "as / than", alt: "old", am: "on the / at the", an: "at / on", andere: "other",
  antwortet: "answers", antworten: "to answer", april: "April", arbeit: "work",
  arbeitet: "works", arbeiten: "to work", arzt: "doctor", auch: "also", auf: "on / onto",
  aufstehen: "to get up", aufsteht: "gets up", aus: "from / out of", ausweis: "ID card",
  automat: "machine", bahnhof: "station", balkon: "balcony", bald: "soon", bank: "bank",
  bar: "cash", bäckerei: "bakery", bäcker: "baker", bad: "bathroom", beantworten: "to answer",
  bekommt: "gets / receives", ben: "Ben", berlin: "Berlin", beruf: "profession", besser: "better",
  bett: "bed", bezahlen: "to pay", bezahlt: "pays", beide: "both", beim: "at the / with the",
  bleiben: "to stay", bleibt: "stays", blau: "blue", blaue: "blue", blonde: "blonde",
  bonn: "Bonn", braun: "brown", brief: "letter", briefkasten: "mailbox", briefmarke: "stamp",
  brille: "glasses", bringt: "brings", brot: "bread", brötchen: "bread roll", bruder: "brother",
  brüder: "brothers", buch: "book", bücher: "books", büro: "office", bus: "bus",
  café: "café", chef: "boss", computer: "computer", da: "there", dabei: "with them",
  danach: "after that", danke: "thank you", dankt: "thanks", das: "the / that", dein: "your",
  deine: "your", dem: "the", den: "the", denn: "because", der: "the", deshalb: "therefore",
  deutsch: "German", die: "the", dich: "you", direkt: "directly", drei: "three", dritten: "third",
  durch: "through", durchsage: "announcement", dunkel: "dark", du: "you", ein: "a / one",
  eine: "a / one", einem: "a / one", einen: "a / one", einer: "a / one", einkaufen: "to shop",
  einladung: "invitation", einsteigen: "to get on", einfach: "simple / one-way", einfache: "simple / one-way",
  eier: "eggs", eis: "ice / ice cream", elf: "eleven", eltern: "parents", englisch: "English",
  er: "he", erste: "first", ersten: "first", es: "it / there", essen: "to eat / food",
  euro: "euro", fährt: "travels / drives", fahrer: "driver", fahrkarte: "ticket", familie: "family",
  fast: "almost", fehlt: "is missing", fenster: "window", ferienhaus: "holiday house",
  fertig: "finished / ready", fest: "party / festival", fieber: "fever", film: "film", findet: "finds",
  flasche: "bottle", fleisch: "meat", flohmarkt: "flea market", form: "form", formulare: "forms",
  foto: "photo", frei: "free", freitag: "Friday", freund: "male friend", freunde: "friends",
  freundin: "female friend", freundlich: "friendly", freut: "is happy", früh: "early",
  früher: "earlier", frühstück: "breakfast", für: "for", fünf: "five", funktioniert: "works",
  geht: "goes / is", gelb: "yellow", geld: "money", geldautomat: "cash machine", gemütlich: "cosy",
  gemüse: "vegetables", genau: "exactly", gerade: "just / straight", geradeaus: "straight ahead",
  gern: "gladly / like to", geschäft: "shop", geschäfte: "shops", geschichte: "story",
  geschichten: "stories", geschlossen: "closed", geschenk: "gift", gestern: "yesterday",
  getränke: "drinks", gewinnt: "wins", gibt: "gives / there is", gitarre: "guitar", glas: "glass",
  gleich: "right away", gleis: "track / platform", glücklich: "happy", grad: "degrees",
  grau: "grey", groß: "big / tall", große: "big", grüße: "greetings", grün: "green",
  gut: "good / well", gute: "good", guten: "good", hallo: "hello", halb: "half",
  haltestelle: "stop", hamburg: "Hamburg", handy: "mobile phone", hat: "has", hatten: "had",
  haus: "house / home", hause: "home", hausaufgabe: "homework", heißen: "to be called",
  heißt: "is called", helfen: "to help", hilft: "helps", hell: "bright", hemd: "shirt",
  herd: "stove", herr: "Mr.", heute: "today", hier: "here", himmel: "sky", hin: "there",
  hinter: "behind", hört: "hears / listens", hotel: "hotel", hund: "dog", ich: "I",
  ihr: "her / their / you", ihre: "her / their", im: "in the", in: "in / into", ist: "is",
  italien: "Italy", italienisch: "Italian", ja: "yes", jacke: "jacket", japan: "Japan",
  jahre: "years", jetzt: "now", junge: "boy", kalendar: "calendar", kalt: "cold",
  kann: "can", karte: "card / map", karotten: "carrots", kasse: "checkout", kassenbon: "receipt",
  kauft: "buys", kaufen: "to buy", kaufhaus: "department store", kein: "no / not a",
  keine: "no / not any", keinen: "no / not any", kellner: "waiter", kellnerin: "waitress",
  kennt: "knows", kind: "child", kinder: "children", kindergarten: "kindergarten",
  kirche: "church", klein: "small", kleine: "small", kleinen: "small", kleiner: "smaller",
  kocht: "cooks", kochen: "to cook", kollegen: "colleagues", kollegin: "female colleague",
  kommt: "comes", kommen: "to come", konnte: "could", kopf: "head", kopfschmerzen: "headache",
  kostet: "costs", kurs: "course", kuchen: "cake", küche: "kitchen", kühlschrank: "fridge",
  kurz: "short", kurze: "short", langen: "long", lange: "long", länger: "longer",
  langsam: "slowly", laden: "shop", lampe: "lamp", lacht: "laughs", lachen: "to laugh",
  laufen: "to run / walk", lebt: "lives", leicht: "easy / light", leider: "unfortunately",
  lehrer: "teacher", lehrerin: "female teacher", lernt: "learns", lernen: "to learn",
  lesen: "to read", liest: "reads", liebe: "dear / love", lieber: "preferably", liegt: "lies / is located",
  links: "left", man: "one / you", macht: "does / makes", machen: "to do / make",
  mal: "time / times", markt: "market", marktplatz: "market square", mantel: "coat",
  meer: "sea", mein: "my", meine: "my", meinem: "my", menschen: "people", mitte: "middle",
  mit: "with", mitarbeiter: "employee", milch: "milk", minuten: "minutes", möbel: "furniture",
  morgen: "morning / tomorrow", möchte: "would like", möchten: "would like", muss: "must / has to",
  müssen: "must / have to", müde: "tired", musik: "music", museum: "museum", mutter: "mother",
  mütze: "hat", nach: "to / after", nachbarin: "female neighbor", nachmittag: "afternoon",
  nachricht: "message", name: "name", neben: "next to", nein: "no", neu: "new", neue: "new",
  neuen: "new", neunzehn: "nineteen", nicht: "not", nichts: "nothing", noch: "still / yet",
  nummer: "number", nur: "only", oben: "upstairs / above", oder: "or", öffnet: "opens",
  oma: "grandmother", orangensaft: "orange juice", papier: "paper", park: "park", passt: "fits",
  pause: "break", per: "by / via", person: "person", personen: "people", polizei: "police",
  polizist: "police officer", polen: "Poland", polnisch: "Polish", post: "post office",
  postkarte: "postcard", preis: "price", probiert: "tries", pünktlich: "on time", rechts: "right",
  regal: "shelf", regen: "rain", regenschirm: "umbrella", regnet: "it rains", reise: "journey",
  restaurant: "restaurant", richtig: "correct", rot: "red", rote: "red", ruft: "calls",
  rund: "round", sagt: "says", salat: "salad", samstag: "Saturday", samstags: "on Saturdays",
  schinken: "ham", schließt: "closes", schlüssel: "key", schnell: "quickly", schön: "beautiful",
  schöne: "beautiful", schwarz: "black", schwarze: "black", schwester: "sister", schwimmen: "to swim",
  sechs: "six", seine: "his", sein: "to be / his", seife: "soap", seiten: "pages", sehr: "very",
  seit: "since", setzt: "sits / places", sich: "oneself", sieben: "seven", sie: "she / they / you",
  sind: "are", sitzt: "sits", socke: "sock", sofa: "sofa", sofort: "immediately", sommer: "summer",
  sonne: "sun", sonntag: "Sunday", sonntags: "on Sundays", sonnig: "sunny", spanien: "Spain",
  spanisch: "Spanish", später: "later", spazieren: "to walk", spricht: "speaks", sprechen: "to speak",
  spielt: "plays", spielen: "to play", sport: "sport", stadt: "city", steht: "stands / says",
  steine: "stones", stellen: "to put / place", straße: "street", straßenbahn: "tram", stuhl: "chair",
  stühle: "chairs", student: "student", studentin: "female student", studiert: "studies",
  sucht: "searches", suppe: "soup", tag: "day", tante: "aunt", tanzen: "to dance",
  tee: "tea", telefonnummer: "phone number", termin: "appointment", termine: "appointments",
  tisch: "table", tochter: "daughter", tomaten: "tomatoes", tor: "goal", tourist: "tourist",
  tragen: "to carry / wear", trägt: "carries / wears", treffen: "to meet", treppenhaus: "stairwell",
  trinken: "to drink", trinkt: "drinks", trocken: "dry", tschüss: "bye", tür: "door",
  uhr: "o'clock / clock", um: "at / around", umschlag: "envelope", und: "and", universität: "university",
  unser: "our", unsere: "our", unter: "under", unterschreiben: "to sign", unterwegs: "on the way",
  überrascht: "surprised", vater: "father", Verkäufer: "salesperson", verkäuferin: "saleswoman",
  verschiedene: "different", versteht: "understands", verstehen: "to understand", verspätung: "delay",
  vier: "four", viele: "many", von: "from / of", vor: "before / in front of", vorbei: "past",
  wartet: "waits", warten: "to wait", warm: "warm", war: "was", warum: "why", wasser: "water",
  weiß: "white / knows", welche: "which", wenn: "if / when", wer: "who", wie: "how / like",
  wieder: "again", wien: "Vienna", will: "wants", wind: "wind", winter: "winter", wir: "we",
  wo: "where", woche: "week", wochenende: "weekend", woher: "where from", wohnen: "to live",
  wohnt: "lives", wohnung: "apartment", wohnzimmer: "living room", wollen: "want", wort: "word",
  wörter: "words", wörterbuch: "dictionary", zehn: "ten", zeit: "time", zettel: "note",
  zwanzig: "twenty", zwei: "two", zweiten: "second", zur: "to the", zurück: "back", zusammen: "together",
  achtzehn: "eighteen", achtzig: "eighty", allen: "everyone / all", alles: "everything",
  also: "so / therefore", alte: "old", alten: "old", angefangen: "started", backt: "bakes",
  bedankt: "thanks", beginnt: "begins", bei: "at / with", beiden: "both", bekanntes: "well-known",
  bekommen: "to receive", benutzen: "to use", bestellen: "to order", bestellt: "orders",
  besuche: "visit", bewegt: "moves", bin: "am", bis: "until", bisschen: "a little",
  bist: "are", bitte: "please", bittet: "asks", braucht: "needs", dann: "then", darf: "may / is allowed",
  deckt: "sets / covers", denselben: "the same", deutsches: "German", dort: "there", draußen: "outside",
  dreiundzwanzig: "twenty-three", dreißig: "thirty", drucken: "to print", dunkle: "dark",
  eigenen: "own", eines: "of a / one", einfachen: "simple", einmal: "once", empfiehlt: "recommends",
  entschuldigung: "excuse me", erklärt: "explains", erreicht: "reaches", erzählen: "to tell",
  esse: "eat", etwas: "something", fahre: "travel / drive", folgt: "follows", fragt: "asks",
  frau: "Ms. / woman", froh: "glad", frühstückt: "eats breakfast", fängt: "starts",
  fünfzehn: "fifteen", gegenüber: "opposite", gehen: "to go", gekauft: "bought", gelben: "yellow",
  gesucht: "wanted / searched for", gratis: "free", großen: "large", großes: "large", größer: "bigger / taller",
  grüne: "green", grünes: "green", grüßt: "greets", haben: "to have", hast: "have", hatte: "had",
  heiß: "hot", heiße: "am called", heraus: "out", hilfe: "help", hinein: "inside", hundert: "hundred",
  hält: "stops / holds", hängen: "hang", hören: "to hear / listen", ihm: "him", ihnen: "them / you",
  ihrem: "her / their", ihren: "her / their", immer: "always", ins: "into the", isst: "eats",
  jeden: "every", jedes: "every", kannst: "can", kim: "Kim", klatschen: "to clap", kleines: "small",
  klingelt: "rings", koche: "cook", komme: "come", kommst: "come", kosten: "to cost", krank: "ill",
  kurzen: "short", können: "can / to be able", kühl: "cool", langweilig: "boring", laut: "aloud / loud",
  leben: "to live", leichtes: "easy", leiht: "borrows", leo: "Leo", letzter: "last", lieb: "dear / kind",
  lieben: "to love", los: "off / going", lustig: "funny", lächelt: "smiles", lädt: "invites",
  längere: "longer", läuft: "runs", mag: "likes", malen: "to paint", markiert: "marks",
  meisten: "most", merkt: "notices", mieten: "to rent", minus: "minus", mir: "me", mitspielen: "to join the game",
  mögen: "to like", nebenan: "next door", nehmen: "to take", nett: "nice", neun: "nine", nimmt: "takes",
  nächsten: "next", offen: "open", oft: "often", ohne: "without", plant: "plans", reserviert: "reserved",
  roten: "red", ruhig: "quiet", räumt: "tidies", sagen: "to say", sammeln: "to collect", schaut: "looks",
  scheint: "shines", schickt: "sends", schlafen: "to sleep", schläft: "sleeps", schneidet: "cuts",
  schon: "already", schreiben: "to write", schreibt: "writes", schwer: "heavy / difficult", schönen: "beautiful",
  sechzehn: "sixteen", sehen: "to see", seinem: "his", seinen: "his", seiner: "his", setzen: "to sit / set",
  siebzehn: "seventeen", siebzig: "seventy", sieht: "sees", singt: "sings", sitzen: "to sit", so: "so / like this",
  spät: "late", stark: "strong / heavily", steckt: "inserts", stehen: "to stand", steigt: "gets on",
  stellt: "puts / places", süß: "sweet", tanzt: "dances", teuer: "expensive", toll: "great", trifft: "meets",
  trotzdem: "nevertheless", tut: "does / hurts", viel: "much / a lot", vielen: "many", vierfünfacht: "four-five-eight",
  vierundzwanzig: "twenty-four", vierzehn: "fourteen", vierzig: "forty", vom: "from the", vorne: "ahead / in front",
  wandern: "to hike", wann: "when", warme: "warm", warte: "wait", was: "what", weh: "sore / painful",
  weiße: "white", wenig: "little", wird: "becomes", wirft: "throws / puts", wohne: "live", wählen: "to choose",
  wählt: "chooses", während: "while", zeigt: "shows", zieht: "moves / pulls", zu: "to / too / closed",
  zum: "to the / for the", zweites: "second", zwölf: "twelve", älter: "older", öffnen: "to open", über: "about / over",
};

Object.assign(GLOSSARY, {
  ab: "from / off", abfahrt: "departure", ablauf: "sequence / course", abstand: "distance",
  achten: "to pay attention", aktivitäten: "activities", alltag: "everyday life",
  alltagssituation: "everyday situation", alter: "age", ändert: "changes", anfang: "beginning",
  ankommen: "to arrive", ankunft: "arrival", anmeldung: "registration", anrede: "salutation",
  anruf: "phone call", anrufen: "to call", anschließend: "afterwards", anstrengend: "tiring",
  antwort: "answer", anzeige: "display / notice", apotheke: "pharmacy", arbeitsplatz: "workplace",
  arbeitstag: "working day", aufgabe: "task", aufgeräumt: "tidied", aufräumen: "to tidy up",
  aufmerksamkeit: "attention", aufmerksam: "attentive", augen: "eyes", ausdrücke: "expressions",
  ausflüge: "excursions", ausgefüllt: "filled out", außerdem: "in addition", auswahl: "selection",
  auswählen: "to choose", bahn: "train / railway", bedeutung: "meaning", bedeutungen: "meanings",
  beendet: "finishes / ended", begegnet: "encounters", begrüßen: "to greet", begrüßt: "greets",
  beispielsatz: "example sentence", beispielsätzen: "example sentences", bekannt: "known / familiar",
  benutzt: "uses", bereit: "ready", bereiten: "to prepare", beschreiben: "to describe",
  beschwerden: "symptoms / complaints", besondere: "special", bestätigt: "confirms", beste: "best",
  bestellt: "ordered", besuch: "visit", besuchen: "to visit", bevor: "before", bewältigen: "to manage",
  bewegung: "movement / exercise", bewertet: "rates / evaluates", beziehung: "relationship",
  bibliothek: "library", bietet: "offers", bild: "picture", bilder: "pictures", birne: "pear",
  birnen: "pears", bitten: "to ask / request", blatt: "sheet / leaf", blumen: "flowers",
  böse: "angry", brauchen: "to need", breit: "wide", bringen: "to bring", büchern: "books",
  bunte: "colorful", charakter: "character / personality", cousinen: "female cousins",
  dadurch: "through that", damit: "so that / with it", daraus: "from it", darüber: "about it",
  dass: "that", datei: "file", dauert: "lasts", decken: "to set / cover", denken: "to think",
  details: "details", deutlich: "clear / clearly", dienstags: "on Tuesdays", dinge: "things",
  doch: "however / after all", dokument: "document", dokumente: "documents", donnerstags: "on Thursdays",
  drucker: "printer", druckt: "prints", duftet: "smells fragrant", dunkles: "dark",
  echte: "real / genuine", eigener: "own", einfachem: "simple", einfacher: "simpler",
  eingeplant: "planned in", einige: "some", einkauf: "shopping / purchase", einkäufe: "purchases",
  eins: "one", einzelnen: "individual", eng: "tight / narrow", entdeckt: "discovers",
  entsteht: "is created", erfolg: "success", ergänzt: "adds / completes", ergebnis: "result",
  erinnert: "remembers", erklärung: "explanation", erlebnis: "experience", erlebnisse: "experiences",
  erledigt: "completed", erreichbar: "reachable", ersatz: "replacement", erwartet: "expects",
  erzählung: "narrative", etikett: "label", fahren: "to travel / drive", falls: "in case",
  fällt: "falls / is difficult", falsch: "wrong", familienfoto: "family photo", farbe: "color",
  farben: "colors", fehler: "mistake", feierabend: "end of the working day", fertigen: "finished",
  filmabend: "movie night", finden: "to find", flur: "hallway", flüssig: "fluent / flowing",
  folgen: "to follow", formular: "form", freie: "free", freitags: "on Fridays", freizeit: "free time",
  fremde: "foreign / unfamiliar", freude: "joy", freundliche: "friendly", frische: "fresh",
  friseur: "hairdresser", frühstückszeit: "breakfast time", fühlt: "feels", führt: "leads",
  fünfundzwanzig: "twenty-five", fuß: "foot", fußball: "football / soccer", gab: "there was / gave",
  ganz: "whole / quite", ganze: "whole", garten: "garden", gäste: "guests", geben: "to give",
  gebraucht: "needed / used", geburtstag: "birthday", geduldig: "patiently", gefühl: "feeling",
  gegenstand: "object", geholfen: "helped", gehören: "to belong", gehört: "belongs / heard",
  gelegt: "laid / put", gelesen: "read", gelingt: "succeeds", gelöst: "solved", gemacht: "done / made",
  gemeinsam: "together", gemeinsame: "shared", gesellschaft: "company / society", gesicht: "face",
  gesperrt: "closed / blocked", gespräch: "conversation", gespräche: "conversations",
  gewaschen: "washed", geworden: "become", gläser: "glasses", glück: "luck", großeltern: "grandparents",
  größen: "sizes", grund: "reason", gruppe: "group", gruppenfoto: "group photo", gruß: "greeting",
  günstig: "inexpensive", haare: "hair", hals: "throat / neck", hand: "hand", hauptperson: "main character",
  haustür: "front door", heft: "notebook", heimweg: "way home", hinstellen: "to put / place",
  hinüber: "across / over", hobbys: "hobbies", höflich: "polite", holt: "gets / fetches",
  holztisch: "wooden table", ideen: "ideas", information: "information", informationen: "information",
  interessante: "interesting", internet: "internet", jede: "each / every", jedem: "each / everyone",
  jeder: "everyone / each", jemand: "someone", kalte: "cold", kamera: "camera", karten: "cards",
  karton: "cardboard box", kauf: "purchase", kissen: "cushions", klappt: "works out", klar: "clear",
  kleidung: "clothing", klingt: "sounds", kommode: "chest of drawers", konzert: "concert",
  korb: "basket", körper: "body", kreuzung: "intersection", kunde: "customer", kunden: "customers",
  kurses: "of the course", kürzeste: "shortest", land: "country", länder: "countries",
  lebensmittel: "groceries / food", leer: "empty", legen: "to lay / put", leichter: "easier",
  leise: "quietly", letzten: "last", lieblingsgericht: "favorite dish", liste: "list",
  mahlzeit: "meal", manchmal: "sometimes", markieren: "to mark", mehr: "more", mehrere: "several",
  menge: "amount", merken: "to notice / remember", misst: "measures", mittag: "midday",
  modell: "model", momente: "moments", möchtest: "would like", muster: "template / example",
  nachbarschaft: "neighborhood", nachbartisch: "next table", nächste: "next", namen: "names",
  natürlich: "of course / naturally", natürlicher: "more natural", nebeneinander: "next to each other",
  nennen: "to name", nennt: "names", neuigkeiten: "news", niemand: "nobody", notiert: "notes down",
  nötige: "necessary things", notizen: "notes", ob: "whether / if", öffentlich: "public",
  öl: "oil", orange: "orange", ordnet: "organizes", orientierung: "orientation", ort: "place",
  orte: "places", ortsangaben: "location phrases", packt: "packs", paket: "parcel",
  partner: "partner", partnerin: "female partner", passende: "suitable", passiert: "happens",
  perfekt: "perfect", pfanne: "pan", pflanzen: "plants", plan: "plan / map", planen: "to plan",
  platz: "place / seat", plötzlich: "suddenly", polizisten: "police officer", popcorn: "popcorn",
  portion: "portion", postkarten: "postcards", praktische: "practical", preise: "prices",
  probieren: "to try / taste", problem: "problem", produkt: "product", produkte: "products",
  prozent: "percent", prüft: "checks", rabatt: "discount", rathaus: "town hall", raum: "room",
  rechnung: "bill / invoice", reihenfolge: "order / sequence", reisetag: "travel day",
  rezept: "recipe", rezeption: "reception", rezeptionistin: "receptionist", rhythmus: "rhythm",
  richtung: "direction", riecht: "smells", route: "route", rückgabe: "return", rückseite: "back side",
  rückweg: "return journey", ruhe: "rest / quiet", sachen: "things", samstagvormittag: "Saturday morning",
  satz: "sentence", sätze: "sentences", schale: "bowl / punnet", schauen: "to look",
  schlägt: "suggests / hits", schließlich: "finally", schluss: "end", schmeckt: "tastes",
  schritt: "step", schule: "school", schüssel: "bowl", schüsseln: "bowls", schwierig: "difficult",
  see: "lake", selbst: "oneself / even", sendet: "sends", sicher: "safe / certainly", sicherheit: "confidence / safety",
  situation: "situation", sobald: "as soon as", sogar: "even", sollen: "should", sondern: "but rather",
  sortiert: "sorts", spaziergang: "walk", speisen: "dishes / foods", spiegel: "mirror", spiel: "game",
  sportarten: "sports", sprache: "language", sprachen: "languages", sprachkurs: "language course",
  sprachnachricht: "voice message", sprachübung: "language exercise", sprichst: "speak",
  stadtplan: "city map", stand: "stall / stood", ständen: "stalls", stimme: "voice", strom: "electricity",
  suche: "search", suchen: "to search", tafel: "board", tagesplan: "daily schedule", tasche: "bag",
  taschen: "pockets / bags", tassen: "cups", telefon: "telephone", telefonbuch: "phone book",
  telefonnummern: "phone numbers", teller: "plates", temperatur: "temperature", teppich: "carpet",
  text: "text", texte: "texts", treppe: "stairs", tun: "to do", üben: "to practice",
  überlegen: "to consider", übrig: "left over", übt: "practices", übung: "exercise",
  uhrzeit: "time of day", umkleidekabine: "changing room", umstieg: "transfer",
  unbekannte: "unknown", ungeplant: "unplanned", unterkunft: "accommodation", unterschied: "difference",
  urlaubstag: "vacation day", vegetarische: "vegetarian", verabreden: "to arrange to meet",
  verben: "verbs", verbessert: "improves", verbesserung: "improvement", verbinden: "to connect",
  verbindung: "connection", vergessen: "to forget", vergleichen: "to compare", verkehrsmittel: "public transport",
  verlieren: "to lose", verschieben: "to postpone", version: "version", versuch: "attempt",
  versuchen: "to try", vertraut: "familiar", viertel: "quarter", vögel: "birds", voll: "full",
  voller: "full of", voneinander: "from each other", vorbereiten: "to prepare", vorderseite: "front side",
  vorher: "beforehand", vorsichtig: "carefully", wächst: "grows", wartezimmer: "waiting room",
  wäsche: "laundry", wechselt: "changes", wege: "ways / routes", wegen: "because of",
  weile: "while", weiter: "further / on", weltkarte: "world map", weniger: "less", werden: "to become / will",
  wichtig: "important", wiederholt: "repeats", wiegt: "weighs", wirken: "to seem", wirklich: "really",
  wohnorte: "places of residence", wohnungsschlüssel: "apartment key", wörtern: "words",
  wunderbar: "wonderful", zeichnet: "draws", zeitung: "newspaper", zentrum: "center",
  zimmerkarte: "room key card", zimmers: "of the room", zufällig: "by chance", zuletzt: "lastly",
  zunächst: "at first", zurückrufen: "to call back", zusammenfassung: "summary",
  zusammenhängend: "connected / coherent", zusätzliche: "additional", zutaten: "ingredients",
  zweite: "second", zwischen: "between",
  ähnlichen: "similar", anders: "different / differently", bemerkt: "notices", des: "of the",
  diese: "this / these", dieselben: "the same", diesem: "this", endet: "ends",
  erklären: "to explain", fehlen: "to be missing", fragen: "to ask / questions", genug: "enough",
  geöffnet: "opened", geplant: "planned", geprüft: "checked", geschnitten: "cut",
  geschrieben: "written", günstigeren: "less expensive", hoch: "high", ihn: "him",
  interessanter: "more interesting", lachend: "laughing", liegen: "to lie / be located",
  mehrmals: "several times", neugierig: "curious", passen: "to fit", passender: "more suitable",
  räumen: "to clear / tidy", reichen: "to pass / be enough", schicke: "send",
  soll: "should / is supposed to", übersetzen: "to translate", unsicher: "unsure",
  verändert: "changes", verspätete: "delayed", verständlich: "understandable", weg: "way / gone",
  weil: "because", wichtigste: "most important", wichtigsten: "most important",
  willst: "want", wohnst: "live", zuerst: "first / first of all", zufrieden: "satisfied",
});

export function cleanWord(token: string) {
  return token.toLocaleLowerCase("de-DE").replace(/[^a-zäöüßé]/gi, "");
}

const ALL_READING_WORDS = A1_STORIES.flatMap((story) =>
  story.text.split(/\s+/).map(cleanWord).filter(Boolean),
);

export const A1_STATS = {
  totalWords: ALL_READING_WORDS.length,
  uniqueWordForms: new Set(ALL_READING_WORDS).size,
  averageStoryWords: Math.round(ALL_READING_WORDS.length / A1_STORIES.length),
};

export function meaningFor(token: string) {
  const word = cleanWord(token);
  if (!word) return "";
  if (GLOSSARY[word]) return GLOSSARY[word];
  const candidates = [
    word.endsWith("ern") ? word.slice(0, -3) : "",
    word.endsWith("en") ? word.slice(0, -2) : "",
    word.endsWith("er") ? word.slice(0, -2) : "",
    word.endsWith("es") || word.endsWith("em") ? word.slice(0, -2) : "",
    word.endsWith("e") || word.endsWith("n") || word.endsWith("s") ? word.slice(0, -1) : "",
    word.endsWith("et") ? `${word.slice(0, -2)}en` : "",
    word.endsWith("t") ? `${word.slice(0, -1)}en` : "",
  ];
  for (const candidate of candidates) {
    if (candidate && GLOSSARY[candidate]) return GLOSSARY[candidate];
  }
  if (/^[A-ZÄÖÜ]/.test(token)) return "name / place";
  return "";
}
