export type RecallSheet = { id: string; title: string; note: string; columns: string[]; rows: string[][]; tip?: string };
const genders = ["Case", "Masculine", "Feminine", "Neuter", "Plural"];
const cases = ["Nominativ", "Akkusativ", "Dativ", "Genitiv"];
function forms(id: string, title: string, note: string, rows: string[][], tip?: string): RecallSheet {
  return { id, title, note, columns: genders, rows: rows.map((row, i) => [cases[i], ...row]), tip };
}
export const RECALL_SHEETS: RecallSheet[] = [
  { id: "case-map", title: "Choose the case", note: "First find what governs the phrase: a verb, a preposition, or its role in the sentence. Then choose gender and number.", columns: ["Case", "Question", "Typical role", "Example"], rows: [
    ["Nominativ", "wer? / was?", "Subject; predicate noun after sein, werden, bleiben", "Der Hund schläft. Er ist ein Freund."],
    ["Akkusativ", "wen? / was?", "Direct object; certain prepositions", "Ich sehe den Hund."],
    ["Dativ", "wem?", "Recipient; certain verbs and prepositions", "Ich gebe dem Hund Wasser."],
    ["Genitiv", "wessen?", "Possession or relationship; certain prepositions", "Das Halsband des Hundes ist rot."],
  ], tip: "English word order does not decide German case. Learn a verb or preposition together with the case it requires." },
  forms("articles", "Definite articles · der, die, das", "Use these with a specific or identifiable noun.", [["der", "die", "das", "die"], ["den", "die", "das", "die"], ["dem", "der", "dem", "den"], ["des", "der", "des", "der"]], "Dative plural usually adds -n to the noun too: mit den Kindern. No extra -n after plural -n or -s: den Frauen, den Autos."),
  forms("indefinite", "Indefinite articles · ein", "Ein has no plural. An indefinite plural can have no article: Ich kaufe Bücher.", [["ein", "eine", "ein", "—"], ["einen", "eine", "ein", "—"], ["einem", "einer", "einem", "—"], ["eines", "einer", "eines", "—"]]),
  forms("negative", "Negative articles · kein", "Kein negates nouns with an indefinite article or no article: ein Auto → kein Auto; Bücher → keine Bücher.", [["kein", "keine", "kein", "keine"], ["keinen", "keine", "kein", "keine"], ["keinem", "keiner", "keinem", "keinen"], ["keines", "keiner", "keines", "keiner"]]),
  { id: "possessors", title: "Possessive stems · whose?", note: "Choose the stem from the owner; choose the ending from the possessed noun's case, gender and number.", columns: ["Owner", "Stem", "Example"], rows: [["ich", "mein-", "mein Bruder"], ["du", "dein-", "deine Schwester"], ["er / es", "sein-", "sein Fahrrad"], ["sie (she)", "ihr-", "ihr Fahrrad"], ["wir", "unser-", "unsere Wohnung"], ["ihr", "euer- / eur-", "euer Hund; eure Katze"], ["sie (they)", "ihr-", "ihre Kinder"], ["Sie (formal)", "Ihr-", "Ihre Tasche"]], tip: "The owner does not determine the ending: Anna hilft ihrem Bruder. Euer normally loses its second e before an ending: euren, eurem, eurer, eures." },
  forms("possessive-articles", "Possessives before a noun · mein", "Replace mein- with the appropriate possessive stem. These also show the ein-word ending pattern.", [["mein", "meine", "mein", "meine"], ["meinen", "meine", "mein", "meine"], ["meinem", "meiner", "meinem", "meinen"], ["meines", "meiner", "meines", "meiner"]], "Example: Ich spreche mit meiner neuen Lehrerin. Possessive endings describe Lehrerin, not the speaker."),
  forms("possessive-pronouns", "Possessives replacing a noun · meiner", "Standalone possessives need an ending even where mein before a noun has none. Genitive forms are rare in ordinary conversation.", [["meiner", "meine", "meins / meines", "meine"], ["meinen", "meine", "meins / meines", "meine"], ["meinem", "meiner", "meinem", "meinen"], ["meines", "meiner", "meines", "meiner"]], "Ist das dein Stift? — Nein, meiner ist blau. Ist das dein Buch? — Ja, das ist meins."),
  { id: "personal", title: "Personal pronouns", note: "Genitive personal pronouns are formal or literary. They are not the everyday possessive articles mein, dein, etc.", columns: ["Person", ...cases], rows: [["I", "ich", "mich", "mir", "meiner"], ["you · singular", "du", "dich", "dir", "deiner"], ["he", "er", "ihn", "ihm", "seiner"], ["she", "sie", "sie", "ihr", "ihrer"], ["it", "es", "es", "ihm", "seiner"], ["we", "wir", "uns", "uns", "unser"], ["you · plural", "ihr", "euch", "euch", "euer"], ["they", "sie", "sie", "ihnen", "ihrer"], ["you · formal", "Sie", "Sie", "Ihnen", "Ihrer"]], tip: "Ich sehe ihn. Ich helfe ihm. Formal/literary: Wir gedenken ihrer. Everyday possession: Das ist ihr Buch." },
  { id: "reflexive", title: "Reflexive and reciprocal pronouns", note: "Reflexive objects are usually accusative or dative. There is no nominative reflexive object; genitive reflexives occur only in formal constructions.", columns: ["Subject", "Akkusativ", "Dativ", "Genitiv · rare"], rows: [["ich", "mich", "mir", "meiner"], ["du", "dich", "dir", "deiner"], ["er / sie / es", "sich", "sich", "seiner / ihrer / seiner"], ["wir", "uns", "uns", "unser"], ["ihr", "euch", "euch", "euer"], ["sie / Sie", "sich", "sich", "ihrer / Ihrer"]], tip: "Ich wasche mich. Ich wasche mir die Hände (die Hände is accusative). Reciprocal: Wir helfen einander; wir sprechen miteinander. Einander itself does not change." },
  forms("demonstratives", "Demonstratives and welcher · dieser pattern", "Dies- and jen- take these endings. Welch- uses the same pattern: welcher, welche, welches. Jeder is normally singular; use alle for ‘all’ in the plural.", [["dieser", "diese", "dieses", "diese"], ["diesen", "diese", "dieses", "diese"], ["diesem", "dieser", "diesem", "diesen"], ["dieses", "dieser", "dieses", "dieser"]], "Standalone der/die/das demonstratives use the relative-pronoun forms below (including denen and dessen/deren); genitive plural derer also occurs, especially before a following relative clause."),
  forms("relative", "Relative pronouns · der, die, das", "Gender and number come from the noun referred to. Case comes from the pronoun's role inside the relative clause.", [["der", "die", "das", "die"], ["den", "die", "das", "die"], ["dem", "der", "dem", "denen"], ["dessen", "deren", "dessen", "deren"]], "Der Mann, dem ich helfe, ist nett. Die Frau, deren Sohn hier wohnt, kommt morgen. A preposition stays with its case: das Kind, mit dem ich spreche."),
  { id: "questions", title: "Question words and indefinite pronouns", note: "Not every pronoun has a normal form in every case. Dashes mark forms that are not used as an ordinary paradigm.", columns: ["Meaning", ...cases], rows: [["who", "wer", "wen", "wem", "wessen"], ["what", "was", "was", "—", "wessen"], ["someone", "jemand", "jemanden / jemand", "jemandem / jemand", "jemandes"], ["nobody", "niemand", "niemanden / niemand", "niemandem / niemand", "niemandes"], ["one / people", "man", "einen", "einem", "—"], ["something / nothing", "etwas / nichts", "etwas / nichts", "etwas / nichts", "—"]], tip: "Prefer the explicit endings jemanden/jemandem when learning. For things after a preposition use wo(r)-: womit? woran? For people: mit wem? an wen? Etwas and nichts do not decline: mit etwas Glück; nichts Neues." },
  forms("adjectives-weak", "Adjective endings · after der-words", "After der/die/das and declined dieser/welcher: weak declension. Add the ending to the adjective stem.", [["-e", "-e", "-e", "-en"], ["-en", "-e", "-e", "-en"], ["-en", "-en", "-en", "-en"], ["-en", "-en", "-en", "-en"]], "der kleine Hund; die kleine Katze; das kleine Kind; mit den kleinen Kindern"),
  forms("adjectives-mixed", "Adjective endings · after ein-words", "After ein, kein and possessives: mixed declension. The plural applies to keine/meine, because ein has no plural.", [["-er", "-e", "-es", "-en"], ["-en", "-e", "-es", "-en"], ["-en", "-en", "-en", "-en"], ["-en", "-en", "-en", "-en"]], "ein kleiner Hund; ein kleines Kind; meine kleinen Kinder; mit einem kleinen Kind"),
  forms("adjectives-strong", "Adjective endings · without an article", "With no article carrying the case ending: strong declension. Masculine and neuter genitive adjectives normally end in -en, not -es.", [["-er", "-e", "-es", "-e"], ["-en", "-e", "-es", "-e"], ["-em", "-er", "-em", "-en"], ["-en", "-er", "-en", "-er"]], "frischer Tee; kaltes Wasser; mit frischem Brot; wegen schlechten Wetters. Predicate/adverbial adjectives do not decline: Der Tee ist heiß. Sie läuft schnell."),
  forms("nouns", "Noun endings · ordinary nouns", "The article carries much of the case information. Nouns have additional endings, especially in the genitive and dative plural.", [["der Tag", "die Frau", "das Kind", "die Kinder"], ["den Tag", "die Frau", "das Kind", "die Kinder"], ["dem Tag", "der Frau", "dem Kind", "den Kindern"], ["des Tages", "der Frau", "des Kindes", "der Kinder"]], "Most masculine/neuter nouns take genitive -(e)s. Names commonly take -s: Annas Buch. After a name ending in an s-sound, use an apostrophe: Max’ Buch."),
  { id: "weak-nouns", title: "Weak nouns and nominalized adjectives", note: "Many masculine person/animal nouns add -(e)n outside nominative singular. Learn the noun with its pattern; not every masculine noun is weak.", columns: ["Case", "Student · weak", "Name · mixed", "Herz · irregular", "Adjective used as noun"], rows: [["Nominativ", "der Student", "der Name", "das Herz", "der Deutsche / ein Deutscher"], ["Akkusativ", "den Studenten", "den Namen", "das Herz", "den Deutschen / einen Deutschen"], ["Dativ", "dem Studenten", "dem Namen", "dem Herzen", "dem Deutschen / einem Deutschen"], ["Genitiv", "des Studenten", "des Namens", "des Herzens", "des Deutschen / eines Deutschen"]], tip: "Also: der Junge → dem Jungen; der Mensch → des Menschen; der Herr → den Herrn. Nominalized adjectives and participles keep adjective endings and use a capital letter: eine Bekannte, mit den Reisenden." },
  { id: "prepositions", title: "Prepositions by case", note: "Prepositions govern a case; they do not themselves decline. No ordinary German preposition governs the nominative.", columns: ["Case", "Core prepositions", "Example / qualification"], rows: [["Akkusativ", "durch, für, gegen, ohne, um", "für meinen Bruder; ohne dich"], ["Akkusativ · special", "bis; entlang (after the noun)", "bis nächsten Montag; den Fluss entlang. Bis often combines with another preposition: bis zum Bahnhof."], ["Dativ", "aus, außer, bei, mit, nach, seit, von, zu, gegenüber", "mit meiner Schwester; seit einem Jahr; dem Haus gegenüber"], ["Genitiv · standard written usage", "wegen, trotz, während, (an)statt; innerhalb, außerhalb, oberhalb, unterhalb, diesseits, jenseits, angesichts", "wegen des Regens; außerhalb der Stadt. Dative variants occur with some of these, especially colloquially; learn the standard genitive first."], ["Akkusativ or Dativ", "an, auf, hinter, in, neben, über, unter, vor, zwischen", "Spatial destination: in den Park. Spatial location: im Park."]], tip: "Additional prepositions have register-dependent patterns (e.g. dank, laut, zufolge). Check their individual entry rather than extending a mnemonic to every use. Entlang before a noun can take genitive: entlang des Flusses." },
  { id: "two-way", title: "Two-way prepositions · destination vs location", note: "For spatial uses of the nine two-way prepositions, ask whether a new spatial relationship is established. Movement alone does not mean accusative.", columns: ["Preposition", "Akkusativ · wohin?", "Dativ · wo?"], rows: [["an", "Ich hänge das Bild an die Wand.", "Das Bild hängt an der Wand."], ["auf", "Ich lege es auf den Tisch.", "Es liegt auf dem Tisch."], ["hinter", "Ich stelle es hinter die Tür.", "Es steht hinter der Tür."], ["in", "Ich gehe in den Park.", "Ich laufe im Park."], ["neben", "Ich setze mich neben dich.", "Ich sitze neben dir."], ["über", "Ich hänge die Lampe über den Tisch.", "Die Lampe hängt über dem Tisch."], ["unter", "Ich schiebe es unter das Bett.", "Es liegt unter dem Bett."], ["vor", "Ich stelle mich vor das Haus.", "Ich stehe vor dem Haus."], ["zwischen", "Ich lege es zwischen die Bücher.", "Es liegt zwischen den Büchern."]], tip: "Fixed verb-preposition combinations follow their own case: warten auf + Akkusativ, teilnehmen an + Dativ. Do not apply wo/wohin to them." },
  { id: "contractions", title: "Preposition + article contractions", note: "The contracted article still carries its original case. Use the full article when it is deliberately stressed or demonstrative.", columns: ["Form", "Expanded", "Case", "Example"], rows: [["am / beim / vom", "an / bei / von + dem", "Dativ", "am Montag; beim Arzt; vom Bahnhof"], ["im / zum", "in / zu + dem", "Dativ", "im Garten; zum Kurs"], ["zur", "zu + der", "Dativ · feminine", "zur Schule"], ["ans / ins", "an / in + das", "Akkusativ · neuter", "ans Meer; ins Kino"], ["aufs / fürs / ums", "auf / für / um + das", "Akkusativ · neuter", "aufs Dach; fürs Kind; ums Haus"]], tip: "Zu always takes dative, even for a destination: Ich gehe zum Arzt. Direction is not a universal accusative rule." },
  { id: "verbs", title: "Verbs and their case patterns", note: "These are high-frequency patterns, not an exhaustive verb dictionary. Learn the complete construction, not just an English translation.", columns: ["Pattern", "Useful verbs", "Example"], rows: [["Nominativ + Nominativ", "sein, werden, bleiben", "Er wird ein guter Lehrer."], ["Akkusativ object", "haben, sehen, brauchen, besuchen, fragen", "Ich frage den Lehrer."], ["Dativ object", "helfen, danken, gefallen, gehören, folgen, antworten, vertrauen", "Ich helfe dem Lehrer."], ["Dativ person + Akkusativ thing", "geben, schicken, zeigen, erklären, schenken", "Ich erkläre ihr die Regel."], ["Two accusative objects", "nennen; some uses of fragen, kosten", "Sie nennt ihn einen Freund."], ["Genitiv object · formal", "gedenken, bedürfen; sich einer Sache bewusst sein", "Wir gedenken der Opfer."], ["Fixed preposition + Akkusativ", "warten auf; denken an; sich interessieren für", "Ich warte auf den Bus."], ["Fixed preposition + Dativ", "teilnehmen an; sprechen mit; träumen von", "Sie nimmt an einem Kurs teil."]], tip: "With two unstressed personal-pronoun objects, accusative usually precedes dative: Ich gebe es ihr. With two noun objects, dative commonly comes first: Ich gebe der Frau das Buch. Case stays the same when emphasis changes word order." },
  { id: "case-extras", title: "Time, comparison and case traps", note: "Case also appears without prepositions. These patterns help explain forms that do not look like ordinary objects.", columns: ["Construction", "Case / rule", "Example"], rows: [["Duration / definite time without a preposition", "Often Akkusativ", "Ich bleibe einen Monat. Nächsten Montag komme ich."], ["Indefinite time", "Some fixed Genitiv expressions", "Eines Tages verstehen wir es."], ["Comparison with als / wie", "Case follows the role of the compared phrase", "Er arbeitet als Lehrer. Ich sehe ihn als einen Freund."], ["Passive", "An active accusative object can become a nominative subject; dative stays dative", "Man hilft dem Kind. → Dem Kind wird geholfen."], ["Da(r)-words", "Refer to things/situations, not people; no case endings", "Ich warte darauf. Ich spreche mit ihr (a person)."], ["Apposition", "Usually matches the case of its reference noun", "mit Herrn Weber, unserem Lehrer"], ["Quantifiers", "Not all behave like der or ein", "alle guten Bücher (weak); viele gute Bücher (strong). Learn variable quantifiers individually."]], tip: "Tenses, verb conjugation, conjunctions and sentence order are separate grammar systems. Use the Grammar lessons for those; four-case tables apply to declension and case government." },
];
