import type { GrammarExercise } from "@/app/grammar/course";

const withGroup = (group: string, items: GrammarExercise[]) => items.map((item) => ({ ...item, group }));
const ex = (item: GrammarExercise) => item;

export const A1_LESSON_SEVENTEEN_EXERCISES: GrammarExercise[] = [
  ...withGroup("1 · Existence or possession", [
    ex({ id: "a135-01", type: "choice", prompt: "Which phrase means there is / there are?", options: ["es gibt", "es hat", "es ist", "man gibt"], answer: "es gibt", explanation: "es gibt presents something as existing or available." }),
    ex({ id: "a135-02", type: "choice", prompt: "Which sentence expresses possession?", options: ["Ich habe ein Fahrrad.", "Es gibt ein Fahrrad.", "Das Fahrrad ist da.", "Ein Fahrrad kommt."], answer: "Ich habe ein Fahrrad.", explanation: "haben links an owner to what they possess." }),
    ex({ id: "a135-03", type: "choice", prompt: "Which case follows es gibt?", options: ["accusative", "nominative", "dative", "genitive"], answer: "accusative", explanation: "The noun phrase after es gibt is always accusative." }),
    ex({ id: "a135-04", type: "choice", prompt: "Choose: In der Stadt ___ einen Bahnhof.", options: ["gibt es", "hat es", "ist es", "haben"], answer: "gibt es", explanation: "When a place is first, gibt remains second and es follows it." }),
    ex({ id: "a135-05", type: "choice", prompt: "Choose: Wir ___ heute keine Zeit.", options: ["haben", "gibt", "hat", "sind"], answer: "haben", explanation: "The subject wir takes haben." }),
    ex({ id: "a135-06", type: "choice", prompt: "Choose the correct negative: Es gibt ___ Aufzug.", options: ["keinen", "kein", "nicht ein", "keine"], answer: "keinen", explanation: "Aufzug is masculine accusative: keinen Aufzug." }),
    ex({ id: "a135-07", type: "choice", prompt: "Choose the correct negative: Das Hotel hat ___ Restaurant.", options: ["kein", "keinen", "keine", "nicht"], answer: "kein", explanation: "Restaurant is neuter accusative: kein Restaurant." }),
    ex({ id: "a135-08", type: "choice", prompt: "Which question asks whether something is available?", options: ["Gibt es hier WLAN?", "Hat WLAN hier?", "Ist es WLAN?", "Wo WLAN gibt?"], answer: "Gibt es hier WLAN?", explanation: "A yes/no question begins Gibt es …?" }),
    ex({ id: "a135-09", type: "choice", prompt: "Choose the correct haben form: Meine Wohnung ___ zwei Zimmer.", options: ["hat", "habe", "haben", "habt"], answer: "hat", explanation: "The singular subject Wohnung takes hat." }),
    ex({ id: "a135-10", type: "choice", prompt: "Which sentence means The room has a balcony?", options: ["Das Zimmer hat einen Balkon.", "Es gibt das Zimmer einen Balkon.", "Das Zimmer gibt einen Balkon.", "Der Balkon hat das Zimmer."], answer: "Das Zimmer hat einen Balkon.", explanation: "haben describes a feature belonging to the room." }),
  ]),
  ...withGroup("2 · Articles and forms", [
    ex({ id: "a135-11", type: "fill", prompt: "Es gibt hier ___ Supermarkt. (a)", answer: "einen", explanation: "Supermarkt is masculine accusative: einen Supermarkt." }),
    ex({ id: "a135-12", type: "fill", prompt: "Es gibt ___ Apotheke in der Nähe. (a)", answer: "eine", explanation: "Apotheke is feminine accusative: eine Apotheke." }),
    ex({ id: "a135-13", type: "fill", prompt: "Das Hotel hat ___ Schwimmbad. (a)", answer: "ein", explanation: "Schwimmbad is neuter accusative: ein Schwimmbad." }),
    ex({ id: "a135-14", type: "fill", prompt: "In der Straße gibt es ___ Cafés. (some / no article)", answer: ["Cafés", "viele Cafés", "einige Cafés"], explanation: "An indefinite plural often appears without an article." }),
    ex({ id: "a135-15", type: "fill", prompt: "Es gibt hier ___ Parkplatz. (no)", answer: "keinen", explanation: "Masculine accusative kein becomes keinen." }),
    ex({ id: "a135-16", type: "fill", prompt: "Die Wohnung hat ___ Küche. (no)", answer: "keine", explanation: "Feminine accusative uses keine." }),
    ex({ id: "a135-17", type: "fill", prompt: "Das Dorf hat ___ Kino. (no)", answer: "kein", explanation: "Neuter accusative uses kein." }),
    ex({ id: "a135-18", type: "fill", prompt: "Wir ___ zwei Kinder. (haben)", answer: "haben", explanation: "The wir form is haben." }),
    ex({ id: "a135-19", type: "fill", prompt: "___ du morgen Zeit? (haben)", answer: "Hast", explanation: "The du question starts with Hast." }),
    ex({ id: "a135-20", type: "fill", prompt: "Warum ___ Paul kein Auto? (haben)", answer: "hat", explanation: "Paul takes the third-person singular form hat." }),
  ]),
  ...withGroup("3 · Build and repair", [
    ex({ id: "a135-21", type: "order", prompt: "Build the existence sentence.", tokens: ["einen", "hier", "Park", "Es", "gibt", "."], answer: "Es gibt hier einen Park.", explanation: "es gibt is followed by the accusative phrase einen Park." }),
    ex({ id: "a135-22", type: "order", prompt: "Start with the place.", tokens: ["gibt", "In", "es", "Stadt", "Museen", "der", "."], answer: "In der Stadt gibt es Museen.", explanation: "The place is first, gibt second, and es follows the verb." }),
    ex({ id: "a135-23", type: "order", prompt: "Build the possession sentence.", tokens: ["hat", "Balkon", "Wohnung", "Die", "einen", "."], answer: "Die Wohnung hat einen Balkon.", explanation: "Wohnung is the subject; Balkon is masculine accusative." }),
    ex({ id: "a135-24", type: "order", prompt: "Build the availability question.", tokens: ["hier", "Gibt", "WLAN", "es", "?"], answer: "Gibt es hier WLAN?", explanation: "A yes/no question begins with Gibt es." }),
    ex({ id: "a135-25", type: "order", prompt: "Build the negative sentence.", tokens: ["keinen", "Das", "Aufzug", "Hotel", "hat", "."], answer: "Das Hotel hat keinen Aufzug.", explanation: "Aufzug is masculine accusative after haben." }),
    ex({ id: "a135-26", type: "correction", prompt: "Correct: Es hat hier einen Bahnhof.", answer: "Es gibt hier einen Bahnhof.", explanation: "Use es gibt for existence, not es hat." }),
    ex({ id: "a135-27", type: "correction", prompt: "Correct: Es gibt ein Supermarkt.", answer: "Es gibt einen Supermarkt.", explanation: "Supermarkt is masculine accusative." }),
    ex({ id: "a135-28", type: "correction", prompt: "Correct: Meine Stadt haben viele Parks.", answer: "Meine Stadt hat viele Parks.", explanation: "The singular subject Stadt takes hat." }),
    ex({ id: "a135-29", type: "correction", prompt: "Correct: Gibt hier es ein Hotel?", answer: "Gibt es hier ein Hotel?", explanation: "The fixed question opening is Gibt es." }),
    ex({ id: "a135-30", type: "correction", prompt: "Correct: Das Zimmer hat nicht Balkon.", answer: "Das Zimmer hat keinen Balkon.", explanation: "Negate the masculine noun with keinen." }),
  ]),
  ...withGroup("4 · Translation", [
    ex({ id: "a135-31", type: "translation", direction: "en-de", prompt: "Translate: There is a supermarket here.", answer: ["Hier gibt es einen Supermarkt.", "Es gibt hier einen Supermarkt."], explanation: "es gibt requires masculine accusative einen Supermarkt." }),
    ex({ id: "a135-32", type: "translation", direction: "en-de", prompt: "Translate: There are two cafés in the street.", answer: ["In der Straße gibt es zwei Cafés.", "Es gibt zwei Cafés in der Straße."], explanation: "A number directly introduces the plural noun." }),
    ex({ id: "a135-33", type: "translation", direction: "en-de", prompt: "Translate: Is there a pharmacy nearby?", answer: ["Gibt es eine Apotheke in der Nähe?", "Gibt es in der Nähe eine Apotheke?"], explanation: "Use Gibt es …? for availability." }),
    ex({ id: "a135-34", type: "translation", direction: "en-de", prompt: "Translate: The apartment has a balcony.", answer: ["Die Wohnung hat einen Balkon.", "Die Wohnung hat einen Balkon"], explanation: "haben links the apartment to its feature." }),
    ex({ id: "a135-35", type: "translation", direction: "en-de", prompt: "Translate: We do not have time today.", answer: ["Wir haben heute keine Zeit.", "Heute haben wir keine Zeit."], explanation: "Zeit is feminine, so use keine." }),
    ex({ id: "a135-36", type: "translation", direction: "de-en", prompt: "Translate: Im Hotel gibt es kein Restaurant.", answer: ["There is no restaurant in the hotel.", "The hotel has no restaurant."], explanation: "kein Restaurant negates a neuter noun after es gibt." }),
    ex({ id: "a135-37", type: "translation", direction: "de-en", prompt: "Translate: Haben Sie ein freies Zimmer?", answer: ["Do you have an available room?", "Do you have a vacant room?"], explanation: "haben asks the hotel or receptionist about possession or availability." }),
    ex({ id: "a135-38", type: "translation", direction: "de-en", prompt: "Translate: In unserem Kurs gibt es zwölf Teilnehmer.", answer: ["There are twelve participants in our course.", "Our course has twelve participants."], explanation: "es gibt introduces what the course contains." }),
    ex({ id: "a135-39", type: "translation", direction: "de-en", prompt: "Translate: Das Auto hat ein Problem.", answer: ["The car has a problem."], explanation: "haben describes a feature or condition of the car." }),
    ex({ id: "a135-40", type: "translation", direction: "de-en", prompt: "Translate: Gibt es heute noch Tickets?", answer: ["Are there still tickets today?", "Are any tickets still available today?"], explanation: "Gibt es …? asks about availability." }),
  ]),
  ...withGroup("5 · Describing what is available", [
    ex({ id: "a135-41", type: "production", prompt: "Describe your neighbourhood with five es gibt sentences.", model: "In meinem Viertel gibt es einen Supermarkt, eine Apotheke und zwei Cafés. Es gibt auch einen kleinen Park. Leider gibt es kein Kino.", explanation: "Use accusative articles after es gibt." }),
    ex({ id: "a135-42", type: "production", prompt: "Describe your home with five haben sentences.", model: "Meine Wohnung hat zwei Zimmer. Das Wohnzimmer hat einen Balkon. Die Küche hat ein großes Fenster. Wir haben keinen Garten. Mein Zimmer hat viele Bücher.", explanation: "Match haben to its subject and use accusative noun phrases." }),
    ex({ id: "a135-43", type: "production", prompt: "Write six availability questions for a hotel.", model: "Gibt es WLAN? Gibt es einen Aufzug? Gibt es ein Restaurant? Gibt es freie Zimmer? Haben Sie einen Parkplatz? Hat das Zimmer einen Balkon?", explanation: "Choose es gibt for existence and haben for features or the service provider." }),
    ex({ id: "a135-44", type: "production", prompt: "Write five positive and five negative city facts.", model: "Es gibt einen Bahnhof, aber es gibt keinen Flughafen. Die Stadt hat viele Parks, aber sie hat kein großes Stadion.", explanation: "Practise kein endings across masculine, feminine, neuter, and plural nouns." }),
    ex({ id: "a135-45", type: "production", prompt: "Create a six-line apartment-viewing dialogue.", model: "Wie viele Zimmer hat die Wohnung? – Sie hat drei Zimmer. Gibt es einen Balkon? – Ja. Hat die Küche ein Fenster? – Nein, aber es gibt ein Fenster im Wohnzimmer.", explanation: "Alternate existence questions with feature questions." }),
    ex({ id: "a135-46", type: "production", prompt: "Compare two towns in eight sentences.", model: "In A-Dorf gibt es einen Bahnhof, aber B-Dorf hat keinen Bahnhof. Beide Orte haben Schulen. In B-Dorf gibt es mehr Cafés. A-Dorf hat einen großen Park.", explanation: "Use both structures naturally instead of translating English word for word." }),
    ex({ id: "a135-47", type: "production", prompt: "Make a four-column noun list for ein/einen/eine/kein forms after es gibt.", model: "einen: einen Park, einen Bus · eine: eine Bank, eine Schule · ein: ein Kino, ein Hotel · plural: Cafés, Geschäfte", explanation: "Sorting by gender makes accusative choice visible." }),
    ex({ id: "a135-48", type: "production", prompt: "Write a short event notice saying what the event has and what is available.", model: "Das Stadtfest hat drei Bühnen und ein Kinderprogramm. Auf dem Platz gibt es viele Essensstände. Es gibt auch Musik. Das Fest hat keinen Eintritt: Der Besuch ist kostenlos.", explanation: "Use haben for event features and es gibt to introduce available things." }),
    ex({ id: "a135-49", type: "production", prompt: "Describe a problem location using eight negative sentences.", model: "Im Dorf gibt es keinen Arzt und keine Apotheke. Es gibt keine Busse am Abend. Der Bahnhof hat keinen Aufzug. Die Schule hat keine Sporthalle.", explanation: "Use kein rather than nicht to negate absent nouns." }),
    ex({ id: "a135-50", type: "production", prompt: "Record a one-minute guide to what your area offers.", model: "In meiner Gegend gibt es alles für den Alltag. Es gibt einen Markt, mehrere Geschäfte und einen Bahnhof. Der Bahnhof hat einen Aufzug. Leider gibt es kein Schwimmbad, aber die Nachbarstadt hat eins.", explanation: "Fluent comparison helps existence, possession, and accusative forms work together." }),
  ]),
];

export const A1_LESSON_EIGHTEEN_EXERCISES: GrammarExercise[] = [
  ...withGroup("1 · Reflexive pronouns", [
    ex({ id: "a136-01", type: "choice", prompt: "Choose the reflexive pronoun for ich.", options: ["mich", "dich", "sich", "mir"], answer: "mich", explanation: "The A1 accusative reflexive pronoun for ich is mich." }),
    ex({ id: "a136-02", type: "choice", prompt: "Choose the reflexive pronoun for du.", options: ["dich", "mich", "sich", "euch"], answer: "dich", explanation: "The reflexive pronoun for du is dich." }),
    ex({ id: "a136-03", type: "choice", prompt: "Choose the reflexive pronoun for er/sie/es.", options: ["sich", "ihn", "sie", "es"], answer: "sich", explanation: "All third-person subjects use sich." }),
    ex({ id: "a136-04", type: "choice", prompt: "Choose the reflexive pronoun for wir.", options: ["uns", "euch", "sich", "wir"], answer: "uns", explanation: "The reflexive pronoun for wir is uns." }),
    ex({ id: "a136-05", type: "choice", prompt: "Choose the reflexive pronoun for ihr.", options: ["euch", "uns", "sich", "ihr"], answer: "euch", explanation: "The reflexive pronoun for ihr is euch." }),
    ex({ id: "a136-06", type: "choice", prompt: "Choose the reflexive pronoun for formal Sie.", options: ["sich", "Sie", "Ihnen", "euch"], answer: "sich", explanation: "Formal Sie uses sich, written lowercase." }),
    ex({ id: "a136-07", type: "choice", prompt: "Which sentence means I am getting dressed?", options: ["Ich ziehe mich an.", "Ich ziehe an mich.", "Ich anziehe mich.", "Mich zieht ich an."], answer: "Ich ziehe mich an.", explanation: "The pronoun follows the finite verb and the prefix closes the clause." }),
    ex({ id: "a136-08", type: "choice", prompt: "Which verb means to hurry?", options: ["sich beeilen", "sich freuen", "sich treffen", "sich setzen"], answer: "sich beeilen", explanation: "sich beeilen means to hurry." }),
    ex({ id: "a136-09", type: "choice", prompt: "Which sentence is not reflexive?", options: ["Ich wasche das Auto.", "Ich wasche mich.", "Er setzt sich.", "Wir beeilen uns."], answer: "Ich wasche das Auto.", explanation: "The action affects das Auto, not the subject." }),
    ex({ id: "a136-10", type: "choice", prompt: "Where does sich stand in Heute freut sich Mia?", options: ["after the conjugated verb", "at the very end", "before position one", "joined to the verb"], answer: "after the conjugated verb", explanation: "With a noun subject after the verb, the short reflexive pronoun usually comes before that noun." }),
  ]),
  ...withGroup("2 · Daily routines", [
    ex({ id: "a136-11", type: "fill", prompt: "Ich wasche ___ jeden Morgen.", answer: "mich", explanation: "The subject ich reflects back as mich." }),
    ex({ id: "a136-12", type: "fill", prompt: "Du ziehst ___ schnell an.", answer: "dich", explanation: "The subject du reflects back as dich." }),
    ex({ id: "a136-13", type: "fill", prompt: "Paul rasiert ___ im Bad.", answer: "sich", explanation: "Paul equals er, so use sich." }),
    ex({ id: "a136-14", type: "fill", prompt: "Wir beeilen ___ heute.", answer: "uns", explanation: "The reflexive pronoun for wir is uns." }),
    ex({ id: "a136-15", type: "fill", prompt: "Kinder, setzt ___ bitte!", answer: "euch", explanation: "The ihr command uses euch." }),
    ex({ id: "a136-16", type: "fill", prompt: "Frau Klein, setzen Sie ___ bitte.", answer: "sich", explanation: "Formal Sie uses sich." }),
    ex({ id: "a136-17", type: "fill", prompt: "Mia und Tom treffen ___ um acht.", answer: "sich", explanation: "A third-person plural subject uses sich; here it has reciprocal meaning." }),
    ex({ id: "a136-18", type: "fill", prompt: "Freust du ___ auf das Wochenende?", answer: "dich", explanation: "sich freuen agrees with du as dich." }),
    ex({ id: "a136-19", type: "fill", prompt: "Ich muss ___ jetzt anziehen.", answer: "mich", explanation: "After a modal, the reflexive pronoun follows the modal while anziehen remains final." }),
    ex({ id: "a136-20", type: "fill", prompt: "Wann stellt ihr ___? (sich vorstellen)", answer: "euch vor", explanation: "sich vorstellen separates as stellt euch … vor; the prompt expects the pronoun and prefix." }),
  ]),
  ...withGroup("3 · Word order and repair", [
    ex({ id: "a136-21", type: "order", prompt: "Build the sentence.", tokens: ["mich", "Ich", "wasche", "."], answer: "Ich wasche mich.", explanation: "The reflexive pronoun follows the conjugated verb." }),
    ex({ id: "a136-22", type: "order", prompt: "Build the separable reflexive sentence.", tokens: ["zieht", "sich", "Mia", "an", "."], answer: "Mia zieht sich an.", explanation: "sich follows zieht; an closes the clause." }),
    ex({ id: "a136-23", type: "order", prompt: "Start with Heute.", tokens: ["Heute", "wir", "uns", "beeilen", "."], answer: "Heute beeilen wir uns.", explanation: "The subject follows the verb, then the reflexive pronoun." }),
    ex({ id: "a136-24", type: "order", prompt: "Build the question.", tokens: ["du", "dich", "Freust", "?"], answer: "Freust du dich?", explanation: "The verb opens the question, followed by subject and reflexive pronoun." }),
    ex({ id: "a136-25", type: "order", prompt: "Build the modal sentence.", tokens: ["muss", "Ich", "mich", "beeilen", "."], answer: "Ich muss mich beeilen.", explanation: "The pronoun follows the modal and the infinitive is final." }),
    ex({ id: "a136-26", type: "correction", prompt: "Correct: Ich wasche dich. (myself)", answer: "Ich wasche mich.", explanation: "The pronoun must refer back to ich." }),
    ex({ id: "a136-27", type: "correction", prompt: "Correct: Du ziehst mich an. (yourself)", answer: "Du ziehst dich an.", explanation: "The subject du requires dich." }),
    ex({ id: "a136-28", type: "correction", prompt: "Correct: Wir uns beeilen heute.", answer: "Wir beeilen uns heute.", explanation: "The conjugated verb remains in position two." }),
    ex({ id: "a136-29", type: "correction", prompt: "Correct: Er sich setzt hier.", answer: "Er setzt sich hier.", explanation: "sich follows the conjugated verb." }),
    ex({ id: "a136-30", type: "correction", prompt: "Correct formally: Setzen Sie Sie bitte.", answer: "Setzen Sie sich bitte.", explanation: "Formal Sie uses the lowercase reflexive pronoun sich." }),
  ]),
  ...withGroup("4 · Translation", [
    ex({ id: "a136-31", type: "translation", direction: "en-de", prompt: "Translate: I wash myself every morning.", answer: ["Ich wasche mich jeden Morgen.", "Jeden Morgen wasche ich mich."], explanation: "ich requires the reflexive pronoun mich." }),
    ex({ id: "a136-32", type: "translation", direction: "en-de", prompt: "Translate: Are you getting dressed? (informal singular)", answer: ["Ziehst du dich an?", "Ziehst du dich gerade an?"], explanation: "anziehen splits and du takes dich." }),
    ex({ id: "a136-33", type: "translation", direction: "en-de", prompt: "Translate: We have to hurry.", answer: ["Wir müssen uns beeilen.", "Wir müssen uns beeilen"], explanation: "uns follows müssen and beeilen is final." }),
    ex({ id: "a136-34", type: "translation", direction: "en-de", prompt: "Translate formally: Please sit down.", answer: ["Setzen Sie sich bitte!", "Bitte setzen Sie sich!"], explanation: "Formal Sie takes sich." }),
    ex({ id: "a136-35", type: "translation", direction: "en-de", prompt: "Translate: The children are looking forward to the holiday.", answer: ["Die Kinder freuen sich auf die Ferien.", "Die Kinder freuen sich auf den Urlaub."], explanation: "A plural third-person subject uses sich." }),
    ex({ id: "a136-36", type: "translation", direction: "de-en", prompt: "Translate: Ich interessiere mich für Musik.", answer: ["I am interested in music."], explanation: "sich interessieren für means to be interested in." }),
    ex({ id: "a136-37", type: "translation", direction: "de-en", prompt: "Translate: Beeilt euch bitte!", answer: ["Please hurry up!", "Hurry up, please!"], explanation: "euch refers back to informal plural ihr." }),
    ex({ id: "a136-38", type: "translation", direction: "de-en", prompt: "Translate: Wann trefft ihr euch?", answer: ["When are you meeting?", "When do you meet each other?"], explanation: "euch has reciprocal meaning with a plural subject." }),
    ex({ id: "a136-39", type: "translation", direction: "de-en", prompt: "Translate: Heute rasiert sich Paul nicht.", answer: ["Paul is not shaving today.", "Today Paul does not shave."], explanation: "The reflexive pronoun precedes the noun subject after the verb." }),
    ex({ id: "a136-40", type: "translation", direction: "de-en", prompt: "Translate: Wir stellen uns kurz vor.", answer: ["We introduce ourselves briefly.", "We briefly introduce ourselves."], explanation: "stellen … vor is separable and uns refers back to wir." }),
  ]),
  ...withGroup("5 · Personal reflexive use", [
    ex({ id: "a136-41", type: "production", prompt: "Describe your morning with six reflexive actions.", model: "Ich wasche mich, dusche mich und ziehe mich an. Danach kämme ich mich. Vor der Arbeit beeile ich mich. Im Bus entspanne ich mich wieder.", explanation: "Match every pronoun to ich and place separable prefixes at the end." }),
    ex({ id: "a136-42", type: "production", prompt: "Rewrite five ich sentences for du.", model: "Ich wasche mich. → Du wäschst dich. · Ich ziehe mich an. → Du ziehst dich an. · Ich beeile mich. → Du beeilst dich.", explanation: "Change both the verb form and the reflexive pronoun." }),
    ex({ id: "a136-43", type: "production", prompt: "Write one sentence for every reflexive pronoun.", model: "Ich freue mich. Du setzt dich. Er wäscht sich. Wir treffen uns. Ihr beeilt euch. Sie interessieren sich.", explanation: "Recite the full pronoun chain through meaningful sentences." }),
    ex({ id: "a136-44", type: "production", prompt: "Create six questions about routines with reflexive verbs.", model: "Wann wäschst du dich? Wo ziehst du dich an? Musst du dich morgens beeilen? Worauf freust du dich? Wann trefft ihr euch? Setzen Sie sich hier?", explanation: "Keep subject and reflexive pronoun together after the finite verb." }),
    ex({ id: "a136-45", type: "production", prompt: "Write five pairs contrasting reflexive and non-reflexive objects.", model: "Ich wasche mich. / Ich wasche das Auto. · Sie zieht sich an. / Sie zieht das Kind an. · Er setzt sich. / Er setzt das Kind auf den Stuhl.", explanation: "Ask whether the action returns to the subject or affects someone else." }),
    ex({ id: "a136-46", type: "production", prompt: "Write a six-line getting-ready dialogue.", model: "Beeilst du dich? – Ja, ich ziehe mich gerade an. – Die Kinder waschen sich noch. – Dann müssen sie sich beeilen. – Treffen wir uns unten? – Ja.", explanation: "Use reflexive forms naturally across different subjects." }),
    ex({ id: "a136-47", type: "production", prompt: "Write five modal sentences with reflexive verbs.", model: "Ich muss mich beeilen. Du sollst dich ausruhen. Wir wollen uns treffen. Ihr könnt euch setzen. Sie möchten sich anmelden.", explanation: "Place the reflexive pronoun after the modal and the infinitive at the end." }),
    ex({ id: "a136-48", type: "production", prompt: "Describe what three people do before an event.", model: "Mia duscht sich und zieht sich an. Paul rasiert sich. Die Kinder waschen sich und beeilen sich. Danach treffen sie sich vor dem Haus.", explanation: "Third-person singular and plural both use sich; the verb shows number." }),
    ex({ id: "a136-49", type: "production", prompt: "Write an eight-sentence diary entry using at least six reflexive verbs.", model: "Heute fühle ich mich gut. Ich freue mich auf den Tag. Morgens beeile ich mich nicht. Nach der Arbeit treffe ich mich mit Lena. Wir unterhalten uns und entspannen uns im Park.", explanation: "A connected text develops reflexive word order beyond isolated drills." }),
    ex({ id: "a136-50", type: "production", prompt: "Record a one-minute routine, then underline every subject–pronoun pair.", model: "Ich stehe auf und wasche mich. Meine Kinder ziehen sich an. Wir setzen uns an den Tisch. Danach müssen wir uns beeilen. Vor der Schule verabschieden wir uns.", explanation: "Checking each pair prevents pronoun choice from becoming guesswork." }),
  ]),
];
