import type { GrammarExercise } from "@/app/grammar/course";

const TYPES = "1 · Question types";
const WORDS = "2 · Choosing question words";
const BUILD = "3 · Building questions";
const REPAIR = "4 · Answers, transformations, and errors";
const SPEAK = "5 · Translation and real communication";

export const A1_LESSON_FIVE_EXERCISES: GrammarExercise[] = [
  { id: "a115-01", group: TYPES, type: "choice", prompt: "Which pattern forms a neutral yes/no question?", options: ["subject + verb + rest", "verb + subject + rest", "W-word + subject + verb", "subject + rest + verb"], answer: "verb + subject + rest", explanation: "A yes/no question begins with the conjugated verb: Kommst du heute?" },
  { id: "a115-02", group: TYPES, type: "choice", prompt: "Which pattern forms a direct W-question?", options: ["W-word + verb + subject", "W-word + subject + verb", "verb + W-word + subject", "subject + verb + W-word"], answer: "W-word + verb + subject", explanation: "Use question word, conjugated verb, then subject: Wo wohnst du?" },
  { id: "a115-03", group: TYPES, type: "choice", prompt: "Which is a yes/no question?", options: ["Wo wohnst du?", "Wann beginnt der Kurs?", "Arbeitest du heute?", "Warum lernst du Deutsch?"], answer: "Arbeitest du heute?", explanation: "It begins with the verb and can be answered with ja or nein." },
  { id: "a115-04", group: TYPES, type: "choice", prompt: "Which is a W-question?", options: ["Hast du Zeit?", "Kommst du mit?", "Was machst du?", "Ist das richtig?"], answer: "Was machst du?", explanation: "Was asks for specific information." },
  { id: "a115-05", group: TYPES, type: "choice", prompt: "Which sentence asks about a person who performs the action?", options: ["Wen siehst du?", "Wer kommt heute?", "Was kommt heute?", "Wo kommt er?"], answer: "Wer kommt heute?", explanation: "Wer is the subject and is followed directly by the singular verb." },
  { id: "a115-06", group: TYPES, type: "choice", prompt: "Which question uses formal address?", options: ["Wo wohnst du?", "Wo wohnt ihr?", "Wo wohnen Sie?", "Wo wohnen sie?"], answer: "Wo wohnen Sie?", explanation: "Capitalised Sie and the -en verb form mark formal address." },
  { id: "a115-07", group: TYPES, type: "choice", prompt: "Choose the correctly punctuated question.", options: ["Wo wohnst du.", "Wo wohnst du?", "Wo? wohnst du", "Wo wohnst? du"], answer: "Wo wohnst du?", explanation: "A direct question ends with a question mark." },
  { id: "a115-08", group: TYPES, type: "choice", prompt: "Which question asks for a choice between alternatives?", options: ["Trinkst du Kaffee oder Tee?", "Warum trinkst du Tee?", "Wie trinkst du Tee?", "Wer trinkt Tee?"], answer: "Trinkst du Kaffee oder Tee?", explanation: "A verb-first question can present alternatives with oder." },
  { id: "a115-09", group: TYPES, type: "choice", prompt: "In Wer arbeitet heute?, what is Wer?", options: ["the subject", "the object", "the verb", "a time expression"], answer: "the subject", explanation: "Wer itself performs the action, so no separate subject follows." },
  { id: "a115-10", group: TYPES, type: "choice", prompt: "Which question asks about an object?", options: ["Wer kauft das Buch?", "Was kaufst du?", "Wo kaufst du ein?", "Wann kaufst du ein?"], answer: "Was kaufst du?", explanation: "Was asks which thing receives the action kaufen." },

  { id: "a115-11", group: WORDS, type: "choice", prompt: "___ wohnst du? — In Köln.", options: ["Wo", "Wohin", "Woher", "Wann"], answer: "Wo", explanation: "Wo asks for a location." },
  { id: "a115-12", group: WORDS, type: "choice", prompt: "___ fährst du? — Nach Berlin.", options: ["Wo", "Wohin", "Woher", "Wer"], answer: "Wohin", explanation: "Wohin asks for a destination or direction." },
  { id: "a115-13", group: WORDS, type: "choice", prompt: "___ kommst du? — Aus Indien.", options: ["Wo", "Wohin", "Woher", "Wie"], answer: "Woher", explanation: "Woher asks about origin." },
  { id: "a115-14", group: WORDS, type: "choice", prompt: "___ beginnt der Film? — Um acht Uhr.", options: ["Wann", "Wie lange", "Warum", "Wie oft"], answer: "Wann", explanation: "Wann asks at what time something happens." },
  { id: "a115-15", group: WORDS, type: "choice", prompt: "___ lernst du Deutsch? — Weil ich in Berlin arbeite.", options: ["Wie", "Warum", "Was", "Wer"], answer: "Warum", explanation: "Warum asks for a reason." },
  { id: "a115-16", group: WORDS, type: "choice", prompt: "___ kostet das Ticket? — 25 Euro.", options: ["Wie viel", "Wie viele", "Wie lange", "Wie alt"], answer: "Wie viel", explanation: "Wie viel asks for an amount or price." },
  { id: "a115-17", group: WORDS, type: "choice", prompt: "___ Personen kommen? — Sechs.", options: ["Wie viel", "Wie viele", "Wie", "Welche"], answer: "Wie viele", explanation: "Wie viele asks for the number of countable plural items or people." },
  { id: "a115-18", group: WORDS, type: "choice", prompt: "___ bleibst du in Hamburg? — Drei Tage.", options: ["Wie lange", "Wie oft", "Wann", "Wie spät"], answer: "Wie lange", explanation: "Wie lange asks about duration." },
  { id: "a115-19", group: WORDS, type: "choice", prompt: "___ gehst du schwimmen? — Zweimal pro Woche.", options: ["Wie lange", "Wie oft", "Wie viel", "Wann genau"], answer: "Wie oft", explanation: "Wie oft asks about frequency." },
  { id: "a115-20", group: WORDS, type: "choice", prompt: "___ Buch möchtest du? — Das rote.", options: ["Welches", "Wie", "Was", "Wessen"], answer: "Welches", explanation: "Welches asks the listener to choose a neuter noun from known options." },

  { id: "a115-21", group: BUILD, type: "fill", prompt: "___ du heute Abend Zeit? (haben)", answer: "Hast", explanation: "A yes/no question begins with the conjugated verb: Hast du …?" },
  { id: "a115-22", group: BUILD, type: "fill", prompt: "Wo ___ deine Schwester? (arbeiten)", answer: "arbeitet", explanation: "The W-word comes first, the verb second, and the subject follows." },
  { id: "a115-23", group: BUILD, type: "fill", prompt: "Warum ___ ihr Deutsch? (lernen)", answer: "lernt", explanation: "ihr takes lernt, placed immediately after Warum." },
  { id: "a115-24", group: BUILD, type: "fill", prompt: "___ Sie einen Termin? (brauchen)", answer: "Brauchen", explanation: "Formal Sie uses brauchen; verb-first order makes the yes/no question." },
  { id: "a115-25", group: BUILD, type: "order", prompt: "Ask where someone lives.", tokens: ["du", "Wo", "wohnst", "?"], answer: "Wo wohnst du?", explanation: "Use W-word + verb + subject." },
  { id: "a115-26", group: BUILD, type: "order", prompt: "Ask a yes/no question.", tokens: ["heute", "du", "Arbeitest", "?"], answer: "Arbeitest du heute?", explanation: "Begin with the conjugated verb, then place the subject." },
  { id: "a115-27", group: BUILD, type: "order", prompt: "Ask about the departure time.", tokens: ["der", "Wann", "fährt", "Zug", "?"], answer: "Wann fährt der Zug?", explanation: "Wann is first, fährt second, and the subject der Zug follows." },
  { id: "a115-28", group: BUILD, type: "order", prompt: "Ask politely about origin.", tokens: ["kommen", "Woher", "Sie", "?"], answer: "Woher kommen Sie?", explanation: "Formal Sie uses the -en form and follows the verb." },
  { id: "a115-29", group: BUILD, type: "order", prompt: "Ask who is coming today.", tokens: ["heute", "Wer", "kommt", "?"], answer: "Wer kommt heute?", explanation: "Wer is the subject, so the verb follows directly." },
  { id: "a115-30", group: BUILD, type: "order", prompt: "Ask what the person is reading.", tokens: ["du", "Was", "liest", "?"], answer: "Was liest du?", explanation: "Was is the object; the subject du still follows the verb." },

  { id: "a115-31", group: REPAIR, type: "correction", prompt: "Correct: Wo du wohnst?", answer: "Wo wohnst du?", explanation: "In a direct W-question, the verb must be second." },
  { id: "a115-32", group: REPAIR, type: "correction", prompt: "Correct: Du hast Zeit?", answer: "Hast du Zeit?", explanation: "A neutral yes/no question begins with the conjugated verb." },
  { id: "a115-33", group: REPAIR, type: "correction", prompt: "Correct: Wann der Kurs beginnt?", answer: "Wann beginnt der Kurs?", explanation: "The conjugated verb follows the question word." },
  { id: "a115-34", group: REPAIR, type: "correction", prompt: "Correct: Warum ihr lernt Deutsch?", answer: "Warum lernt ihr Deutsch?", explanation: "The correct order is W-word + verb + subject + rest." },
  { id: "a115-35", group: REPAIR, type: "correction", prompt: "Correct: Woher Sie kommen?", answer: "Woher kommen Sie?", explanation: "Formal Sie follows the conjugated verb in a direct question." },
  { id: "a115-36", group: REPAIR, type: "choice", prompt: "Make a question for the answer In München.", options: ["Wo wohnst du?", "Wohin fährst du?", "Woher kommst du?", "Wann wohnst du?"], answer: "Wo wohnst du?", explanation: "A city given as current location answers wo." },
  { id: "a115-37", group: REPAIR, type: "choice", prompt: "Make a question for the answer Morgen um zehn.", options: ["Wo beginnt der Kurs?", "Wann beginnt der Kurs?", "Wie beginnt der Kurs?", "Wer beginnt den Kurs?"], answer: "Wann beginnt der Kurs?", explanation: "A time answer requires wann." },
  { id: "a115-38", group: REPAIR, type: "fill", prompt: "Change to a yes/no question: Du sprichst Deutsch. → ___", answer: ["Sprichst du Deutsch?", "Sprichst du Deutsch"], explanation: "Move the conjugated verb before the subject." },
  { id: "a115-39", group: REPAIR, type: "fill", prompt: "Ask about the object: Du kaufst ein Buch. → ___", answer: ["Was kaufst du?", "Was kaufst du"], explanation: "Replace the object with was and keep verb–subject order after it." },
  { id: "a115-40", group: REPAIR, type: "fill", prompt: "Ask about the subject: Lara arbeitet heute. → ___", answer: ["Wer arbeitet heute?", "Wer arbeitet heute"], explanation: "Wer replaces the subject, so no additional subject is needed." },

  { id: "a115-41", group: SPEAK, type: "translation", direction: "en-de", prompt: "Translate: Do you live in Berlin? (informal singular)", answer: ["Wohnst du in Berlin?", "Wohnst du in Berlin"], explanation: "A yes/no question begins with wohnst, followed by du." },
  { id: "a115-42", group: SPEAK, type: "translation", direction: "en-de", prompt: "Translate: Where do you work? (formal)", answer: ["Wo arbeiten Sie?", "Wo arbeiten Sie"], explanation: "Use Wo + arbeiten + formal Sie." },
  { id: "a115-43", group: SPEAK, type: "translation", direction: "en-de", prompt: "Translate: Why is the train late?", answer: ["Warum ist der Zug spät?", "Warum ist der Zug spät"], explanation: "The form ist follows Warum, then the subject der Zug." },
  { id: "a115-44", group: SPEAK, type: "translation", direction: "en-de", prompt: "Translate: How much does the coffee cost?", answer: ["Wie viel kostet der Kaffee?", "Wie viel kostet der Kaffee"], explanation: "Wie viel asks the price; kostet occupies the verb position." },
  { id: "a115-45", group: SPEAK, type: "translation", direction: "de-en", prompt: "Translate: Wie oft besuchst du deine Familie?", answer: ["How often do you visit your family?", "How often are you visiting your family?"], explanation: "Wie oft asks about frequency." },
  { id: "a115-46", group: SPEAK, type: "translation", direction: "de-en", prompt: "Translate: Wohin fahren Sie morgen?", answer: ["Where are you going tomorrow?", "Where are you travelling tomorrow?"], explanation: "Wohin asks for the destination; Sie is formal you." },
  { id: "a115-47", group: SPEAK, type: "production", prompt: "Write five questions for a new classmate using wo, woher, was, warum, and wie oft.", model: "Wo wohnst du? Woher kommst du? Was machst du gern? Warum lernst du Deutsch? Wie oft übst du?", explanation: "Use W-word + conjugated verb + subject in each question." },
  { id: "a115-48", group: SPEAK, type: "production", prompt: "Write five polite questions for a hotel reception, shop, or office.", model: "Haben Sie ein Zimmer frei? Wie viel kostet es? Wann beginnt das Frühstück? Wo ist der Aufzug? Kann ich mit Karte zahlen?", explanation: "Use formal Sie and appropriate verb-first or W-question order." },
  { id: "a115-49", group: SPEAK, type: "production", prompt: "Write a six-line interview containing three yes/no and three W-questions.", model: "Kommen Sie aus Berlin? Wo wohnen Sie jetzt? Arbeiten Sie hier? Was machen Sie beruflich? Lernen Sie Deutsch? Warum lernen Sie es?", explanation: "Alternate the two question frames and keep formal Sie capitalised." },
  { id: "a115-50", group: SPEAK, type: "production", prompt: "Create eight questions that could guide a real conversation about someone's day.", model: "Wann stehst du auf? Trinkst du morgens Kaffee? Wie fährst du zur Arbeit? Wo isst du mittags? Arbeitest du am Nachmittag? Was machst du am Abend? Siehst du fern? Wann gehst du schlafen?", explanation: "Use varied question words and natural yes/no questions rather than repeating one frame." },
];
