import type { GrammarExercise } from "@/app/grammar/course";

const CHOICE = "1 · Choosing nicht or kein";
const FORMS = "2 · Forms of kein";
const POSITION = "3 · Position and focus";
const REPAIR = "4 · Building and correcting negatives";
const TRANSFER = "5 · Translation and production";

export const A1_LESSON_SIX_EXERCISES: GrammarExercise[] = [
  { id: "a116-01", group: CHOICE, type: "choice", prompt: "Which word normally negates an indefinite noun?", options: ["nicht", "kein", "nie", "nein"], answer: "kein", explanation: "kein replaces ein or a zero article: ein Auto → kein Auto." },
  { id: "a116-02", group: CHOICE, type: "choice", prompt: "Which word normally negates an adjective?", options: ["kein", "nicht", "keine", "neinen"], answer: "nicht", explanation: "Use nicht directly before an adjective: nicht teuer." },
  { id: "a116-03", group: CHOICE, type: "choice", prompt: "Choose the correct negative: Ich habe ___ Auto.", options: ["nicht", "kein", "keine", "keinen"], answer: "kein", explanation: "Auto is neuter and indefinite, so use kein Auto." },
  { id: "a116-04", group: CHOICE, type: "choice", prompt: "Choose the correct negative: Das Auto ist ___ neu.", options: ["kein", "keine", "nicht", "keinen"], answer: "nicht", explanation: "neu is an adjective, so it is negated with nicht." },
  { id: "a116-05", group: CHOICE, type: "choice", prompt: "Choose the correct negative: Das ist ___ mein Schlüssel.", options: ["kein", "keine", "nicht", "keinen"], answer: "nicht", explanation: "A noun with a possessive determiner is negated with nicht." },
  { id: "a116-06", group: CHOICE, type: "choice", prompt: "Choose the correct negative: Wir kaufen ___ Brot.", options: ["nicht", "kein", "keine", "keinen"], answer: "kein", explanation: "Brot is a neuter noun with no article, so use kein." },
  { id: "a116-07", group: CHOICE, type: "choice", prompt: "Choose the correct negative: Sie kommt heute ___.", options: ["kein", "keine", "nicht", "keinen"], answer: "nicht", explanation: "nicht negates the action kommen." },
  { id: "a116-08", group: CHOICE, type: "choice", prompt: "Choose the correct negative: Das ist ___ der Bus nach Bonn.", options: ["kein", "nicht", "keine", "keinen"], answer: "nicht", explanation: "A specific noun with a definite article is negated with nicht." },
  { id: "a116-09", group: CHOICE, type: "choice", prompt: "Choose the correct negative: Im Café gibt es ___ Milch.", options: ["nicht", "kein", "keine", "keinen"], answer: "keine", explanation: "Milch is feminine and has no article, so use keine." },
  { id: "a116-10", group: CHOICE, type: "choice", prompt: "Which sentence means I am not a teacher?", options: ["Ich bin nicht Lehrer.", "Ich bin kein Lehrer.", "Ich bin keinen Lehrer.", "Ich nicht bin Lehrer."], answer: "Ich bin kein Lehrer.", explanation: "A profession noun used as an indefinite identity is negated with kein." },

  { id: "a116-11", group: FORMS, type: "choice", prompt: "___ Mann wartet hier. (no)", options: ["Kein", "Keine", "Keinen", "Nicht"], answer: "Kein", explanation: "Mann is masculine nominative: kein Mann." },
  { id: "a116-12", group: FORMS, type: "choice", prompt: "___ Frau arbeitet heute. (no)", options: ["Kein", "Keine", "Keinen", "Nicht"], answer: "Keine", explanation: "Frau is feminine nominative: keine Frau." },
  { id: "a116-13", group: FORMS, type: "choice", prompt: "___ Kind spielt draußen. (no)", options: ["Kein", "Keine", "Keinen", "Nicht"], answer: "Kein", explanation: "Kind is neuter nominative: kein Kind." },
  { id: "a116-14", group: FORMS, type: "choice", prompt: "Hier sind ___ Gäste.", options: ["kein", "keine", "keinen", "nicht"], answer: "keine", explanation: "The plural form is keine Gäste." },
  { id: "a116-15", group: FORMS, type: "choice", prompt: "Ich sehe ___ Mann.", options: ["kein", "keine", "keinen", "nicht"], answer: "keinen", explanation: "Masculine accusative adds -en: keinen Mann." },
  { id: "a116-16", group: FORMS, type: "choice", prompt: "Wir brauchen ___ Termin.", options: ["kein", "keine", "keinen", "nicht"], answer: "keinen", explanation: "Termin is masculine accusative: keinen Termin." },
  { id: "a116-17", group: FORMS, type: "fill", prompt: "Mara trinkt ___ Kaffee.", answer: "keinen", explanation: "Kaffee is masculine and the direct object: keinen Kaffee." },
  { id: "a116-18", group: FORMS, type: "fill", prompt: "Ich habe ___ Zeit.", answer: "keine", explanation: "Zeit is feminine: keine Zeit." },
  { id: "a116-19", group: FORMS, type: "fill", prompt: "Das Hotel hat ___ freie Zimmer.", answer: "keine", explanation: "The plural accusative form is keine." },
  { id: "a116-20", group: FORMS, type: "choice", prompt: "Which sequence is correct?", options: ["kein–keine–kein–keine", "kein–kein–keine–keinen", "keine–kein–keinen–nicht", "kein–keinen–keine–kein"], answer: "kein–keine–kein–keine", explanation: "Nominative masculine, feminine, neuter, and plural are kein, keine, kein, keine." },

  { id: "a116-21", group: POSITION, type: "choice", prompt: "Choose the natural whole-sentence negation.", options: ["Ich arbeite nicht heute.", "Ich arbeite heute nicht.", "Nicht ich arbeite heute.", "Ich nicht arbeite heute."], answer: "Ich arbeite heute nicht.", explanation: "When nicht negates the whole action, it often stands near the end." },
  { id: "a116-22", group: POSITION, type: "choice", prompt: "Choose the sentence that means not today, but tomorrow.", options: ["Ich komme heute nicht.", "Ich komme nicht heute, sondern morgen.", "Nicht ich komme heute.", "Ich nicht komme morgen."], answer: "Ich komme nicht heute, sondern morgen.", explanation: "Put nicht directly before the specifically contrasted time element." },
  { id: "a116-23", group: POSITION, type: "choice", prompt: "Choose the correct adjective negation.", options: ["Der Film ist langweilig nicht.", "Der Film nicht ist langweilig.", "Der Film ist nicht langweilig.", "Der Film ist kein langweilig."], answer: "Der Film ist nicht langweilig.", explanation: "nicht stands directly before the adjective it negates." },
  { id: "a116-24", group: POSITION, type: "choice", prompt: "Choose the sentence that contrasts Berlin with Hamburg.", options: ["Sie wohnt in Berlin nicht.", "Sie wohnt nicht in Berlin, sondern in Hamburg.", "Nicht sie wohnt in Berlin.", "Sie nicht wohnt in Hamburg."], answer: "Sie wohnt nicht in Berlin, sondern in Hamburg.", explanation: "Place nicht before the place phrase being corrected." },
  { id: "a116-25", group: POSITION, type: "fill", prompt: "Das Essen ist ___ warm.", answer: "nicht", explanation: "nicht immediately precedes the adjective warm." },
  { id: "a116-26", group: POSITION, type: "fill", prompt: "Wir fahren morgen ___.", answer: "nicht", explanation: "At the end, nicht negates the planned action as a whole." },
  { id: "a116-27", group: POSITION, type: "choice", prompt: "Which sentence means I am not buying the red jacket (but perhaps another one)?", options: ["Ich kaufe die rote Jacke nicht.", "Ich kaufe nicht die rote Jacke.", "Ich kaufe keine rote Jacke.", "Nicht ich kaufe die rote Jacke."], answer: "Ich kaufe nicht die rote Jacke.", explanation: "nicht immediately before the definite noun phrase creates contrastive focus." },
  { id: "a116-28", group: POSITION, type: "choice", prompt: "Which sentence means I am buying no red jacket at all?", options: ["Ich kaufe die rote Jacke nicht.", "Ich kaufe nicht die rote Jacke.", "Ich kaufe keine rote Jacke.", "Ich keine rote Jacke kaufe."], answer: "Ich kaufe keine rote Jacke.", explanation: "keine negates the entire indefinite noun phrase." },
  { id: "a116-29", group: POSITION, type: "fill", prompt: "Das ist ___ der richtige Schlüssel.", answer: "nicht", explanation: "A noun phrase with the definite article der takes nicht." },
  { id: "a116-30", group: POSITION, type: "choice", prompt: "Choose the natural negative with a separable verb.", options: ["Ich kaufe heute nicht ein.", "Ich kaufe heute ein nicht.", "Ich nicht kaufe heute ein.", "Ich kaufe kein heute ein."], answer: "Ich kaufe heute nicht ein.", explanation: "nicht comes before the separated prefix when it negates the whole activity." },

  { id: "a116-31", group: REPAIR, type: "order", prompt: "Build the negative sentence.", tokens: ["heute", "arbeitet", "nicht", "Er", "."], answer: "Er arbeitet heute nicht.", explanation: "Subject and verb begin the clause; whole-action nicht stands near the end." },
  { id: "a116-32", group: REPAIR, type: "order", prompt: "Build the noun negation.", tokens: ["Auto", "kein", "Ich", "habe", "."], answer: "Ich habe kein Auto.", explanation: "kein directly introduces the neuter noun Auto." },
  { id: "a116-33", group: REPAIR, type: "order", prompt: "Build the contrast.", tokens: ["sondern", "heute", "Wir", "morgen", "kommen", "nicht", ",", "."], answer: "Wir kommen nicht heute, sondern morgen.", explanation: "nicht precedes the contrasted item; sondern introduces the correction." },
  { id: "a116-34", group: REPAIR, type: "correction", prompt: "Correct: Sie kauft nicht Brot.", answer: "Sie kauft kein Brot.", explanation: "An indefinite neuter noun is negated with kein." },
  { id: "a116-35", group: REPAIR, type: "correction", prompt: "Correct: Das ist kein mein Fahrrad.", answer: "Das ist nicht mein Fahrrad.", explanation: "A noun with a possessive determiner uses nicht." },
  { id: "a116-36", group: REPAIR, type: "correction", prompt: "Correct: Ich habe kein Bruder.", answer: "Ich habe keinen Bruder.", explanation: "Bruder is masculine accusative, so kein becomes keinen." },
  { id: "a116-37", group: REPAIR, type: "correction", prompt: "Correct: Der Kaffee ist kein heiß.", answer: "Der Kaffee ist nicht heiß.", explanation: "Adjectives are negated with nicht." },
  { id: "a116-38", group: REPAIR, type: "correction", prompt: "Correct: Wir nicht wohnen in Köln.", answer: "Wir wohnen nicht in Köln.", explanation: "The conjugated verb remains in position two; nicht follows later." },
  { id: "a116-39", group: REPAIR, type: "fill", prompt: "Make negative: Ich trinke einen Kaffee. → ___", answer: ["Ich trinke keinen Kaffee.", "Ich trinke keinen Kaffee"], explanation: "Masculine accusative einen changes to keinen." },
  { id: "a116-40", group: REPAIR, type: "fill", prompt: "Make negative: Das Hotel ist teuer. → ___", answer: ["Das Hotel ist nicht teuer.", "Das Hotel ist nicht teuer"], explanation: "Use nicht before the adjective teuer." },

  { id: "a116-41", group: TRANSFER, type: "translation", direction: "en-de", prompt: "Translate: I do not have a car.", answer: ["Ich habe kein Auto.", "Ich habe kein Auto"], explanation: "Auto is a neuter indefinite noun: kein Auto." },
  { id: "a116-42", group: TRANSFER, type: "translation", direction: "en-de", prompt: "Translate: She does not drink coffee.", answer: ["Sie trinkt keinen Kaffee.", "Sie trinkt keinen Kaffee"], explanation: "Kaffee is a masculine accusative noun: keinen Kaffee." },
  { id: "a116-43", group: TRANSFER, type: "translation", direction: "en-de", prompt: "Translate: The room is not large.", answer: ["Das Zimmer ist nicht groß.", "Das Zimmer ist nicht groß"], explanation: "Use nicht directly before the adjective groß." },
  { id: "a116-44", group: TRANSFER, type: "translation", direction: "en-de", prompt: "Translate: We are not coming today.", answer: ["Wir kommen heute nicht.", "Wir kommen heute nicht"], explanation: "Final nicht negates the complete action." },
  { id: "a116-45", group: TRANSFER, type: "translation", direction: "de-en", prompt: "Translate: Das ist nicht meine Tasche.", answer: ["That is not my bag.", "This is not my bag."], explanation: "nicht negates the noun phrase with the possessive meine." },
  { id: "a116-46", group: TRANSFER, type: "translation", direction: "de-en", prompt: "Translate: Wir brauchen keine Tickets.", answer: ["We do not need any tickets.", "We need no tickets."], explanation: "keine negates the plural noun Tickets." },
  { id: "a116-47", group: TRANSFER, type: "production", prompt: "Write five true negative sentences using kein, keine, keinen, and nicht.", model: "Ich habe kein Auto. Ich trinke keine Milch. Ich brauche keinen Termin. Das Zimmer ist nicht groß. Ich arbeite heute nicht.", explanation: "Choose the negative word from what is being negated, then check gender and case." },
  { id: "a116-48", group: TRANSFER, type: "production", prompt: "Correct five assumptions about yourself using nicht … sondern.", model: "Ich wohne nicht in Berlin, sondern in Bonn. Ich arbeite nicht am Samstag, sondern am Montag. Ich trinke nicht Kaffee, sondern Tee.", explanation: "Place nicht directly before the incorrect element and sondern before the correction." },
  { id: "a116-49", group: TRANSFER, type: "production", prompt: "Describe what is missing from an empty apartment in six sentences.", model: "Die Wohnung hat keine Möbel. Es gibt keinen Tisch und keine Stühle. Die Küche hat keinen Kühlschrank. Im Schlafzimmer steht kein Bett. Auch Lampen gibt es nicht.", explanation: "Use kein- forms for absent nouns and nicht for the broader final statement." },
  { id: "a116-50", group: TRANSFER, type: "production", prompt: "Write an eight-line dialogue in which a customer rejects choices and explains what they do not want.", model: "Möchten Sie Kaffee? Nein, ich trinke keinen Kaffee. Möchten Sie Tee? Ja, aber nicht schwarzen Tee. Haben Sie grünen Tee? Leider haben wir keinen grünen Tee. Dann nehme ich keine heiße, sondern eine kalte Schokolade. Gern.", explanation: "Combine noun negation, adjective focus, and contrastive nicht … sondern naturally." },
];
