import type { GrammarExercise } from "@/app/grammar/course";

const withGroup = (group: string, items: GrammarExercise[]) => items.map((item) => ({ ...item, group }));
const ex = (item: GrammarExercise) => item;

export const A1_LESSON_FIFTEEN_EXERCISES: GrammarExercise[] = [
  ...withGroup("1 · Choosing the imperative", [
    ex({ id: "a133-01", type: "choice", prompt: "Which form addresses one familiar person?", options: ["Komm!", "Kommt!", "Kommen Sie!", "Kommen wir!"], answer: "Komm!", explanation: "The du imperative normally uses the verb stem without du." }),
    ex({ id: "a133-02", type: "choice", prompt: "Which form addresses several familiar people?", options: ["Wartet!", "Warte!", "Warten Sie!", "Wartest!"], answer: "Wartet!", explanation: "The ihr imperative is the normal ihr verb form without the pronoun." }),
    ex({ id: "a133-03", type: "choice", prompt: "Which form is polite or formal?", options: ["Setzen Sie sich!", "Setz dich!", "Setzt euch!", "Sitzt!"], answer: "Setzen Sie sich!", explanation: "The formal imperative uses infinitive + Sie." }),
    ex({ id: "a133-04", type: "choice", prompt: "Choose the du imperative of lesen.", options: ["Lies!", "Les!", "Lest!", "Lesen Sie!"], answer: "Lies!", explanation: "lesen keeps its stem change in the du imperative: lies." }),
    ex({ id: "a133-05", type: "choice", prompt: "Choose the du imperative of nehmen.", options: ["Nimm!", "Nehm!", "Nehmt!", "Nehmen Sie!"], answer: "Nimm!", explanation: "nehmen forms the irregular du imperative nimm." }),
    ex({ id: "a133-06", type: "choice", prompt: "Choose the du imperative of arbeiten.", options: ["Arbeite!", "Arbeit!", "Arbeitet!", "Arbeiten Sie!"], answer: "Arbeite!", explanation: "Stems ending in -t normally add -e for pronunciation." }),
    ex({ id: "a133-07", type: "choice", prompt: "Choose the du imperative of sein.", options: ["Sei!", "Bist!", "Seid!", "Seien Sie!"], answer: "Sei!", explanation: "sein has the special singular imperative sei." }),
    ex({ id: "a133-08", type: "choice", prompt: "Which command means Please come in?", options: ["Kommen Sie bitte herein!", "Sie kommen bitte herein!", "Kommst du herein?", "Herein Sie kommen!"], answer: "Kommen Sie bitte herein!", explanation: "The formal imperative starts with the infinitive and includes Sie." }),
    ex({ id: "a133-09", type: "choice", prompt: "Where does the prefix go in Ruf mich an!?", options: ["at the end", "before ruf", "after mich but joined", "it disappears"], answer: "at the end", explanation: "A separable verb also separates in an imperative." }),
    ex({ id: "a133-10", type: "choice", prompt: "Which word makes a command friendlier?", options: ["bitte", "nicht", "sehr", "auch"], answer: "bitte", explanation: "bitte softens a request and can stand in several positions." }),
  ]),
  ...withGroup("2 · Form the command", [
    ex({ id: "a133-11", type: "fill", prompt: "___ bitte langsam! (sprechen, du)", answer: "Sprich", explanation: "sprechen keeps its e→i change: sprich." }),
    ex({ id: "a133-12", type: "fill", prompt: "___ hier! (warten, ihr)", answer: "Wartet", explanation: "Use the ihr form wartet without ihr." }),
    ex({ id: "a133-13", type: "fill", prompt: "___ bitte das Formular aus! (füllen, Sie)", answer: "Füllen Sie", explanation: "Formal commands use infinitive + Sie." }),
    ex({ id: "a133-14", type: "fill", prompt: "___ die Tür zu! (machen, du)", answer: "Mach", explanation: "The du form uses the stem mach; zu is separated." }),
    ex({ id: "a133-15", type: "fill", prompt: "___ vorsichtig! (sein, du)", answer: "Sei", explanation: "The singular imperative of sein is sei." }),
    ex({ id: "a133-16", type: "fill", prompt: "___ leise! (sein, ihr)", answer: "Seid", explanation: "The plural familiar imperative of sein is seid." }),
    ex({ id: "a133-17", type: "fill", prompt: "___ Sie bitte pünktlich! (sein)", answer: "Seien", explanation: "The formal imperative of sein is Seien Sie." }),
    ex({ id: "a133-18", type: "fill", prompt: "___ deine Medikamente! (nehmen, du)", answer: "Nimm", explanation: "nehmen forms nimm in the du imperative." }),
    ex({ id: "a133-19", type: "fill", prompt: "___ mich heute Abend ___! (anrufen, du)", answer: "Ruf an", explanation: "anrufen splits as Ruf … an!" }),
    ex({ id: "a133-20", type: "fill", prompt: "___ euch bitte! (setzen, ihr)", answer: "Setzt", explanation: "The ihr imperative is Setzt euch!" }),
  ]),
  ...withGroup("3 · Build and correct", [
    ex({ id: "a133-21", type: "order", prompt: "Build the friendly command.", tokens: ["bitte", "Komm", "rein", "!"], answer: "Komm bitte rein!", explanation: "The du imperative starts with Komm and the prefix rein closes the command." }),
    ex({ id: "a133-22", type: "order", prompt: "Build the ihr command.", tokens: ["langsam", "Sprecht", "bitte", "!"], answer: "Sprecht bitte langsam!", explanation: "Sprecht is the present ihr form without ihr." }),
    ex({ id: "a133-23", type: "order", prompt: "Build the formal request.", tokens: ["Sie", "hier", "Warten", "bitte", "!"], answer: "Warten Sie bitte hier!", explanation: "Formal commands use infinitive + Sie." }),
    ex({ id: "a133-24", type: "order", prompt: "Build the negative command.", tokens: ["nicht", "Vergiss", "Schlüssel", "den", "!"], answer: "Vergiss den Schlüssel nicht!", explanation: "nicht comes after the object in this whole-action negation." }),
    ex({ id: "a133-25", type: "order", prompt: "Build the reflexive formal command.", tokens: ["Sie", "Setzen", "bitte", "sich", "!"], answer: "Setzen Sie sich bitte!", explanation: "The formal reflexive pronoun is sich." }),
    ex({ id: "a133-26", type: "correction", prompt: "Correct: Du komm bitte herein!", answer: "Komm bitte herein!", explanation: "The subject du is normally omitted." }),
    ex({ id: "a133-27", type: "correction", prompt: "Correct: Ihr wartet hier!", answer: "Wartet hier!", explanation: "The pronoun ihr is omitted, but its verb ending remains." }),
    ex({ id: "a133-28", type: "correction", prompt: "Correct formally: Sitzen bitte Sie hier!", answer: "Sitzen Sie bitte hier!", explanation: "The formal order is infinitive + Sie." }),
    ex({ id: "a133-29", type: "correction", prompt: "Correct: Les den Text!", answer: "Lies den Text!", explanation: "lesen has the irregular du imperative lies." }),
    ex({ id: "a133-30", type: "correction", prompt: "Correct: Ruf an mich morgen!", answer: "Ruf mich morgen an!", explanation: "The separated prefix belongs at the end." }),
  ]),
  ...withGroup("4 · Translation", [
    ex({ id: "a133-31", type: "translation", direction: "en-de", prompt: "Translate informally: Come in! (one person)", answer: ["Komm rein!", "Komm herein!"], explanation: "Use the du imperative Komm and a final prefix." }),
    ex({ id: "a133-32", type: "translation", direction: "en-de", prompt: "Translate informally: Wait here! (several people)", answer: ["Wartet hier!", "Wartet hier"], explanation: "Use the ihr form wartet without the pronoun." }),
    ex({ id: "a133-33", type: "translation", direction: "en-de", prompt: "Translate formally: Please sign here.", answer: ["Unterschreiben Sie bitte hier!", "Bitte unterschreiben Sie hier!"], explanation: "The formal imperative uses infinitive + Sie." }),
    ex({ id: "a133-34", type: "translation", direction: "en-de", prompt: "Translate informally: Read the email! (one person)", answer: ["Lies die E-Mail!", "Lies die Mail!"], explanation: "lesen forms the command lies." }),
    ex({ id: "a133-35", type: "translation", direction: "en-de", prompt: "Translate informally: Don't forget your passport!", answer: ["Vergiss deinen Pass nicht!", "Vergiss den Pass nicht!"], explanation: "vergessen forms vergiss; nicht negates the command." }),
    ex({ id: "a133-36", type: "translation", direction: "de-en", prompt: "Translate: Mach bitte das Fenster zu!", answer: ["Please close the window.", "Close the window, please."], explanation: "mach … zu is the du imperative of zumachen." }),
    ex({ id: "a133-37", type: "translation", direction: "de-en", prompt: "Translate: Seid vorsichtig!", answer: ["Be careful!", "You all be careful!"], explanation: "seid addresses several familiar people." }),
    ex({ id: "a133-38", type: "translation", direction: "de-en", prompt: "Translate: Nehmen Sie zweimal täglich eine Tablette.", answer: ["Take one tablet twice daily.", "Take a tablet twice a day."], explanation: "Nehmen Sie is a formal instruction." }),
    ex({ id: "a133-39", type: "translation", direction: "de-en", prompt: "Translate: Ruf mich später an!", answer: ["Call me later!", "Phone me later!"], explanation: "ruf … an is a familiar singular command." }),
    ex({ id: "a133-40", type: "translation", direction: "de-en", prompt: "Translate: Setzt euch bitte.", answer: ["Please sit down.", "Sit down, please."], explanation: "setzt euch addresses several familiar people." }),
  ]),
  ...withGroup("5 · Practical instructions", [
    ex({ id: "a133-41", type: "production", prompt: "Write five friendly classroom instructions for one learner.", model: "Öffne das Buch. Lies den Text. Schreib die Antworten. Sprich bitte langsam. Frag mich bei Problemen.", explanation: "Use du imperatives and add bitte where it sounds natural." }),
    ex({ id: "a133-42", type: "production", prompt: "Rewrite five du commands for an ihr group.", model: "Komm! → Kommt! · Lies! → Lest! · Nimm! → Nehmt! · Sei leise! → Seid leise! · Setz dich! → Setzt euch!", explanation: "Use the normal ihr form without the pronoun and adjust reflexive pronouns." }),
    ex({ id: "a133-43", type: "production", prompt: "Rewrite five informal commands as formal requests.", model: "Warte hier! → Warten Sie bitte hier! · Lies das! → Lesen Sie das bitte! · Ruf an! → Rufen Sie bitte an!", explanation: "Use infinitive + Sie and add bitte for politeness." }),
    ex({ id: "a133-44", type: "production", prompt: "Write six instructions for using a ticket machine.", model: "Wählen Sie zuerst die Sprache. Drücken Sie auf Start. Wählen Sie Ihr Ziel. Bezahlen Sie mit Karte. Nehmen Sie die Fahrkarte. Vergessen Sie Ihre Karte nicht.", explanation: "Formal imperatives suit public instructions." }),
    ex({ id: "a133-45", type: "production", prompt: "Give six directions through a building.", model: "Gehen Sie geradeaus. Nehmen Sie die Treppe. Gehen Sie in den zweiten Stock. Biegen Sie links ab. Warten Sie vor Zimmer zwölf. Klopfen Sie bitte.", explanation: "Use clear formal commands and separable prefixes correctly." }),
    ex({ id: "a133-46", type: "production", prompt: "Write five positive and five negative health instructions.", model: "Trink viel Wasser. Schlaf genug. Nimm die Tabletten. Rauch nicht. Trink keinen Alkohol. Arbeite heute nicht.", explanation: "Use nicht for actions and kein for negating nouns." }),
    ex({ id: "a133-47", type: "production", prompt: "Create a six-line parent-and-child dialogue with commands and responses.", model: "Räum bitte dein Zimmer auf. – Gleich. Mach zuerst das Fenster auf. – Okay. Und vergiss die Bücher nicht. – Ich mache es jetzt.", explanation: "Soften everyday commands with bitte, mal, or context." }),
    ex({ id: "a133-48", type: "production", prompt: "Write a short recipe with eight imperative steps.", model: "Waschen Sie das Gemüse. Schneiden Sie die Tomaten. Geben Sie alles in eine Schüssel. Fügen Sie Salz hinzu. Mischen Sie den Salat. Servieren Sie ihn sofort.", explanation: "A recipe naturally practises a consistent command form." }),
    ex({ id: "a133-49", type: "production", prompt: "Write emergency instructions for du, ihr, and Sie.", model: "Du: Ruf sofort die Polizei an! · Ihr: Bleibt hier und wartet! · Sie: Verlassen Sie bitte das Gebäude und benutzen Sie den Aufzug nicht!", explanation: "Match the command form precisely to the audience." }),
    ex({ id: "a133-50", type: "production", prompt: "Record one minute of clear instructions for a daily task.", model: "Mach zuerst den Computer an. Öffne das Programm. Gib dein Passwort ein. Wähle die Datei aus. Speichere sie. Mach am Ende den Computer aus.", explanation: "Sequencing a real process turns imperative forms into usable language." }),
  ]),
];

export const A1_LESSON_SIXTEEN_EXERCISES: GrammarExercise[] = [
  ...withGroup("1 · mögen, gern, or möchten", [
    ex({ id: "a134-01", type: "choice", prompt: "Choose: Ich ___ Kaffee. (I like coffee.)", options: ["mag", "möchte", "gern", "will"], answer: "mag", explanation: "mögen normally takes a noun object: Ich mag Kaffee." }),
    ex({ id: "a134-02", type: "choice", prompt: "Choose: Ich trinke ___ Kaffee. (I like drinking coffee.)", options: ["gern", "mag", "möchte", "gerne zu"], answer: "gern", explanation: "gern modifies an activity verb." }),
    ex({ id: "a134-03", type: "choice", prompt: "Choose the polite order: ___ einen Kaffee, bitte.", options: ["Ich möchte", "Ich mag", "Ich kann", "Ich soll"], answer: "Ich möchte", explanation: "möchte expresses a polite present wish." }),
    ex({ id: "a134-04", type: "choice", prompt: "Choose the correct form: Du ___ Pizza.", options: ["magst", "mag", "mögt", "mögen"], answer: "magst", explanation: "The du form of mögen is magst." }),
    ex({ id: "a134-05", type: "choice", prompt: "Choose the correct form: Wir ___ heute kochen.", options: ["möchten", "möchtet", "möchte", "mag"], answer: "möchten", explanation: "The wir form is möchten; kochen stays at the end." }),
    ex({ id: "a134-06", type: "choice", prompt: "Which question is most polite in a café?", options: ["Was möchten Sie?", "Was wollen Sie?", "Was mögen Sie machen?", "Was müssen Sie?"], answer: "Was möchten Sie?", explanation: "möchten is standard for polite service encounters." }),
    ex({ id: "a134-07", type: "choice", prompt: "Which sentence asks about a general preference?", options: ["Magst du Tee?", "Möchtest du jetzt Tee?", "Du musst Tee trinken.", "Trink Tee!"], answer: "Magst du Tee?", explanation: "mögen asks whether someone generally likes something." }),
    ex({ id: "a134-08", type: "choice", prompt: "Which sentence offers something now?", options: ["Möchtest du einen Tee?", "Magst du Tee?", "Du trinkst gern Tee.", "Du willst Tee."], answer: "Möchtest du einen Tee?", explanation: "möchten asks about a present wish." }),
    ex({ id: "a134-09", type: "choice", prompt: "Choose the natural sentence for a hobby.", options: ["Ich lese gern.", "Ich mag lesen gern.", "Ich möchte lesen immer.", "Ich gern lese."], answer: "Ich lese gern.", explanation: "Use activity verb + gern for something you enjoy doing." }),
    ex({ id: "a134-10", type: "choice", prompt: "Which form addresses formal Sie?", options: ["Sie möchten", "Sie möchtet", "Sie möchtest", "Sie möchte"], answer: "Sie möchten", explanation: "Formal Sie takes the plural form möchten." }),
  ]),
  ...withGroup("2 · Forms in context", [
    ex({ id: "a134-11", type: "fill", prompt: "Ich ___ Schokolade. (mögen)", answer: "mag", explanation: "The ich form of mögen is mag." }),
    ex({ id: "a134-12", type: "fill", prompt: "___ du italienisches Essen? (mögen)", answer: "Magst", explanation: "The du question begins with Magst." }),
    ex({ id: "a134-13", type: "fill", prompt: "Er ___ keine laute Musik. (mögen)", answer: "mag", explanation: "The third-person singular is mag." }),
    ex({ id: "a134-14", type: "fill", prompt: "Ihr ___ diesen Film. (mögen)", answer: "mögt", explanation: "The ihr form is mögt." }),
    ex({ id: "a134-15", type: "fill", prompt: "Ich ___ bitte zahlen. (möchten)", answer: "möchte", explanation: "Ich möchte … is a polite wish; zahlen stays infinitive." }),
    ex({ id: "a134-16", type: "fill", prompt: "Was ___ du trinken? (möchten)", answer: "möchtest", explanation: "The du form is möchtest." }),
    ex({ id: "a134-17", type: "fill", prompt: "Mia ___ heute zu Hause bleiben. (möchten)", answer: "möchte", explanation: "Mia takes möchte and the infinitive goes last." }),
    ex({ id: "a134-18", type: "fill", prompt: "Wir ___ zwei Fahrkarten. (möchten)", answer: "möchten", explanation: "Wir möchten can take a noun object directly." }),
    ex({ id: "a134-19", type: "fill", prompt: "Ich spiele ___ Tennis. (like doing)", answer: "gern", explanation: "gern expresses enjoyment of the activity spielen." }),
    ex({ id: "a134-20", type: "fill", prompt: "Sie hört nicht ___ laute Musik. (like doing)", answer: "gern", explanation: "nicht gern means not liking an activity." }),
  ]),
  ...withGroup("3 · Contrast and word order", [
    ex({ id: "a134-21", type: "order", prompt: "Build the preference.", tokens: ["Kaffee", "Ich", "mag", "."], answer: "Ich mag Kaffee.", explanation: "mögen is conjugated like the only verb and takes a noun object." }),
    ex({ id: "a134-22", type: "order", prompt: "Build the hobby sentence.", tokens: ["gern", "liest", "Mia", "."], answer: "Mia liest gern.", explanation: "gern follows the activity verb phrase." }),
    ex({ id: "a134-23", type: "order", prompt: "Build the polite wish.", tokens: ["zahlen", "Ich", "möchte", "bitte", "."], answer: "Ich möchte bitte zahlen.", explanation: "möchte is second and zahlen is final." }),
    ex({ id: "a134-24", type: "order", prompt: "Build the offer.", tokens: ["einen", "Möchtest", "Tee", "du", "?"], answer: "Möchtest du einen Tee?", explanation: "A yes/no question begins with Möchtest." }),
    ex({ id: "a134-25", type: "order", prompt: "Build the formal restaurant question.", tokens: ["Sie", "Was", "bestellen", "möchten", "?"], answer: "Was möchten Sie bestellen?", explanation: "The W-word comes first, möchten second, and bestellen last." }),
    ex({ id: "a134-26", type: "correction", prompt: "Correct: Ich möge Kaffee.", answer: "Ich mag Kaffee.", explanation: "The present ich form is mag." }),
    ex({ id: "a134-27", type: "correction", prompt: "Correct: Du magst schwimmen gern.", answer: "Du schwimmst gern.", explanation: "Use the activity verb with gern for an activity preference." }),
    ex({ id: "a134-28", type: "correction", prompt: "Correct: Ich möchte bestelle eine Suppe.", answer: "Ich möchte eine Suppe bestellen.", explanation: "The second verb is a final infinitive." }),
    ex({ id: "a134-29", type: "correction", prompt: "Correct: Mögen Sie jetzt einen Kaffee? (offer)", answer: "Möchten Sie jetzt einen Kaffee?", explanation: "An offer about a present wish uses möchten." }),
    ex({ id: "a134-30", type: "correction", prompt: "Correct: Wir möchtet nach Berlin fahren.", answer: "Wir möchten nach Berlin fahren.", explanation: "The wir form is möchten." }),
  ]),
  ...withGroup("4 · Translation", [
    ex({ id: "a134-31", type: "translation", direction: "en-de", prompt: "Translate: I like tea.", answer: ["Ich mag Tee.", "Ich mag Tee"], explanation: "Use mögen with the noun Tee." }),
    ex({ id: "a134-32", type: "translation", direction: "en-de", prompt: "Translate: I like cooking.", answer: ["Ich koche gern.", "Ich koche gerne."], explanation: "Use kochen + gern for an activity preference." }),
    ex({ id: "a134-33", type: "translation", direction: "en-de", prompt: "Translate: I would like a coffee, please.", answer: ["Ich möchte einen Kaffee, bitte.", "Ich möchte bitte einen Kaffee."], explanation: "möchte makes the order polite; Kaffee is masculine accusative." }),
    ex({ id: "a134-34", type: "translation", direction: "en-de", prompt: "Translate: Would you like to come with us? (informal)", answer: ["Möchtest du mitkommen?", "Möchtest du mit uns kommen?"], explanation: "möchtest opens the question; mitkommen is final." }),
    ex({ id: "a134-35", type: "translation", direction: "en-de", prompt: "Translate formally: What would you like to drink?", answer: ["Was möchten Sie trinken?", "Was möchten Sie gern trinken?"], explanation: "Formal Sie takes möchten." }),
    ex({ id: "a134-36", type: "translation", direction: "de-en", prompt: "Translate: Magst du deutsche Musik?", answer: ["Do you like German music?"], explanation: "mögen asks about a general preference." }),
    ex({ id: "a134-37", type: "translation", direction: "de-en", prompt: "Translate: Meine Eltern reisen gern.", answer: ["My parents like travelling.", "My parents like to travel."], explanation: "reisen + gern expresses enjoyment of the activity." }),
    ex({ id: "a134-38", type: "translation", direction: "de-en", prompt: "Translate: Wir möchten morgen früher gehen.", answer: ["We would like to leave earlier tomorrow."], explanation: "möchten expresses a polite or softened plan." }),
    ex({ id: "a134-39", type: "translation", direction: "de-en", prompt: "Translate: Möchtet ihr noch etwas essen?", answer: ["Would you like to eat something else?", "Would you all like something more to eat?"], explanation: "möchtet agrees with ihr." }),
    ex({ id: "a134-40", type: "translation", direction: "de-en", prompt: "Translate: Er mag keinen Fisch.", answer: ["He does not like fish.", "He likes no fish."], explanation: "kein negates the noun Fisch." }),
  ]),
  ...withGroup("5 · Preferences and polite wishes", [
    ex({ id: "a134-41", type: "production", prompt: "Write five things you like and five you do not like with mögen.", model: "Ich mag Kaffee, Bücher, Hunde, kleine Städte und ruhige Musik. Ich mag keinen Fisch, keinen Lärm, keine Hitze, keine langen Meetings und keine Horrorfilme.", explanation: "Use correct accusative kein forms with noun preferences." }),
    ex({ id: "a134-42", type: "production", prompt: "Write eight activity preferences with gern, lieber, or nicht gern.", model: "Ich lese gern. Ich schwimme sehr gern. Ich koche lieber zu Hause. Ich fahre nicht gern nachts. Am liebsten wandere ich.", explanation: "Use gern with the conjugated activity verb, not as a verb itself." }),
    ex({ id: "a134-43", type: "production", prompt: "Create a six-line café dialogue with möchten.", model: "Was möchten Sie? – Ich möchte einen Tee. – Möchten Sie auch etwas essen? – Ja, ich möchte einen Kuchen. – Sonst noch etwas? – Nein, danke.", explanation: "Use möchten for both offers and polite orders." }),
    ex({ id: "a134-44", type: "production", prompt: "Write five pairs contrasting general likes and present wishes.", model: "Ich mag Kaffee. Jetzt möchte ich einen Tee. · Sie mag italienisches Essen. Heute möchte sie eine Suppe kochen.", explanation: "mögen describes a general preference; möchten points to a wish in the situation." }),
    ex({ id: "a134-45", type: "production", prompt: "Plan a restaurant order for four people in six sentences.", model: "Ich möchte die Suppe. Mia möchte einen Salat bestellen. Tom mag keinen Fisch und möchte die Pasta. Die Kinder möchten Pommes. Wir möchten Wasser trinken.", explanation: "Combine food preferences, polite wishes, and accusative objects." }),
    ex({ id: "a134-46", type: "production", prompt: "Ask and answer six preference questions.", model: "Magst du Tee? – Ja, sehr. Kochst du gern? – Nein, ich backe lieber. Möchtest du jetzt etwas essen? – Ja, gern.", explanation: "Choose Magst du …? for general preference and Möchtest du …? for a current wish." }),
    ex({ id: "a134-47", type: "production", prompt: "Write a short profile using mögen and gern without repeating the same structure.", model: "Lena mag Musik und kleine Cafés. Sie liest gern und trifft am Wochenende gern Freunde. Sport mag sie nicht, aber sie geht gern spazieren. Heute möchte sie ein Konzert besuchen.", explanation: "Vary noun preferences, activity preferences, and a present wish." }),
    ex({ id: "a134-48", type: "production", prompt: "Rewrite five direct wants with wollen as softer wishes with möchten.", model: "Ich will zahlen. → Ich möchte bitte zahlen. · Willst du Kaffee? → Möchtest du einen Kaffee? · Wir wollen ein Zimmer. → Wir möchten ein Zimmer.", explanation: "möchten is usually more appropriate in service and polite social situations." }),
    ex({ id: "a134-49", type: "production", prompt: "Write an eight-sentence holiday plan with likes and wishes.", model: "Wir reisen gern ans Meer. Meine Schwester mag warme Orte. Ich wandere lieber. Dieses Jahr möchten wir nach Österreich fahren. Wir möchten eine kleine Wohnung mieten und viel draußen sein.", explanation: "Connect stable preferences to specific plans." }),
    ex({ id: "a134-50", type: "production", prompt: "Record a one-minute answer about food, hobbies, and one present wish.", model: "Ich mag asiatisches Essen, aber ich mag keinen Fisch. Ich koche gern und probiere gern neue Rezepte. In meiner Freizeit lese ich lieber. Heute Abend möchte ich mit Freunden essen gehen.", explanation: "Fluent contrast practice makes the three preference patterns automatic." }),
  ]),
];
