import type { GrammarExercise } from "@/app/grammar/course";

const withGroup = (group: string, items: GrammarExercise[]) => items.map((item) => ({ ...item, group }));
const ex = (item: GrammarExercise) => item;

const pluralPairs = [
  ["der Tag", "die Tage", "-e", "die Tags"],
  ["der Stuhl", "die Stühle", "umlaut + -e", "die Stuhls"],
  ["die Frau", "die Frauen", "-(e)n", "die Fraue"],
  ["die Wohnung", "die Wohnungen", "-(e)n", "die Wohnunge"],
  ["das Kind", "die Kinder", "-er", "die Kinds"],
  ["das Buch", "die Bücher", "umlaut + -er", "die Bucher"],
  ["das Auto", "die Autos", "-s", "die Autoen"],
  ["der Lehrer", "die Lehrer", "no ending", "die Lehrers"],
  ["der Apfel", "die Äpfel", "umlaut only", "die Apfeln"],
  ["die Freundin", "die Freundinnen", "-innen", "die Freundins"],
  ["der Mann", "die Männer", "umlaut + -er", "die Manns"],
  ["die Hand", "die Hände", "umlaut + -e", "die Handen"],
  ["das Bild", "die Bilder", "-er", "die Bilds"],
  ["das Ei", "die Eier", "-er", "die Eis"],
  ["der Computer", "die Computer", "no ending", "die Computers"],
  ["die Zeitung", "die Zeitungen", "-(e)n", "die Zeitungs"],
  ["das Café", "die Cafés", "-s", "die Caféen"],
  ["der Bruder", "die Brüder", "umlaut only", "die Bruders"],
  ["die Mutter", "die Mütter", "umlaut only", "die Muttern"],
  ["das Museum", "die Museen", "foreign plural", "die Museums"],
] as const;

export const A1_LESSON_NINE_EXERCISES: GrammarExercise[] = [
  ...withGroup("1 · Plural patterns", pluralPairs.slice(0, 10).map(([singular, plural, pattern, wrong], index) => ex({
    id: `a123-${String(index + 1).padStart(2, "0")}`,
    type: "choice",
    prompt: `Choose the plural of ${singular}.`,
    options: [plural, wrong, singular.replace(/^(der|die|das) /, "die "), `${singular.replace(/^(der|die|das) /, "die ")}e`],
    answer: plural,
    explanation: `${singular} forms its plural as ${plural} (${pattern}).`,
  }))),
  ...withGroup("2 · Plural recall", pluralPairs.slice(10, 20).map(([singular, plural, pattern], index) => ex({
    id: `a123-${String(index + 11).padStart(2, "0")}`,
    type: "fill",
    prompt: `${singular} → ___`,
    answer: plural,
    explanation: `The correct pair is ${singular} – ${plural} (${pattern}).`,
  }))),
  ...withGroup("3 · Plurals in sentences", [
    ex({ id: "a123-21", type: "order", prompt: "Build the plural sentence.", tokens: ["sind", "Die", "neu", "Bücher", "."], answer: "Die Bücher sind neu.", explanation: "Buch becomes Bücher, and the plural subject takes sind." }),
    ex({ id: "a123-22", type: "order", prompt: "Build the sentence.", tokens: ["warten", "Frauen", "Zwei", "draußen", "."], answer: "Zwei Frauen warten draußen.", explanation: "Frau becomes Frauen; the plural verb is warten." }),
    ex({ id: "a123-23", type: "order", prompt: "Build the sentence.", tokens: ["im", "Die", "spielen", "Kinder", "Park", "."], answer: "Die Kinder spielen im Park.", explanation: "Kind becomes Kinder and requires a plural verb." }),
    ex({ id: "a123-24", type: "order", prompt: "Build the sentence.", tokens: ["teuer", "Die", "sind", "Autos", "."], answer: "Die Autos sind teuer.", explanation: "Auto forms the plural Autos." }),
    ex({ id: "a123-25", type: "order", prompt: "Build the sentence.", tokens: ["arbeiten", "hier", "Lehrer", "Drei", "."], answer: "Drei Lehrer arbeiten hier.", explanation: "Lehrer has no visible plural ending; the number and verb show plurality." }),
    ex({ id: "a123-26", type: "correction", prompt: "Correct: Zwei Frau warten draußen.", answer: "Zwei Frauen warten draußen.", explanation: "The plural of Frau is Frauen." }),
    ex({ id: "a123-27", type: "correction", prompt: "Correct: Die Kinder ist müde.", answer: "Die Kinder sind müde.", explanation: "A plural subject requires sind." }),
    ex({ id: "a123-28", type: "correction", prompt: "Correct: Ich kaufe drei Buchs.", answer: "Ich kaufe drei Bücher.", explanation: "The plural of Buch is Bücher." }),
    ex({ id: "a123-29", type: "correction", prompt: "Correct: Die Apfel sind frisch.", answer: "Die Äpfel sind frisch.", explanation: "Apfel forms its plural with an umlaut: Äpfel." }),
    ex({ id: "a123-30", type: "correction", prompt: "Correct: Ein Autos stehen vor dem Haus.", answer: "Autos stehen vor dem Haus.", explanation: "There is no indefinite plural article; Autos already marks the plural." }),
  ]),
  ...withGroup("4 · Translation", [
    ex({ id: "a123-31", type: "translation", direction: "en-de", prompt: "Translate: The books are new.", answer: ["Die Bücher sind neu.", "Die Bücher sind neu"], explanation: "Buch becomes Bücher; use die and sind in the plural." }),
    ex({ id: "a123-32", type: "translation", direction: "en-de", prompt: "Translate: Two women are waiting.", answer: ["Zwei Frauen warten.", "Zwei Frauen warten"], explanation: "The plural of Frau is Frauen." }),
    ex({ id: "a123-33", type: "translation", direction: "en-de", prompt: "Translate: The children are playing outside.", answer: ["Die Kinder spielen draußen.", "Die Kinder spielen draußen"], explanation: "Kind becomes Kinder; spielen is plural." }),
    ex({ id: "a123-34", type: "translation", direction: "en-de", prompt: "Translate: My brothers live in Berlin.", answer: ["Meine Brüder wohnen in Berlin.", "Meine Brüder wohnen in Berlin"], explanation: "Bruder becomes Brüder with an umlaut." }),
    ex({ id: "a123-35", type: "translation", direction: "en-de", prompt: "Translate: There are cafés in the city.", answer: ["In der Stadt gibt es Cafés.", "Es gibt Cafés in der Stadt."], explanation: "Café forms its plural with -s." }),
    ex({ id: "a123-36", type: "translation", direction: "de-en", prompt: "Translate: Die Wohnungen sind klein.", answer: ["The apartments are small."], explanation: "Wohnung forms the plural Wohnungen." }),
    ex({ id: "a123-37", type: "translation", direction: "de-en", prompt: "Translate: Drei Männer arbeiten hier.", answer: ["Three men work here.", "Three men are working here."], explanation: "Mann has the plural Männer." }),
    ex({ id: "a123-38", type: "translation", direction: "de-en", prompt: "Translate: Die Hände sind kalt.", answer: ["The hands are cold."], explanation: "Hand becomes Hände." }),
    ex({ id: "a123-39", type: "translation", direction: "de-en", prompt: "Translate: Meine Freundinnen kommen morgen.", answer: ["My female friends are coming tomorrow.", "My friends are coming tomorrow."], explanation: "Freundin becomes Freundinnen." }),
    ex({ id: "a123-40", type: "translation", direction: "de-en", prompt: "Translate: Die Museen öffnen um zehn.", answer: ["The museums open at ten.", "The museums are opening at ten."], explanation: "Museum has the plural Museen." }),
  ]),
  ...withGroup("5 · Active plural use", [
    ex({ id: "a123-41", type: "production", prompt: "Write five singular–plural pairs from the home category.", model: "der Tisch – die Tische · der Stuhl – die Stühle · die Lampe – die Lampen · das Bild – die Bilder · das Fenster – die Fenster", explanation: "Include articles and mark every umlaut clearly." }),
    ex({ id: "a123-42", type: "production", prompt: "Write five singular–plural pairs from food and shopping.", model: "der Apfel – die Äpfel · die Banane – die Bananen · das Ei – die Eier · das Brötchen – die Brötchen · das Café – die Cafés", explanation: "Mix different plural patterns rather than adding one ending mechanically." }),
    ex({ id: "a123-43", type: "production", prompt: "Describe a classroom using six plural nouns.", model: "Im Kurs stehen Tische und Stühle. Auf den Tischen liegen Bücher und Hefte. Die Schüler haben Stifte und Wörterbücher.", explanation: "Check each plural form and match it with a plural verb where needed." }),
    ex({ id: "a123-44", type: "production", prompt: "Write six sentences that contrast one item with several items.", model: "Ein Buch ist neu. Drei Bücher sind alt. Eine Frau wartet. Zwei Frauen telefonieren.", explanation: "Contrast singular and plural articles, noun forms, and verbs." }),
    ex({ id: "a123-45", type: "production", prompt: "Group twelve nouns by plural pattern: -e, -(e)n, -er, -s, or no ending.", model: "-e: Tage, Tische · -(e)n: Frauen, Wohnungen · -er: Kinder, Bilder · -s: Autos, Cafés · no ending: Lehrer, Computer", explanation: "Organising by pattern builds analogy without pretending every plural is predictable." }),
    ex({ id: "a123-46", type: "production", prompt: "Write a six-sentence market scene with at least eight plural nouns.", model: "Auf dem Markt liegen Äpfel, Bananen und Eier. Zwei Frauen kaufen Tomaten. Die Verkäufer tragen Jacken. Vor den Cafés stehen Tische und Stühle.", explanation: "Use natural quantities and plural verb agreement." }),
    ex({ id: "a123-47", type: "production", prompt: "Write five plural noun cards with article, singular, plural, and English.", model: "der Mann – die Männer – man · die Hand – die Hände – hand · das Museum – die Museen – museum", explanation: "Store plural information with the noun from the beginning." }),
    ex({ id: "a123-48", type: "production", prompt: "Describe five plural changes aloud in words, including any umlaut.", model: "Buch becomes Bücher: u changes to ü and the noun adds -er. Frau becomes Frauen: the noun adds -en.", explanation: "Explaining the visible change makes form recall more deliberate." }),
    ex({ id: "a123-49", type: "production", prompt: "Write an eight-sentence picture description containing people, objects, and places in the plural.", model: "Auf dem Bild sind zwei Männer und drei Frauen. Die Männer tragen Hüte. Die Frauen haben Taschen. Hinter ihnen stehen Autos. Vor den Häusern spielen Kinder.", explanation: "Use plural nouns with matching plural verbs and pronouns." }),
    ex({ id: "a123-50", type: "production", prompt: "Create a ten-item personal plural review list and use every plural in a sentence.", model: "die Bücher: Meine Bücher sind im Regal. · die Freunde: Meine Freunde kommen heute. · die Städte: Die Städte sind groß.", explanation: "Personal examples provide retrieval practice in meaningful contexts." }),
  ]),
];

const subjectItems = [
  ["Heute repariert der Mechaniker das Auto.", "der Mechaniker", ["Heute", "der Mechaniker", "das Auto", "repariert"]],
  ["Die Nachbarin kocht eine Suppe.", "die Nachbarin", ["die Nachbarin", "eine Suppe", "kocht", "die"]],
  ["Im Garten spielen die Kinder.", "die Kinder", ["Im Garten", "die Kinder", "spielen", "Garten"]],
  ["Morgen kommt der Zug später.", "der Zug", ["Morgen", "der Zug", "später", "kommt"]],
  ["Ein Hund schläft vor der Tür.", "ein Hund", ["ein Hund", "vor der Tür", "schläft", "Tür"]],
  ["Meine Schwester arbeitet in Köln.", "meine Schwester", ["meine Schwester", "in Köln", "arbeitet", "Köln"]],
  ["Am Montag beginnt der Kurs.", "der Kurs", ["Am Montag", "der Kurs", "beginnt", "Montag"]],
  ["Das Buch liegt auf dem Tisch.", "das Buch", ["das Buch", "auf dem Tisch", "liegt", "Tisch"]],
  ["Heute besuchen meine Eltern Berlin.", "meine Eltern", ["Heute", "meine Eltern", "Berlin", "besuchen"]],
  ["Wer arbeitet heute?", "Wer", ["Wer", "heute", "arbeitet", "no subject"]],
] as const;

export const A1_LESSON_TEN_EXERCISES: GrammarExercise[] = [
  ...withGroup("1 · Finding the subject", subjectItems.map(([sentence, subject, options], index) => ex({
    id: `a124-${String(index + 1).padStart(2, "0")}`,
    type: "choice",
    prompt: `Identify the nominative subject: ${sentence}`,
    options: [...options],
    answer: subject,
    explanation: `${subject} answers who or what performs the action and controls the verb.`,
  }))),
  ...withGroup("2 · Nominative forms", [
    ex({ id: "a124-11", type: "fill", prompt: "___ Mann arbeitet hier. (the)", answer: "Der", explanation: "The masculine subject uses nominative der." }),
    ex({ id: "a124-12", type: "fill", prompt: "___ Frau wartet draußen. (the)", answer: "Die", explanation: "The feminine subject uses nominative die." }),
    ex({ id: "a124-13", type: "fill", prompt: "___ Kind spielt im Park. (the)", answer: "Das", explanation: "The neuter subject uses nominative das." }),
    ex({ id: "a124-14", type: "fill", prompt: "___ Gäste kommen morgen. (the)", answer: "Die", explanation: "Plural nominative uses die." }),
    ex({ id: "a124-15", type: "fill", prompt: "___ Lehrer erklärt die Aufgabe. (a)", answer: "Ein", explanation: "A masculine nominative subject uses ein." }),
    ex({ id: "a124-16", type: "fill", prompt: "___ Ärztin hilft dem Kind. (a)", answer: "Eine", explanation: "A feminine nominative subject uses eine." }),
    ex({ id: "a124-17", type: "fill", prompt: "___ Problem bleibt. (a)", answer: "Ein", explanation: "Problem is neuter nominative: ein Problem." }),
    ex({ id: "a124-18", type: "fill", prompt: "Heute ___ der Bus spät. (kommen)", answer: "kommt", explanation: "Der Bus is a singular nominative subject and takes kommt." }),
    ex({ id: "a124-19", type: "fill", prompt: "Heute ___ die Busse spät. (kommen)", answer: "kommen", explanation: "Die Busse is a plural nominative subject and takes kommen." }),
    ex({ id: "a124-20", type: "fill", prompt: "Das ___ meine Eltern. (sein)", answer: "sind", explanation: "The nominative complement meine Eltern is plural, so use sind." }),
  ]),
  ...withGroup("3 · Sentence building", [
    ex({ id: "a124-21", type: "order", prompt: "Build the sentence.", tokens: ["kocht", "Die", "Nachbarin", "."], answer: "Die Nachbarin kocht.", explanation: "The nominative subject precedes the verb in the neutral order." }),
    ex({ id: "a124-22", type: "order", prompt: "Start with the time phrase.", tokens: ["meine", "Heute", "kommt", "Schwester", "."], answer: "Heute kommt meine Schwester.", explanation: "Meine Schwester remains nominative after the verb." }),
    ex({ id: "a124-23", type: "order", prompt: "Build the plural sentence.", tokens: ["spielen", "Die", "draußen", "Kinder", "."], answer: "Die Kinder spielen draußen.", explanation: "Die Kinder is the nominative plural subject." }),
    ex({ id: "a124-24", type: "order", prompt: "Build the identification.", tokens: ["Bruder", "mein", "Das", "ist", "."], answer: "Das ist mein Bruder.", explanation: "After sein, mein Bruder is nominative." }),
    ex({ id: "a124-25", type: "order", prompt: "Start with the place.", tokens: ["ein", "Im", "Hund", "schläft", "Flur", "."], answer: "Im Flur schläft ein Hund.", explanation: "Ein Hund remains the nominative subject despite following the verb." }),
    ex({ id: "a124-26", type: "order", prompt: "Build the question.", tokens: ["heute", "Wer", "arbeitet", "?"], answer: "Wer arbeitet heute?", explanation: "Wer is itself the nominative subject." }),
    ex({ id: "a124-27", type: "order", prompt: "Build the sentence.", tokens: ["Ärztin", "Lena", "wird", "."], answer: "Lena wird Ärztin.", explanation: "After werden, the profession remains nominative." }),
    ex({ id: "a124-28", type: "order", prompt: "Build the sentence.", tokens: ["bleibt", "Das", "Problem", "."], answer: "Das Problem bleibt.", explanation: "Das Problem is the nominative subject." }),
    ex({ id: "a124-29", type: "order", prompt: "Start with Morgen.", tokens: ["der", "Morgen", "beginnt", "Kurs", "."], answer: "Morgen beginnt der Kurs.", explanation: "The subject is still der Kurs, not the opening adverb." }),
    ex({ id: "a124-30", type: "order", prompt: "Build the plural identification.", tokens: ["meine", "sind", "Das", "Freunde", "."], answer: "Das sind meine Freunde.", explanation: "Meine Freunde is a plural nominative complement." }),
  ]),
  ...withGroup("4 · Error correction", [
    ex({ id: "a124-31", type: "correction", prompt: "Correct: Heute arbeitet den Mann.", answer: "Heute arbeitet der Mann.", explanation: "The man performs the action, so he is nominative." }),
    ex({ id: "a124-32", type: "correction", prompt: "Correct: Das ist meinen Bruder.", answer: "Das ist mein Bruder.", explanation: "After sein, the identifying noun remains nominative." }),
    ex({ id: "a124-33", type: "correction", prompt: "Correct: Eine Mann wartet.", answer: "Ein Mann wartet.", explanation: "The masculine nominative indefinite article is ein." }),
    ex({ id: "a124-34", type: "correction", prompt: "Correct: Der Kinder spielen.", answer: "Die Kinder spielen.", explanation: "Plural nominative uses die." }),
    ex({ id: "a124-35", type: "correction", prompt: "Correct: Heute kommen der Bus.", answer: "Heute kommt der Bus.", explanation: "The singular subject der Bus requires kommt." }),
    ex({ id: "a124-36", type: "correction", prompt: "Correct: Die Frau kochen heute.", answer: "Die Frau kocht heute.", explanation: "The singular nominative subject controls the verb ending." }),
    ex({ id: "a124-37", type: "correction", prompt: "Correct: Das sind mein Vater.", answer: "Das ist mein Vater.", explanation: "Mein Vater is singular, so use ist." }),
    ex({ id: "a124-38", type: "correction", prompt: "Correct: Im Park spielt die Kinder.", answer: "Im Park spielen die Kinder.", explanation: "Die Kinder is plural even after the verb." }),
    ex({ id: "a124-39", type: "correction", prompt: "Correct: Wer arbeiten heute?", answer: "Wer arbeitet heute?", explanation: "Subject wer normally takes a third-person singular verb." }),
    ex({ id: "a124-40", type: "correction", prompt: "Correct: Er wird einen Lehrer.", answer: "Er wird Lehrer.", explanation: "A profession after werden is nominative and normally has no article." }),
  ]),
  ...withGroup("5 · Translation and production", [
    ex({ id: "a124-41", type: "translation", direction: "en-de", prompt: "Translate: The neighbour is cooking.", answer: ["Die Nachbarin kocht.", "Der Nachbar kocht."], explanation: "The person performing the action is the nominative subject." }),
    ex({ id: "a124-42", type: "translation", direction: "en-de", prompt: "Translate: Today the bus is coming late.", answer: ["Heute kommt der Bus spät.", "Der Bus kommt heute spät."], explanation: "Der Bus remains nominative regardless of position." }),
    ex({ id: "a124-43", type: "translation", direction: "en-de", prompt: "Translate: That is my sister.", answer: ["Das ist meine Schwester.", "Das ist meine Schwester"], explanation: "After ist, meine Schwester is nominative." }),
    ex({ id: "a124-44", type: "translation", direction: "de-en", prompt: "Translate: Im Garten spielen die Kinder.", answer: ["The children are playing in the garden.", "The children play in the garden."], explanation: "Die Kinder is the subject even though it follows the verb." }),
    ex({ id: "a124-45", type: "translation", direction: "de-en", prompt: "Translate: Wer kommt morgen?", answer: ["Who is coming tomorrow?", "Who comes tomorrow?"], explanation: "Wer functions as the nominative subject." }),
    ex({ id: "a124-46", type: "production", prompt: "Write five sentences with different nominative subjects.", model: "Der Bus kommt. Eine Frau wartet. Das Kind spielt. Meine Freunde lernen. Ich arbeite.", explanation: "Underline the subject and match every verb to it." }),
    ex({ id: "a124-47", type: "production", prompt: "Write four sentences in which the subject follows the verb.", model: "Heute arbeitet meine Mutter. Im Park spielen die Kinder. Morgen kommt der Zug. Hier wohnt ein Freund.", explanation: "Position does not determine case; identify who or what controls the verb." }),
    ex({ id: "a124-48", type: "production", prompt: "Write four identification sentences with sein, werden, or bleiben.", model: "Das ist mein Bruder. Mia ist Ärztin. Tom wird Lehrer. Das Problem bleibt ein Problem.", explanation: "Use nominative complements after these linking verbs." }),
    ex({ id: "a124-49", type: "production", prompt: "Create six subject questions with wer or was and answer them.", model: "Wer arbeitet heute? Meine Schwester. Was liegt auf dem Tisch? Das Buch.", explanation: "Wer or was replaces the subject and normally takes a singular verb." }),
    ex({ id: "a124-50", type: "production", prompt: "Write an eight-sentence scene and label each nominative subject.", model: "[Der Zug] kommt. [Viele Menschen] warten. Am Bahnsteig steht [eine Familie]. [Die Kinder] sind müde.", explanation: "Find the controller of each conjugated verb, not simply the first noun." }),
  ]),
];
