import type { GrammarExercise } from "@/app/grammar/course";

const withGroup = (group: string, items: GrammarExercise[]) => items.map((item) => ({ ...item, group }));
const ex = (item: GrammarExercise) => item;

const objectItems = [
  ["Die Frau kauft den Mantel.", "den Mantel", ["Die Frau", "den Mantel", "kauft", "die"]],
  ["Ich brauche einen Termin.", "einen Termin", ["Ich", "einen Termin", "brauche", "Termin"]],
  ["Er liest die Zeitung.", "die Zeitung", ["Er", "die Zeitung", "liest", "Zeitung"]],
  ["Wir suchen das Hotel.", "das Hotel", ["Wir", "das Hotel", "suchen", "Hotel"]],
  ["Mila besucht ihre Freunde.", "ihre Freunde", ["Mila", "ihre Freunde", "besucht", "Freunde"]],
  ["Der Schüler schreibt den Text.", "den Text", ["Der Schüler", "den Text", "schreibt", "Text"]],
  ["Meine Mutter kocht eine Suppe.", "eine Suppe", ["Meine Mutter", "eine Suppe", "kocht", "Suppe"]],
  ["Das Kind isst einen Apfel.", "einen Apfel", ["Das Kind", "einen Apfel", "isst", "Apfel"]],
  ["Sara hat ein Fahrrad.", "ein Fahrrad", ["Sara", "ein Fahrrad", "hat", "Fahrrad"]],
  ["Die Gäste trinken Kaffee.", "Kaffee", ["Die Gäste", "Kaffee", "trinken", "Gäste"]],
] as const;

export const A1_LESSON_ELEVEN_EXERCISES: GrammarExercise[] = [
  ...withGroup("1 · Accusative concepts", [
    ex({ id: "a125-01", type: "choice", prompt: "What does the accusative usually mark?", options: ["the subject", "the direct object", "the verb", "the sentence time"], answer: "the direct object", explanation: "The accusative commonly marks the person or thing directly affected by the action." }),
    ex({ id: "a125-02", type: "choice", prompt: "Which question finds a person as direct object?", options: ["Wer?", "Wen?", "Wo?", "Wann?"], answer: "Wen?", explanation: "Ask Wen? for a person receiving the action." }),
    ex({ id: "a125-03", type: "choice", prompt: "Which question often finds a thing as direct object?", options: ["Was?", "Wer?", "Wie?", "Woher?"], answer: "Was?", explanation: "Ask Was? for a thing directly receiving the action." }),
    ex({ id: "a125-04", type: "choice", prompt: "Which gender shows the main visible A1 accusative change?", options: ["masculine", "feminine", "neuter", "plural"], answer: "masculine", explanation: "Masculine der/ein becomes den/einen." }),
    ex({ id: "a125-05", type: "choice", prompt: "What does der become in the accusative?", options: ["den", "die", "das", "dem"], answer: "den", explanation: "Masculine accusative definite article is den." }),
    ex({ id: "a125-06", type: "choice", prompt: "What does ein become for a masculine accusative noun?", options: ["eine", "einen", "einem", "ein"], answer: "einen", explanation: "Masculine accusative indefinite article is einen." }),
    ex({ id: "a125-07", type: "choice", prompt: "Which form stays unchanged from nominative to accusative?", options: ["der Mann", "ein Mann", "die Frau", "kein Mann"], answer: "die Frau", explanation: "Feminine die remains die in the accusative." }),
    ex({ id: "a125-08", type: "choice", prompt: "Which verb commonly takes an accusative object?", options: ["haben", "sein", "bleiben", "werden"], answer: "haben", explanation: "haben directly links to what someone has." }),
    ex({ id: "a125-09", type: "choice", prompt: "Which sentence contains an accusative object?", options: ["Der Mann schläft.", "Das ist mein Bruder.", "Ich sehe den Mann.", "Heute kommt der Zug."], answer: "Ich sehe den Mann.", explanation: "Den Mann directly receives the action sehen." }),
    ex({ id: "a125-10", type: "choice", prompt: "Which summary is correct?", options: ["Only masculine articles visibly change at this stage.", "Every accusative article changes.", "Subjects are accusative.", "Accusative always comes last."], answer: "Only masculine articles visibly change at this stage.", explanation: "Feminine, neuter, and plural forms look like their nominative forms at A1." }),
  ]),
  ...withGroup("2 · Accusative article forms", [
    ex({ id: "a125-11", type: "fill", prompt: "Ich sehe ___ Mann. (the)", answer: "den", explanation: "Mann is a masculine direct object: den Mann." }),
    ex({ id: "a125-12", type: "fill", prompt: "Wir brauchen ___ Termin. (a)", answer: "einen", explanation: "Termin is masculine accusative: einen Termin." }),
    ex({ id: "a125-13", type: "fill", prompt: "Sie kauft ___ Tasche. (the)", answer: "die", explanation: "Feminine die remains die in the accusative." }),
    ex({ id: "a125-14", type: "fill", prompt: "Er bestellt ___ Suppe. (a)", answer: "eine", explanation: "Feminine eine remains eine in the accusative." }),
    ex({ id: "a125-15", type: "fill", prompt: "Ich lese ___ Buch. (the)", answer: "das", explanation: "Neuter das remains das in the accusative." }),
    ex({ id: "a125-16", type: "fill", prompt: "Mia hat ___ Auto. (a)", answer: "ein", explanation: "Neuter ein remains ein in the accusative." }),
    ex({ id: "a125-17", type: "fill", prompt: "Wir besuchen ___ Freunde. (the)", answer: "die", explanation: "Plural die remains die in the accusative." }),
    ex({ id: "a125-18", type: "fill", prompt: "Er trinkt ___ Kaffee. (no)", answer: "keinen", explanation: "Kaffee is masculine accusative: keinen Kaffee." }),
    ex({ id: "a125-19", type: "fill", prompt: "Sie sucht ___ Schlüssel. (her)", answer: "ihren", explanation: "Masculine accusative possessive adds -en: ihren Schlüssel." }),
    ex({ id: "a125-20", type: "fill", prompt: "Ich besuche ___ Bruder. (my)", answer: "meinen", explanation: "Masculine accusative mein becomes meinen." }),
  ]),
  ...withGroup("3 · Finding direct objects", objectItems.map(([sentence, object, options], index) => ex({
    id: `a125-${String(index + 21).padStart(2, "0")}`,
    type: "choice",
    prompt: `Identify the accusative direct object: ${sentence}`,
    options: [...options],
    answer: object,
    explanation: `${object} answers whom or what directly receives the action.`,
  }))),
  ...withGroup("4 · Building and correcting", [
    ex({ id: "a125-31", type: "order", prompt: "Build the sentence.", tokens: ["einen", "Sie", "Kaffee", "bestellt", "."], answer: "Sie bestellt einen Kaffee.", explanation: "Kaffee is a masculine accusative object." }),
    ex({ id: "a125-32", type: "order", prompt: "Build the sentence.", tokens: ["den", "Ich", "Bus", "nehme", "."], answer: "Ich nehme den Bus.", explanation: "Bus is masculine and directly receives nehmen." }),
    ex({ id: "a125-33", type: "order", prompt: "Build the sentence.", tokens: ["die", "liest", "Zeitung", "Er", "."], answer: "Er liest die Zeitung.", explanation: "Zeitung is a feminine accusative object." }),
    ex({ id: "a125-34", type: "order", prompt: "Build the question.", tokens: ["du", "Wen", "besuchst", "?"], answer: "Wen besuchst du?", explanation: "Wen asks for a person as direct object." }),
    ex({ id: "a125-35", type: "order", prompt: "Build the question.", tokens: ["du", "Was", "kaufst", "?"], answer: "Was kaufst du?", explanation: "Was asks for the thing being bought." }),
    ex({ id: "a125-36", type: "correction", prompt: "Correct: Ich sehe der Mann.", answer: "Ich sehe den Mann.", explanation: "The masculine direct object requires den." }),
    ex({ id: "a125-37", type: "correction", prompt: "Correct: Sie braucht ein Termin.", answer: "Sie braucht einen Termin.", explanation: "Masculine accusative ein becomes einen." }),
    ex({ id: "a125-38", type: "correction", prompt: "Correct: Der Schüler liest der Text.", answer: "Der Schüler liest den Text.", explanation: "Text is a masculine direct object." }),
    ex({ id: "a125-39", type: "correction", prompt: "Correct: Ich besuche mein Bruder.", answer: "Ich besuche meinen Bruder.", explanation: "Masculine accusative possessive adds -en." }),
    ex({ id: "a125-40", type: "correction", prompt: "Correct: Den Mann kauft das Brot.", answer: "Der Mann kauft das Brot.", explanation: "The man performs the action and must be nominative der Mann." }),
  ]),
  ...withGroup("5 · Translation and production", [
    ex({ id: "a125-41", type: "translation", direction: "en-de", prompt: "Translate: I see the man.", answer: ["Ich sehe den Mann.", "Ich sehe den Mann"], explanation: "Mann is masculine accusative: den Mann." }),
    ex({ id: "a125-42", type: "translation", direction: "en-de", prompt: "Translate: We need an appointment.", answer: ["Wir brauchen einen Termin.", "Wir brauchen einen Termin"], explanation: "Termin is masculine accusative: einen Termin." }),
    ex({ id: "a125-43", type: "translation", direction: "en-de", prompt: "Translate: She is buying the bag.", answer: ["Sie kauft die Tasche.", "Sie kauft die Tasche"], explanation: "Feminine die is unchanged in the accusative." }),
    ex({ id: "a125-44", type: "translation", direction: "de-en", prompt: "Translate: Das Kind isst einen Apfel.", answer: ["The child is eating an apple.", "The child eats an apple."], explanation: "Einen Apfel is the masculine accusative object." }),
    ex({ id: "a125-45", type: "translation", direction: "de-en", prompt: "Translate: Wen besuchst du morgen?", answer: ["Whom are you visiting tomorrow?", "Who are you visiting tomorrow?"], explanation: "Wen asks for a person as direct object." }),
    ex({ id: "a125-46", type: "production", prompt: "Write five sentences with masculine accusative objects.", model: "Ich sehe den Bus. Ich brauche einen Termin. Ich trinke keinen Kaffee. Ich besuche meinen Bruder. Ich kaufe den Mantel.", explanation: "Mark the -n ending in den, einen, keinen, and meinen." }),
    ex({ id: "a125-47", type: "production", prompt: "Write six sentences using haben, brauchen, kaufen, lesen, essen, and suchen.", model: "Ich habe ein Auto. Wir brauchen einen Plan. Sie kauft die Zeitung. Er liest das Buch. Das Kind isst einen Apfel. Ich suche den Schlüssel.", explanation: "Identify the direct object of each verb and choose its article." }),
    ex({ id: "a125-48", type: "production", prompt: "Write four Wen?/Was? questions and answer them.", model: "Wen besuchst du? Ich besuche meinen Freund. Was liest du? Ich lese die Zeitung.", explanation: "Use Wen for people and Was for things or actions." }),
    ex({ id: "a125-49", type: "production", prompt: "Describe a shopping trip in eight sentences with at least six accusative objects.", model: "Ich kaufe einen Mantel und eine Tasche. Danach brauche ich einen Kaffee. Im Supermarkt kaufe ich das Brot, die Milch und die Äpfel.", explanation: "Check each object's gender; only masculine forms visibly change." }),
    ex({ id: "a125-50", type: "production", prompt: "Write an eight-sentence scene and label every nominative subject and accusative object.", model: "[Die Frau]NOM kauft [den Mantel]AKK. [Der Verkäufer]NOM zeigt [eine Jacke]AKK. [Das Kind]NOM trinkt [einen Saft]AKK.", explanation: "Separate who performs the action from what directly receives it." }),
  ]),
];

const owners = [
  ["ich", "mein", "meine", "my"],
  ["du", "dein", "deine", "your (informal singular)"],
  ["er", "sein", "seine", "his"],
  ["sie", "ihr", "ihre", "her"],
  ["es", "sein", "seine", "its"],
  ["wir", "unser", "unsere", "our"],
  ["ihr", "euer", "eure", "your (informal plural)"],
  ["sie", "ihr", "ihre", "their"],
  ["Sie", "Ihr", "Ihre", "your (formal)"],
  ["man", "sein", "seine", "one's"],
] as const;

export const A1_LESSON_TWELVE_EXERCISES: GrammarExercise[] = [
  ...withGroup("1 · Matching owner and stem", owners.map(([owner, masculine, , english], index) => ex({
    id: `a126-${String(index + 1).padStart(2, "0")}`,
    type: "choice",
    prompt: `Choose the possessive stem for ${owner} (${english}).`,
    options: [masculine, "mein", "dein", "ihr"].filter((value, optionIndex, values) => values.indexOf(value) === optionIndex),
    answer: masculine,
    explanation: `${owner} maps to the possessive stem ${masculine}-.`,
  }))),
  ...withGroup("2 · Possessive endings", [
    ex({ id: "a126-11", type: "fill", prompt: "Das ist ___ Bruder. (my)", answer: "mein", explanation: "Bruder is masculine nominative, so mein has no ending." }),
    ex({ id: "a126-12", type: "fill", prompt: "Das ist ___ Schwester. (my)", answer: "meine", explanation: "Schwester is feminine nominative, so add -e." }),
    ex({ id: "a126-13", type: "fill", prompt: "Das ist ___ Kind. (your, informal singular)", answer: "dein", explanation: "Kind is neuter nominative: dein Kind." }),
    ex({ id: "a126-14", type: "fill", prompt: "Das sind ___ Eltern. (our)", answer: "unsere", explanation: "Plural nominative takes -e: unsere Eltern." }),
    ex({ id: "a126-15", type: "fill", prompt: "Er besucht ___ Bruder. (his)", answer: "seinen", explanation: "Bruder is masculine accusative, so sein becomes seinen." }),
    ex({ id: "a126-16", type: "fill", prompt: "Sie besucht ___ Schwester. (her)", answer: "ihre", explanation: "Feminine accusative uses ihre." }),
    ex({ id: "a126-17", type: "fill", prompt: "Wir suchen ___ Auto. (our)", answer: "unser", explanation: "Neuter accusative has no ending: unser Auto." }),
    ex({ id: "a126-18", type: "fill", prompt: "Ihr besucht ___ Freunde. (your, plural)", answer: "eure", explanation: "euer loses the second e before an ending: eure Freunde." }),
    ex({ id: "a126-19", type: "fill", prompt: "Ist das ___ Pass, Frau Klein? (your, formal)", answer: "Ihr", explanation: "Formal possessive Ihr is capitalised." }),
    ex({ id: "a126-20", type: "fill", prompt: "Sie liebt ___ Kinder. (their)", answer: "ihre", explanation: "Plural accusative takes ihre; context shows that the owner is they." }),
  ]),
  ...withGroup("3 · Possessives in context", [
    ex({ id: "a126-21", type: "choice", prompt: "Ich habe einen Bruder. ___ Bruder heißt Tom.", options: ["Mein", "Meine", "Meinen", "Dein"], answer: "Mein", explanation: "The owner is ich; Bruder is masculine nominative." }),
    ex({ id: "a126-22", type: "choice", prompt: "Du hast eine Schwester. Wie heißt ___ Schwester?", options: ["dein", "deine", "deinen", "eure"], answer: "deine", explanation: "The owner is du; Schwester is feminine." }),
    ex({ id: "a126-23", type: "choice", prompt: "Paul hat ein Auto. ___ Auto ist neu.", options: ["Sein", "Seine", "Ihr", "Unser"], answer: "Sein", explanation: "Paul maps to er/sein; Auto is neuter." }),
    ex({ id: "a126-24", type: "choice", prompt: "Mia hat einen Termin. Sie vergisst ___ Termin nicht.", options: ["ihr", "ihre", "ihren", "seinen"], answer: "ihren", explanation: "Mia maps to ihr-; Termin is masculine accusative." }),
    ex({ id: "a126-25", type: "choice", prompt: "Wir wohnen in Bonn. ___ Wohnung ist klein.", options: ["Unser", "Unsere", "Unseren", "Eure"], answer: "Unsere", explanation: "The owner is wir; Wohnung is feminine." }),
    ex({ id: "a126-26", type: "choice", prompt: "Kinder, wo sind ___ Bücher?", options: ["euer", "eure", "euren", "Ihre"], answer: "eure", explanation: "The owners are ihr; plural Bücher takes eure." }),
    ex({ id: "a126-27", type: "choice", prompt: "Herr Klein, ist das ___ Koffer?", options: ["Ihr", "Ihre", "Ihren", "euer"], answer: "Ihr", explanation: "Formal Ihr is capitalised; Koffer is masculine nominative." }),
    ex({ id: "a126-28", type: "choice", prompt: "Die Kinder besuchen ___ Großeltern.", options: ["sein", "seine", "ihr", "ihre"], answer: "ihre", explanation: "The plural owners sie use ihr-; plural object takes -e." }),
    ex({ id: "a126-29", type: "choice", prompt: "Das Kind sucht ___ Ball.", options: ["sein", "seine", "seinen", "ihren"], answer: "seinen", explanation: "Kind maps to es/sein; Ball is masculine accusative." }),
    ex({ id: "a126-30", type: "choice", prompt: "Which phrase can mean her bag or their bag?", options: ["seine Tasche", "ihre Tasche", "deine Tasche", "unsere Tasche"], answer: "ihre Tasche", explanation: "ihr- can refer to sie singular or sie plural; context resolves the owner." }),
  ]),
  ...withGroup("4 · Building and correcting", [
    ex({ id: "a126-31", type: "order", prompt: "Build the sentence.", tokens: ["Bruder", "Das", "mein", "ist", "."], answer: "Das ist mein Bruder.", explanation: "Masculine nominative uses mein without an ending." }),
    ex({ id: "a126-32", type: "order", prompt: "Build the question.", tokens: ["deine", "Wo", "Schwester", "wohnt", "?"], answer: "Wo wohnt deine Schwester?", explanation: "Feminine nominative uses deine." }),
    ex({ id: "a126-33", type: "order", prompt: "Build the sentence.", tokens: ["seinen", "Er", "Bruder", "besucht", "."], answer: "Er besucht seinen Bruder.", explanation: "Masculine accusative sein- takes -en." }),
    ex({ id: "a126-34", type: "order", prompt: "Build the formal question.", tokens: ["Pass", "Ihr", "das", "Ist", "?"], answer: "Ist das Ihr Pass?", explanation: "Formal possessive Ihr is capitalised." }),
    ex({ id: "a126-35", type: "correction", prompt: "Correct: Das ist meine Bruder.", answer: "Das ist mein Bruder.", explanation: "Masculine nominative has no possessive ending." }),
    ex({ id: "a126-36", type: "correction", prompt: "Correct: Ich besuche mein Bruder.", answer: "Ich besuche meinen Bruder.", explanation: "Masculine accusative adds -en." }),
    ex({ id: "a126-37", type: "correction", prompt: "Correct: Wir lieben unser Kinder.", answer: "Wir lieben unsere Kinder.", explanation: "Plural accusative takes -e." }),
    ex({ id: "a126-38", type: "correction", prompt: "Correct: Kinder, wo ist euere Mutter?", answer: "Kinder, wo ist eure Mutter?", explanation: "euer normally becomes eure before an ending." }),
    ex({ id: "a126-39", type: "correction", prompt: "Correct formally: Ist das ihr Pass, Herr Klein?", answer: "Ist das Ihr Pass, Herr Klein?", explanation: "Formal Ihr must be capitalised." }),
    ex({ id: "a126-40", type: "correction", prompt: "Correct: Mia besucht seinen Vater.", answer: "Mia besucht ihren Vater.", explanation: "A female owner sie uses ihr-; Vater is masculine accusative." }),
  ]),
  ...withGroup("5 · Translation and production", [
    ex({ id: "a126-41", type: "translation", direction: "en-de", prompt: "Translate: That is my brother.", answer: ["Das ist mein Bruder.", "Das ist mein Bruder"], explanation: "Masculine nominative uses mein." }),
    ex({ id: "a126-42", type: "translation", direction: "en-de", prompt: "Translate: Where is your sister? (informal singular)", answer: ["Wo ist deine Schwester?", "Wo ist deine Schwester"], explanation: "du maps to dein-; feminine Schwester takes -e." }),
    ex({ id: "a126-43", type: "translation", direction: "en-de", prompt: "Translate: He is visiting his father.", answer: ["Er besucht seinen Vater.", "Er besucht seinen Vater"], explanation: "er maps to sein-; masculine accusative takes -en." }),
    ex({ id: "a126-44", type: "translation", direction: "en-de", prompt: "Translate formally: Is that your passport?", answer: ["Ist das Ihr Pass?", "Ist das Ihr Pass"], explanation: "Formal Ihr is capitalised." }),
    ex({ id: "a126-45", type: "translation", direction: "de-en", prompt: "Translate: Wir suchen unsere Schlüssel.", answer: ["We are looking for our keys.", "We look for our keys."], explanation: "unsere marks a plural accusative noun owned by wir." }),
    ex({ id: "a126-46", type: "production", prompt: "Write one noun phrase for every possessive stem from mein through Ihr.", model: "mein Bruder · deine Schwester · sein Auto · ihre Tasche · unser Haus · eure Freunde · ihre Kinder · Ihr Pass", explanation: "Separate the owner stem from the ending required by the noun." }),
    ex({ id: "a126-47", type: "production", prompt: "Describe your family in six sentences with possessives.", model: "Meine Mutter heißt Ana. Mein Vater arbeitet in Bonn. Meine Schwester studiert. Ihr Freund heißt Max. Unser Haus ist klein. Unsere Großeltern wohnen nah.", explanation: "Choose the owner first, then match the ending to the possessed noun." }),
    ex({ id: "a126-48", type: "production", prompt: "Write five pairs contrasting nominative and masculine accusative.", model: "Mein Bruder kommt. Ich besuche meinen Bruder. · Sein Vater arbeitet. Er sieht seinen Vater.", explanation: "Notice the -en added only in the masculine accusative phrase." }),
    ex({ id: "a126-49", type: "production", prompt: "Write a six-line lost-property dialogue using formal Ihr/Ihre/Ihren.", model: "Ist das Ihr Koffer? Nein, mein Koffer ist blau. Ist das Ihre Tasche? Ja, das ist meine Tasche. Und ist das Ihr Pass? Ja, vielen Dank.", explanation: "Capitalise formal possessives and match their endings to each noun." }),
    ex({ id: "a126-50", type: "production", prompt: "Write an eight-sentence scene with at least six different owners and explain each possessive choice.", model: "Tom sucht seinen Schlüssel: Tom = er, Schlüssel is masculine accusative. Mia öffnet ihre Tasche: Mia = sie, Tasche is feminine accusative.", explanation: "Verbalising owner, noun gender, and case turns possessive choice into a repeatable method." }),
  ]),
];
