import type { GrammarExercise } from "@/app/grammar/course";

const FRAME = "1 · The verb-second frame";
const OPENINGS = "2 · Different sentence openings";
const ORDER = "3 · Building sentences";
const REPAIR = "4 · Transforming and correcting";
const TRANSFER = "5 · Translation and production";

export const A1_LESSON_FOUR_EXERCISES: GrammarExercise[] = [
  { id: "a114-01", group: FRAME, type: "choice", prompt: "Where does the conjugated verb normally stand in a German main clause?", options: ["position one", "position two", "at the end", "after the subject in every sentence"], answer: "position two", explanation: "The conjugated verb is the second sentence element in a neutral German main clause." },
  { id: "a114-02", group: FRAME, type: "choice", prompt: "Which sentence has correct verb-second order?", options: ["Heute ich arbeite zu Hause.", "Heute arbeite ich zu Hause.", "Heute zu Hause ich arbeite.", "Heute ich zu Hause arbeite."], answer: "Heute arbeite ich zu Hause.", explanation: "Heute fills position one, so arbeite must occupy position two." },
  { id: "a114-03", group: FRAME, type: "choice", prompt: "How many sentence positions does Am Montag occupy?", options: ["one", "two", "three", "four"], answer: "one", explanation: "A multiword phrase can fill one functional position." },
  { id: "a114-04", group: FRAME, type: "choice", prompt: "Identify position one: Nach dem Kurs trinkt Sara einen Kaffee.", options: ["Nach", "Nach dem Kurs", "trinkt", "Sara"], answer: "Nach dem Kurs", explanation: "The complete time phrase Nach dem Kurs fills position one." },
  { id: "a114-05", group: FRAME, type: "choice", prompt: "Which element must move when Heute replaces Ich in position one?", options: ["the verb", "the object", "the subject", "the punctuation"], answer: "the subject", explanation: "The verb keeps position two, so the subject moves behind it: Heute arbeite ich." },
  { id: "a114-06", group: FRAME, type: "choice", prompt: "Which sentence begins with the subject?", options: ["Heute lernt Mia Deutsch.", "In Bonn wohnt Mia.", "Mia lernt heute Deutsch.", "Am Abend kocht Mia."], answer: "Mia lernt heute Deutsch.", explanation: "Mia is the subject and occupies position one." },
  { id: "a114-07", group: FRAME, type: "choice", prompt: "Which sentence begins with a place phrase?", options: ["Jonas arbeitet in Köln.", "In Köln arbeitet Jonas.", "Heute arbeitet Jonas.", "Jonas arbeitet heute."], answer: "In Köln arbeitet Jonas.", explanation: "In Köln is a place phrase in position one." },
  { id: "a114-08", group: FRAME, type: "choice", prompt: "Which word is the conjugated verb in Morgen besucht Lea ihre Oma?", options: ["Morgen", "besucht", "Lea", "Oma"], answer: "besucht", explanation: "besucht agrees with Lea and occupies position two." },
  { id: "a114-09", group: FRAME, type: "choice", prompt: "Choose the correct structural formula after a time opening.", options: ["time + subject + verb", "time + verb + subject", "verb + time + subject", "subject + time + verb"], answer: "time + verb + subject", explanation: "The opening phrase fills position one, the verb stays second, and the subject follows." },
  { id: "a114-10", group: FRAME, type: "choice", prompt: "Why is Heute Morgen lerne ich correct?", options: ["The verb is the third word.", "Heute Morgen is one time phrase.", "The subject may be omitted.", "German verbs always follow Morgen."], answer: "Heute Morgen is one time phrase.", explanation: "Verb-second counts sentence elements, not written words." },

  { id: "a114-11", group: OPENINGS, type: "fill", prompt: "Heute ___ ich im Büro. (arbeiten)", answer: "arbeite", explanation: "Heute is position one; the conjugated verb arbeite follows in position two." },
  { id: "a114-12", group: OPENINGS, type: "fill", prompt: "Am Samstag ___ wir unsere Freunde. (besuchen)", answer: "besuchen", explanation: "The time phrase is first, so besuchen is second and wir follows." },
  { id: "a114-13", group: OPENINGS, type: "fill", prompt: "In Berlin ___ meine Schwester. (wohnen)", answer: "wohnt", explanation: "The place phrase occupies position one; wohnt occupies position two." },
  { id: "a114-14", group: OPENINGS, type: "fill", prompt: "Nach der Arbeit ___ Paul Sport. (machen)", answer: "macht", explanation: "Nach der Arbeit is one opening phrase; macht follows directly." },
  { id: "a114-15", group: OPENINGS, type: "fill", prompt: "Jeden Morgen ___ der Bus um sieben Uhr. (kommen)", answer: "kommt", explanation: "The full time phrase fills position one and kommt is second." },
  { id: "a114-16", group: OPENINGS, type: "choice", prompt: "___ kauft Amir auf dem Markt Gemüse.", options: ["Am Samstag", "Am Samstag er", "Er am Samstag", "Kauft am Samstag"], answer: "Am Samstag", explanation: "The time phrase can occupy position one before the verb kauft." },
  { id: "a114-17", group: OPENINGS, type: "choice", prompt: "Im Sommer ___ viele Touristen nach Berlin.", options: ["kommen", "viele kommen", "nach Berlin kommen", "kommt"], answer: "kommen", explanation: "Im Sommer is first, kommen is second, and the plural subject follows." },
  { id: "a114-18", group: OPENINGS, type: "fill", prompt: "Manchmal ___ ich am Abend noch Deutsch. (lernen)", answer: "lerne", explanation: "Manchmal occupies position one; lerne remains second." },
  { id: "a114-19", group: OPENINGS, type: "choice", prompt: "Which continuation is correct after Zum Frühstück?", options: ["ich esse Brot.", "esse ich Brot.", "Brot ich esse.", "ich Brot esse."], answer: "esse ich Brot.", explanation: "After the opening phrase, use verb + subject." },
  { id: "a114-20", group: OPENINGS, type: "fill", prompt: "Bei gutem Wetter ___ die Kinder im Park. (spielen)", answer: "spielen", explanation: "Bei gutem Wetter is position one; spielen is position two." },

  { id: "a114-21", group: ORDER, type: "order", prompt: "Build a subject-first statement.", tokens: ["heute", "Ich", "zu", "arbeite", "Hause", "."], answer: "Ich arbeite heute zu Hause.", explanation: "Subject first, conjugated verb second, then the remaining information." },
  { id: "a114-22", group: ORDER, type: "order", prompt: "Start with the time expression.", tokens: ["heute", "Ich", "zu", "arbeite", "Hause", "."], answer: "Heute arbeite ich zu Hause.", explanation: "Heute is first, arbeite second, and ich follows the verb." },
  { id: "a114-23", group: ORDER, type: "order", prompt: "Start with the place.", tokens: ["meine", "Im", "arbeitet", "Stadtzentrum", "Mutter", "."], answer: "Im Stadtzentrum arbeitet meine Mutter.", explanation: "The place phrase fills position one; arbeitet is position two." },
  { id: "a114-24", group: ORDER, type: "order", prompt: "Build the sentence.", tokens: ["einen", "Nach", "trinkt", "Kaffee", "dem", "Kurs", "Lena", "."], answer: "Nach dem Kurs trinkt Lena einen Kaffee.", explanation: "Nach dem Kurs is one time phrase, followed by verb and subject." },
  { id: "a114-25", group: ORDER, type: "order", prompt: "Start with Morgen.", tokens: ["unsere", "Morgen", "wir", "besuchen", "Oma", "."], answer: "Morgen besuchen wir unsere Oma.", explanation: "The conjugated verb besuchen follows Morgen directly." },
  { id: "a114-26", group: ORDER, type: "order", prompt: "Build a place-first sentence.", tokens: ["viele", "Im", "Menschen", "Park", "spazieren", "."], answer: "Im Park spazieren viele Menschen.", explanation: "Im Park is position one, spazieren position two." },
  { id: "a114-27", group: ORDER, type: "order", prompt: "Build the statement with the subject first.", tokens: ["um", "Der", "beginnt", "Kurs", "Uhr", "neun", "."], answer: "Der Kurs beginnt um neun Uhr.", explanation: "Der Kurs is the subject; beginnt is the second element." },
  { id: "a114-28", group: ORDER, type: "order", prompt: "Start with Um neun Uhr.", tokens: ["um", "der", "beginnt", "Kurs", "Uhr", "neun", "."], answer: "Um neun Uhr beginnt der Kurs.", explanation: "The whole clock-time phrase fills position one." },
  { id: "a114-29", group: ORDER, type: "order", prompt: "Build the sentence with an adverb first.", tokens: ["ich", "fahre", "Normalerweise", "Bus", "mit", "dem", "."], answer: "Normalerweise fahre ich mit dem Bus.", explanation: "Normalerweise is position one; fahre is position two." },
  { id: "a114-30", group: ORDER, type: "order", prompt: "Build a sentence beginning with the object.", tokens: ["ich", "Das", "heute", "Buch", "lese", "."], answer: "Das Buch lese ich heute.", explanation: "An object can be emphasised in position one; the verb still comes second." },

  { id: "a114-31", group: REPAIR, type: "correction", prompt: "Correct: Heute ich lerne Deutsch.", answer: "Heute lerne ich Deutsch.", explanation: "The verb must immediately follow the opening element Heute." },
  { id: "a114-32", group: REPAIR, type: "correction", prompt: "Correct: Am Wochenende meine Freunde kommen.", answer: "Am Wochenende kommen meine Freunde.", explanation: "The time phrase is position one, so kommen must be second." },
  { id: "a114-33", group: REPAIR, type: "correction", prompt: "Correct: In München mein Bruder wohnt.", answer: "In München wohnt mein Bruder.", explanation: "The place phrase is first and the conjugated verb follows." },
  { id: "a114-34", group: REPAIR, type: "correction", prompt: "Correct: Jeden Morgen der Zug fährt um acht.", answer: "Jeden Morgen fährt der Zug um acht.", explanation: "Jeden Morgen occupies one position; fährt must occupy the next." },
  { id: "a114-35", group: REPAIR, type: "correction", prompt: "Correct: Nach dem Essen wir trinken Kaffee.", answer: "Nach dem Essen trinken wir Kaffee.", explanation: "Use opening phrase + verb + subject." },
  { id: "a114-36", group: REPAIR, type: "choice", prompt: "Transform Ich spiele am Samstag Tennis. Begin with Am Samstag.", options: ["Am Samstag ich spiele Tennis.", "Am Samstag spiele ich Tennis.", "Am Samstag Tennis spiele ich.", "Am Samstag ich Tennis spiele."], answer: "Am Samstag spiele ich Tennis.", explanation: "The verb remains second and the subject moves after it." },
  { id: "a114-37", group: REPAIR, type: "choice", prompt: "Transform Sara arbeitet in Köln. Begin with In Köln.", options: ["In Köln Sara arbeitet.", "In Köln arbeitet Sara.", "In Köln Sara Arbeit.", "In Köln arbeiten Sara."], answer: "In Köln arbeitet Sara.", explanation: "Place first, verb second, subject third." },
  { id: "a114-38", group: REPAIR, type: "fill", prompt: "Rewrite with Heute first: Ich koche heute eine Suppe. → ___", answer: ["Heute koche ich eine Suppe.", "Heute koche ich eine Suppe"], explanation: "Move heute to position one, keep koche second, and place ich after the verb." },
  { id: "a114-39", group: REPAIR, type: "fill", prompt: "Rewrite with Im Café first: Wir treffen unsere Freunde im Café. → ___", answer: ["Im Café treffen wir unsere Freunde.", "Im Café treffen wir unsere Freunde"], explanation: "The place phrase moves to position one; treffen stays second." },
  { id: "a114-40", group: REPAIR, type: "choice", prompt: "Which sentence is grammatically correct but emphasises the object?", options: ["Den Film sehe ich heute.", "Den Film ich sehe heute.", "Den Film heute ich sehe.", "Den Film ich heute sehe."], answer: "Den Film sehe ich heute.", explanation: "The object may occupy position one if the conjugated verb stays second." },

  { id: "a114-41", group: TRANSFER, type: "translation", direction: "en-de", prompt: "Translate: Today I am working at home.", answer: ["Heute arbeite ich zu Hause.", "Heute arbeite ich zu Hause"], explanation: "Heute fills position one; arbeite remains position two." },
  { id: "a114-42", group: TRANSFER, type: "translation", direction: "en-de", prompt: "Translate: On Monday the course begins at nine.", answer: ["Am Montag beginnt der Kurs um neun.", "Am Montag beginnt der Kurs um neun"], explanation: "The time phrase is first, the verb second, and the subject follows." },
  { id: "a114-43", group: TRANSFER, type: "translation", direction: "en-de", prompt: "Translate: My sister lives in Berlin.", answer: ["Meine Schwester wohnt in Berlin.", "Meine Schwester wohnt in Berlin"], explanation: "With the subject first, wohnt is the second element." },
  { id: "a114-44", group: TRANSFER, type: "translation", direction: "en-de", prompt: "Translate, beginning with the place: My sister lives in Berlin.", answer: ["In Berlin wohnt meine Schwester.", "In Berlin wohnt meine Schwester"], explanation: "The place occupies position one, so the verb precedes the subject." },
  { id: "a114-45", group: TRANSFER, type: "translation", direction: "de-en", prompt: "Translate into English: Nach der Arbeit kauft Tom ein.", answer: ["After work Tom goes shopping.", "Tom goes shopping after work.", "After work Tom shops."], explanation: "Nach der Arbeit is the opening phrase; kauft … ein is a separable verb." },
  { id: "a114-46", group: TRANSFER, type: "translation", direction: "de-en", prompt: "Translate into English: Manchmal fahre ich mit dem Fahrrad.", answer: ["Sometimes I go by bicycle.", "Sometimes I ride my bike.", "I sometimes travel by bicycle."], explanation: "Manchmal is emphasised in position one; fahre remains second." },
  { id: "a114-47", group: TRANSFER, type: "production", prompt: "Write three sentences about one activity. Begin them with the subject, a time phrase, and a place phrase.", model: "Ich lerne am Abend in der Bibliothek. Am Abend lerne ich in der Bibliothek. In der Bibliothek lerne ich am Abend.", explanation: "Change position one while keeping the conjugated verb in position two." },
  { id: "a114-48", group: TRANSFER, type: "production", prompt: "Write five true sentences beginning with five different time expressions.", model: "Heute arbeite ich zu Hause. Morgen besuche ich Lea. Am Montag lerne ich Deutsch. Nach dem Kurs trinke ich Kaffee. Im Sommer fahre ich ans Meer.", explanation: "Underline the opening phrase and check that the verb follows it directly." },
  { id: "a114-49", group: TRANSFER, type: "production", prompt: "Write four place-first sentences about your town or home.", model: "In meiner Straße gibt es ein Café. Im Zentrum arbeitet meine Schwester. Zu Hause lerne ich Deutsch. Im Park spielen viele Kinder.", explanation: "Each place phrase fills position one; the conjugated verb fills position two." },
  { id: "a114-50", group: TRANSFER, type: "production", prompt: "Write a six-sentence daily routine. Start no more than two sentences with the subject.", model: "Am Morgen mache ich Kaffee. Dann lese ich die Nachrichten. Um acht fahre ich zur Arbeit. Im Büro beantworte ich E-Mails. Nach der Arbeit kaufe ich ein. Zu Hause koche ich das Abendessen.", explanation: "Vary position one while preserving verb-second order in every main clause." },
];
