import type { GrammarExercise } from "@/app/grammar/course";

const FORMS = "1 · ein, eine, and no article";
const USE = "2 · New and specific information";
const CONTEXT = "3 · Articles in context";
const REPAIR = "4 · Building and correcting";
const TRANSFER = "5 · Translation and production";

export const A1_LESSON_EIGHT_EXERCISES: GrammarExercise[] = [
  { id: "a122-01", group: FORMS, type: "choice", prompt: "Which nominative indefinite article goes with a masculine noun?", options: ["ein", "eine", "einen", "no article"], answer: "ein", explanation: "Masculine nominative nouns use ein." },
  { id: "a122-02", group: FORMS, type: "choice", prompt: "Which nominative indefinite article goes with a feminine noun?", options: ["ein", "eine", "einen", "no article"], answer: "eine", explanation: "Feminine nominative nouns use eine." },
  { id: "a122-03", group: FORMS, type: "choice", prompt: "Which nominative indefinite article goes with a neuter noun?", options: ["ein", "eine", "einen", "no article"], answer: "ein", explanation: "Neuter nominative nouns use ein." },
  { id: "a122-04", group: FORMS, type: "choice", prompt: "What is the plural of ein?", options: ["eine", "einen", "eins", "There is no indefinite plural article."], answer: "There is no indefinite plural article.", explanation: "Indefinite plural nouns normally appear without an article: Dort sind Kinder." },
  { id: "a122-05", group: FORMS, type: "choice", prompt: "Choose the correct phrase: ___ Mann", options: ["ein", "eine", "einen", "einem"], answer: "ein", explanation: "Mann is masculine nominative: ein Mann." },
  { id: "a122-06", group: FORMS, type: "choice", prompt: "Choose the correct phrase: ___ Frau", options: ["ein", "eine", "einen", "einem"], answer: "eine", explanation: "Frau is feminine nominative: eine Frau." },
  { id: "a122-07", group: FORMS, type: "choice", prompt: "Choose the correct phrase: ___ Kind", options: ["ein", "eine", "einen", "einem"], answer: "ein", explanation: "Kind is neuter nominative: ein Kind." },
  { id: "a122-08", group: FORMS, type: "choice", prompt: "Choose the indefinite plural: Dort spielen ___ Kinder.", options: ["ein", "eine", "einen", "no article"], answer: "no article", explanation: "German has no plural form of ein." },
  { id: "a122-09", group: FORMS, type: "choice", prompt: "Which pair is correct?", options: ["der → ein", "die → ein", "das → eine", "plural die → eine"], answer: "der → ein", explanation: "Masculine der corresponds to indefinite ein in the nominative." },
  { id: "a122-10", group: FORMS, type: "choice", prompt: "Which sequence matches masculine–feminine–neuter–plural?", options: ["ein–eine–ein–—", "ein–ein–eine–eine", "eine–ein–ein–—", "ein–eine–einen–eine"], answer: "ein–eine–ein–—", explanation: "Only feminine shows -e; indefinite plural has no article." },

  { id: "a122-11", group: USE, type: "choice", prompt: "When do we normally use ein/eine?", options: ["For a newly introduced, non-specific singular noun.", "For every plural noun.", "Only after a name.", "Only in negative sentences."], answer: "For a newly introduced, non-specific singular noun.", explanation: "ein/eine presents one member of a category without identifying a known one." },
  { id: "a122-12", group: USE, type: "choice", prompt: "Choose the natural first mention.", options: ["Dort ist Hund.", "Dort ist ein Hund.", "Dort ist der Hund. (unknown)", "Dort ein Hund ist."], answer: "Dort ist ein Hund.", explanation: "A newly introduced singular count noun uses an indefinite article." },
  { id: "a122-13", group: USE, type: "choice", prompt: "Choose the natural second mention: Dort ist ein Hund. ___ Hund heißt Max.", options: ["Ein", "Eine", "Der", "Kein"], answer: "Der", explanation: "After introduction, the listener knows which dog is meant, so use the definite article." },
  { id: "a122-14", group: USE, type: "choice", prompt: "Which sentence means a doctor, not a known specific doctor?", options: ["Die Ärztin arbeitet hier.", "Eine Ärztin arbeitet hier.", "Ärztin arbeitet hier.", "Ein Ärztin arbeitet hier."], answer: "Eine Ärztin arbeitet hier.", explanation: "The feminine indefinite article introduces one non-specific doctor." },
  { id: "a122-15", group: USE, type: "choice", prompt: "Which sentence naturally introduces several bicycles?", options: ["Dort stehen ein Fahrräder.", "Dort stehen eine Fahrräder.", "Dort stehen Fahrräder.", "Dort steht Fahrräder."], answer: "Dort stehen Fahrräder.", explanation: "Indefinite plural uses no article and a plural verb." },
  { id: "a122-16", group: USE, type: "choice", prompt: "Which noun usually has no article after sein when naming a profession?", options: ["Er ist ein der Lehrer.", "Er ist Lehrer.", "Er ist der ein Lehrer.", "Er Lehrer ist."], answer: "Er ist Lehrer.", explanation: "An unmodified profession after sein commonly appears without an article." },
  { id: "a122-17", group: USE, type: "choice", prompt: "When is an article natural with a profession?", options: ["Never", "When the profession is described or identified", "Only in plural", "Only with sein"], answer: "When the profession is described or identified", explanation: "Use an article with added description: Er ist ein guter Lehrer." },
  { id: "a122-18", group: USE, type: "choice", prompt: "Choose the natural sequence.", options: ["Ein Auto steht draußen. Ein Auto ist rot.", "Ein Auto steht draußen. Das Auto ist rot.", "Das Auto steht draußen. Ein Auto ist rot.", "Auto steht draußen. Der ist rot."], answer: "Ein Auto steht draußen. Das Auto ist rot.", explanation: "Introduce with ein, then refer back with das." },
  { id: "a122-19", group: USE, type: "choice", prompt: "What does eine in Eine Frau wartet mean?", options: ["the known woman", "one/a non-specific woman", "no woman", "several women"], answer: "one/a non-specific woman", explanation: "The indefinite article introduces one woman without identifying her." },
  { id: "a122-20", group: USE, type: "choice", prompt: "Which form negates eine Wohnung?", options: ["nicht Wohnung", "kein Wohnung", "keine Wohnung", "keinen Wohnung"], answer: "keine Wohnung", explanation: "The negative counterpart of feminine eine is keine." },

  { id: "a122-21", group: CONTEXT, type: "fill", prompt: "Das ist ___ Bahnhof.", answer: "ein", explanation: "Bahnhof is masculine nominative: ein Bahnhof." },
  { id: "a122-22", group: CONTEXT, type: "fill", prompt: "Hier arbeitet ___ Ärztin.", answer: "eine", explanation: "Ärztin is feminine nominative: eine Ärztin." },
  { id: "a122-23", group: CONTEXT, type: "fill", prompt: "Im Garten spielt ___ Kind.", answer: "ein", explanation: "Kind is neuter nominative: ein Kind." },
  { id: "a122-24", group: CONTEXT, type: "choice", prompt: "Auf dem Tisch liegen ___ Bücher. (indefinite)", options: ["ein", "eine", "die", "no article"], answer: "no article", explanation: "Indefinite plurals have no article: Auf dem Tisch liegen Bücher." },
  { id: "a122-25", group: CONTEXT, type: "fill", prompt: "Das ist ___ Küche.", answer: "eine", explanation: "Küche is feminine: eine Küche." },
  { id: "a122-26", group: CONTEXT, type: "choice", prompt: "Dort steht ___ Hotel.", options: ["ein", "eine", "einen", "no article"], answer: "ein", explanation: "Hotel is neuter and singular: ein Hotel." },
  { id: "a122-27", group: CONTEXT, type: "choice", prompt: "___ Verkäufer hilft mir.", options: ["Ein", "Eine", "Einen", "No article"], answer: "Ein", explanation: "Verkäufer is masculine nominative: ein Verkäufer." },
  { id: "a122-28", group: CONTEXT, type: "choice", prompt: "___ Verkäuferin hilft mir.", options: ["Ein", "Eine", "Einen", "No article"], answer: "Eine", explanation: "Verkäuferin is feminine nominative: eine Verkäuferin." },
  { id: "a122-29", group: CONTEXT, type: "choice", prompt: "Im Park spielen ___ Kinder. (some children)", options: ["ein", "eine", "die", "no article"], answer: "no article", explanation: "Use no indefinite plural article." },
  { id: "a122-30", group: CONTEXT, type: "choice", prompt: "Mia ist ___. (doctor, profession only)", options: ["eine Ärztin", "Ärztin", "die Ärztin", "ein Ärztin"], answer: "Ärztin", explanation: "An unmodified profession after sein normally has no article." },

  { id: "a122-31", group: REPAIR, type: "order", prompt: "Introduce a new object.", tokens: ["Das", "Regenschirm", "ein", "ist", "."], answer: "Das ist ein Regenschirm.", explanation: "Regenschirm is masculine, so use ein." },
  { id: "a122-32", group: REPAIR, type: "order", prompt: "Introduce a new person.", tokens: ["wartet", "Frau", "Eine", "draußen", "."], answer: "Eine Frau wartet draußen.", explanation: "The feminine indefinite subject is eine Frau." },
  { id: "a122-33", group: REPAIR, type: "order", prompt: "Build the indefinite plural sentence.", tokens: ["Im", "Kinder", "spielen", "Park", "."], answer: "Im Park spielen Kinder.", explanation: "There is no indefinite article before plural Kinder." },
  { id: "a122-34", group: REPAIR, type: "correction", prompt: "Correct: Das ist eine Hotel.", answer: "Das ist ein Hotel.", explanation: "Hotel is neuter: ein Hotel." },
  { id: "a122-35", group: REPAIR, type: "correction", prompt: "Correct: Ein Verkäuferin hilft mir.", answer: "Eine Verkäuferin hilft mir.", explanation: "Verkäuferin is feminine." },
  { id: "a122-36", group: REPAIR, type: "correction", prompt: "Correct: Hier sind eine Bücher.", answer: "Hier sind Bücher.", explanation: "German has no indefinite plural article." },
  { id: "a122-37", group: REPAIR, type: "correction", prompt: "Correct the reference: Dort ist ein Hund. Ein Hund heißt Max.", answer: "Dort ist ein Hund. Der Hund heißt Max.", explanation: "Use the definite article for the now-known second mention." },
  { id: "a122-38", group: REPAIR, type: "correction", prompt: "Correct: Sie ist eine Lehrerin. (profession only)", answer: ["Sie ist Lehrerin.", "Sie ist Lehrerin"], explanation: "The neutral profession statement normally omits the article." },
  { id: "a122-39", group: REPAIR, type: "fill", prompt: "Complete the reference: Ich sehe eine Katze. ___ Katze ist schwarz.", answer: "Die", explanation: "The second sentence refers to the already introduced cat." },
  { id: "a122-40", group: REPAIR, type: "fill", prompt: "Complete the contrast: Das ist kein Büro, sondern ___ Wohnung.", answer: "eine", explanation: "Wohnung is feminine and introduced as the corrected identity." },

  { id: "a122-41", group: TRANSFER, type: "translation", direction: "en-de", prompt: "Translate: That is a train station.", answer: ["Das ist ein Bahnhof.", "Das ist ein Bahnhof"], explanation: "Bahnhof is masculine nominative: ein Bahnhof." },
  { id: "a122-42", group: TRANSFER, type: "translation", direction: "en-de", prompt: "Translate: A doctor works here. (female)", answer: ["Eine Ärztin arbeitet hier.", "Hier arbeitet eine Ärztin."], explanation: "Ärztin is feminine: eine Ärztin." },
  { id: "a122-43", group: TRANSFER, type: "translation", direction: "en-de", prompt: "Translate: A child is playing in the garden.", answer: ["Ein Kind spielt im Garten.", "Im Garten spielt ein Kind."], explanation: "Kind is neuter: ein Kind." },
  { id: "a122-44", group: TRANSFER, type: "translation", direction: "en-de", prompt: "Translate: There are bicycles over there.", answer: ["Dort stehen Fahrräder.", "Dort sind Fahrräder."], explanation: "Use no indefinite article with plural Fahrräder." },
  { id: "a122-45", group: TRANSFER, type: "translation", direction: "de-en", prompt: "Translate: Dort ist ein Café. Das Café ist neu.", answer: ["There is a café there. The café is new.", "A café is over there. The café is new."], explanation: "The first sentence introduces the café; the second identifies it." },
  { id: "a122-46", group: TRANSFER, type: "translation", direction: "de-en", prompt: "Translate: Mein Bruder ist Lehrer.", answer: ["My brother is a teacher.", "My brother is a schoolteacher."], explanation: "German omits the article before an unmodified profession." },
  { id: "a122-47", group: TRANSFER, type: "production", prompt: "Introduce six new people or things with ein/eine.", model: "Dort ist ein Mann. Hier wartet eine Frau. Das ist ein Hotel. Im Garten spielt ein Kind. Eine Ärztin kommt. Ein Bus hält.", explanation: "Use the noun's gender to choose ein or eine." },
  { id: "a122-48", group: TRANSFER, type: "production", prompt: "Write four two-sentence pairs that introduce something and then describe it.", model: "Dort ist ein Hund. Der Hund ist klein. Hier steht eine Lampe. Die Lampe ist neu.", explanation: "Switch from indefinite first mention to definite second mention." },
  { id: "a122-49", group: TRANSFER, type: "production", prompt: "Describe a street scene using three singular and three indefinite plural noun phrases.", model: "Ein Bus kommt. Eine Frau wartet. Ein Kind läuft. Vor dem Café stehen Fahrräder. Im Park spielen Kinder. Auf der Straße fahren Autos.", explanation: "Singular count nouns need ein/eine; indefinite plurals take no article." },
  { id: "a122-50", group: TRANSFER, type: "production", prompt: "Write an eight-sentence mini-story that uses first and second mention correctly.", model: "Vor dem Haus steht ein Auto. Das Auto ist rot. Im Auto sitzt eine Frau. Die Frau liest eine Karte. Neben ihr sitzt ein Kind. Das Kind schläft. Auf dem Dach liegen Taschen. Die Taschen sind groß.", explanation: "Introduce each singular noun indefinitely, then refer back with its definite article." },
];
