import { blueprint, buildGrammarLessons, sample as s, type GrammarBlueprint } from "@/app/grammar/lesson-blueprint";

const blueprints: GrammarBlueprint[] = [
  blueprint({
    id: "a1-4-1",
    lead: "The dative marks a person or thing indirectly involved in an action, especially the receiver with verbs such as geben, helfen, antworten, and gefallen. Its article forms create the foundation for later prepositions and two-object sentences.",
    pattern: "der → dem · die → der · das → dem · plural die → den + noun-n",
    notes: [
      "Ask Wem?—to whom or for whom?—to find a dative person. The subject remains nominative and a directly affected thing can remain accusative.",
      "Masculine and neuter use dem, feminine uses der, and plural uses den. Most plural nouns also add -n unless they already end in -n or -s.",
      "With geben, the receiver is dative and the thing is accusative: Ich gebe dem Kind das Buch. Case, not position alone, identifies each role.",
      "At A1, learn the dative together with high-frequency verbs and phrases. Mark every article and plural ending before trying longer sentences.",
    ],
    forms: [
      ["masculine", "dem / einem", "Ich helfe dem Mann.", "I help the man."],
      ["feminine", "der / einer", "Ich helfe der Frau.", "I help the woman."],
      ["neuter", "dem / einem", "Ich helfe dem Kind.", "I help the child."],
      ["plural", "den + -n", "Ich helfe den Kindern.", "I help the children."],
    ],
    samples: [
      s("Ich helfe dem Mann.", "I help the man.", "Ich helfe ___ Mann. (the)", "dem", "Ich helfe den Mann.", "helfen takes a dative person; masculine der becomes dem."),
      s("Sie antwortet der Lehrerin.", "She answers the teacher.", "Sie antwortet ___ Lehrerin. (the)", "der", "Sie antwortet die Lehrerin.", "antworten takes dative; feminine die becomes der."),
      s("Wir geben dem Kind ein Buch.", "We give the child a book.", "Wir geben ___ Kind ein Buch. (the)", "dem", "Wir geben das Kind ein Buch.", "the receiver is dative dem Kind; the thing remains accusative."),
      s("Das gefällt meiner Mutter.", "My mother likes that.", "Das gefällt ___ Mutter. (my)", "meiner", "Das gefällt meine Mutter.", "gefallen takes a dative experiencer; feminine mein becomes meiner."),
      s("Er hilft den Kindern.", "He helps the children.", "Er hilft ___ Kindern. (the)", "den", "Er hilft die Kinder.", "plural dative uses den and Kinder adds -n."),
      s("Ich danke einem Freund.", "I thank a friend.", "Ich danke ___ Freund. (a)", "einem", "Ich danke einen Freund.", "danken takes dative; masculine ein becomes einem."),
      s("Der Schlüssel gehört der Nachbarin.", "The key belongs to the neighbour.", "Der Schlüssel gehört ___ Nachbarin. (the)", "der", "Der Schlüssel gehört die Nachbarin.", "gehören takes a dative owner."),
      s("Kannst du mir helfen?", "Can you help me?", "Kannst du ___ helfen? (me)", "mir", "Kannst du mich helfen?", "the dative pronoun for ich is mir after helfen."),
      s("Wir zeigen dem Gast das Zimmer.", "We show the guest the room.", "Wir zeigen ___ Gast das Zimmer. (the)", "dem", "Wir zeigen den Gast das Zimmer.", "the person receiving information is dative."),
      s("Die Suppe schmeckt den Gästen.", "The guests like the soup.", "Die Suppe schmeckt ___ Gästen. (the)", "den", "Die Suppe schmeckt die Gäste.", "schmecken takes a dative experiencer; plural uses den."),
    ],
    memoryTip: "Use Wem? for the receiver, then recite dem–der–dem–den. On plural nouns, perform a final -n check.",
  }),
  blueprint({
    id: "a1-4-2",
    lead: "The prepositions mit, nach, bei, seit, von, and zu always require the dative. They express accompaniment, destinations, locations, duration, origin, sources, and movement toward people or services.",
    pattern: "mit · nach · bei · seit · von · zu + dative",
    notes: [
      "These prepositions control case regardless of the sentence's other roles. Once you select one, the following noun phrase must be dative.",
      "Common contractions combine preposition and article: bei dem → beim, von dem → vom, zu dem → zum, and zu der → zur.",
      "Use nach for most cities, countries without articles, and home; use zu for people, businesses, services, and many appointments.",
      "Learn each preposition through useful chunks such as mit dem Bus, nach Hause, beim Arzt, seit einem Jahr, vom Bahnhof, and zur Arbeit.",
    ],
    forms: [
      ["mit", "accompaniment / transport", "mit dem Bus", "by bus"],
      ["nach", "city / country / home", "nach Berlin", "to Berlin"],
      ["bei", "at / with", "beim Arzt", "at the doctor's"],
      ["seit", "since / for", "seit einem Jahr", "for one year"],
      ["von", "from / of", "vom Bahnhof", "from the station"],
      ["zu", "to a person/service", "zur Apotheke", "to the pharmacy"],
    ],
    samples: [
      s("Ich fahre mit dem Bus.", "I travel by bus.", "Ich fahre mit ___ Bus. (the)", "dem", "Ich fahre mit den Bus.", "mit always takes dative; Bus is masculine."),
      s("Wir fliegen nach Berlin.", "We are flying to Berlin.", "Wir fliegen ___ Berlin.", "nach", "Wir fliegen zu Berlin.", "use nach with a city name."),
      s("Mia ist beim Arzt.", "Mia is at the doctor's.", "Mia ist ___ Arzt. (bei + dem)", "beim", "Mia ist bei den Arzt.", "beim is the contraction of bei dem."),
      s("Er lernt seit einem Monat Deutsch.", "He has been learning German for a month.", "Er lernt seit ___ Monat Deutsch. (a)", "einem", "Er lernt seit einen Monat Deutsch.", "seit always takes dative."),
      s("Der Bus kommt vom Bahnhof.", "The bus comes from the station.", "Der Bus kommt ___ Bahnhof. (von + dem)", "vom", "Der Bus kommt von den Bahnhof.", "vom contracts von dem."),
      s("Ich gehe zur Apotheke.", "I am going to the pharmacy.", "Ich gehe ___ Apotheke. (zu + der)", "zur", "Ich gehe zu die Apotheke.", "zur contracts zu der."),
      s("Kommst du mit deiner Schwester?", "Are you coming with your sister?", "Kommst du mit ___ Schwester? (your)", "deiner", "Kommst du mit deine Schwester?", "feminine possessive takes -er after mit."),
      s("Nach dem Kurs gehe ich nach Hause.", "After the course I go home.", "Nach ___ Kurs gehe ich nach Hause. (the)", "dem", "Nach den Kurs gehe ich zu Hause.", "nach takes dative; nach Hause expresses direction home."),
      s("Wir wohnen bei unseren Eltern.", "We live with our parents.", "Wir wohnen bei ___ Eltern. (our)", "unseren", "Wir wohnen bei unsere Eltern.", "plural dative possessive takes -en."),
      s("Sie fährt zum Flughafen.", "She is travelling to the airport.", "Sie fährt ___ Flughafen. (zu + dem)", "zum", "Sie fährt zu der Flughafen.", "Flughafen is masculine; zu dem contracts to zum."),
    ],
    memoryTip: "Chant mit–nach–bei–seit–von–zu, then attach one personal phrase to each. The preposition decides dative before anything else.",
  }),
  blueprint({
    id: "a1-4-3",
    lead: "Two-way prepositions describe spatial relationships. When the sentence answers Wo? and presents a stable location, an, auf, hinter, in, neben, über, unter, vor, and zwischen take the dative.",
    pattern: "Wo? → an/auf/hinter/in/neben/über/unter/vor/zwischen + dative",
    notes: [
      "Start with meaning: Wo? asks where something is located. A location without movement toward a new destination selects the dative.",
      "The article system follows ordinary dative forms. Common contractions are in dem → im and an dem → am.",
      "A verb can describe activity and still express location: Die Kinder spielen im Park. The key question is whether a destination or change of place is presented.",
      "Learn each preposition with a small spatial picture and a contrasting noun. Say the complete phrase aloud rather than memorising a translation alone.",
    ],
    forms: [
      ["in", "inside", "im Zimmer", "in the room"],
      ["auf", "on a surface", "auf dem Tisch", "on the table"],
      ["an", "at / on a boundary", "an der Wand", "on the wall"],
      ["unter / über", "below / above", "unter dem Bett", "under the bed"],
      ["vor / hinter", "in front / behind", "vor dem Haus", "in front of the house"],
      ["neben / zwischen", "beside / between", "neben der Tür", "beside the door"],
    ],
    samples: [
      s("Das Buch liegt auf dem Tisch.", "The book is lying on the table.", "Das Buch liegt auf ___ Tisch. (the)", "dem", "Das Buch liegt auf den Tisch.", "Wo? indicates location, so auf takes dative."),
      s("Die Jacke hängt an der Tür.", "The jacket is hanging on the door.", "Die Jacke hängt an ___ Tür. (the)", "der", "Die Jacke hängt an die Tür.", "a stable position answers Wo? and takes dative."),
      s("Wir sind im Wohnzimmer.", "We are in the living room.", "Wir sind ___ Wohnzimmer. (in + dem)", "im", "Wir sind in das Wohnzimmer.", "im contracts in dem for location."),
      s("Der Hund schläft unter dem Bett.", "The dog is sleeping under the bed.", "Der Hund schläft unter ___ Bett. (the)", "dem", "Der Hund schläft unter das Bett.", "sleeping describes a stable location."),
      s("Das Auto steht vor dem Haus.", "The car is parked in front of the house.", "Das Auto steht vor ___ Haus. (the)", "dem", "Das Auto steht vor das Haus.", "stehen answers Wo? and requires dative here."),
      s("Die Apotheke ist neben der Bank.", "The pharmacy is beside the bank.", "Die Apotheke ist neben ___ Bank. (the)", "der", "Die Apotheke ist neben die Bank.", "sein presents location; feminine dative is der."),
      s("Die Lampe hängt über dem Tisch.", "The lamp is hanging above the table.", "Die Lampe hängt über ___ Tisch. (the)", "dem", "Die Lampe hängt über den Tisch.", "the lamp remains in a location above the table."),
      s("Mia wartet hinter dem Bahnhof.", "Mia is waiting behind the station.", "Mia wartet hinter ___ Bahnhof. (the)", "dem", "Mia wartet hinter den Bahnhof.", "waiting is stationary and answers Wo?"),
      s("Der Stuhl steht zwischen den Fenstern.", "The chair stands between the windows.", "Der Stuhl steht zwischen ___ Fenstern. (the)", "den", "Der Stuhl steht zwischen die Fenster.", "plural dative uses den; Fenster already ends in -n."),
      s("Am Fenster steht eine Pflanze.", "A plant stands by the window.", "___ Fenster steht eine Pflanze. (an + dem)", "Am", "An das Fenster steht eine Pflanze.", "am contracts an dem for a fixed location."),
    ],
    memoryTip: "Ask Wo? first. If the answer is a position rather than a destination, choose dative and then build the spatial phrase.",
  }),
  blueprint({
    id: "a1-4-4",
    lead: "German time expressions answer when, how often, how long, and from when to when. A small set of prepositions and adverbs lets you place everyday events precisely without changing the basic verb-second structure.",
    pattern: "am + day/date · um + clock time · im + month/season · von … bis · seit + dative",
    notes: [
      "Use um for exact clock times, am for days and parts of the day, and im for months and seasons. Nacht is the common exception: in der Nacht.",
      "Frequency adverbs such as immer, oft, manchmal, selten, and nie normally stand in the middle field and do not change verb agreement.",
      "A time expression can occupy position one for emphasis. The conjugated verb remains second, so the subject follows it: Am Montag arbeite ich.",
      "Use seit with a starting point that continues to the present, and von … bis for a bounded range. German often uses the present tense where English uses a perfect form.",
    ],
    forms: [
      ["um", "exact time", "um acht Uhr", "at eight o'clock"],
      ["am", "day / date", "am Montag", "on Monday"],
      ["im", "month / season", "im August", "in August"],
      ["von … bis", "time range", "von neun bis fünf", "from nine to five"],
      ["seit", "continuing duration", "seit einem Jahr", "for one year"],
      ["frequency", "how often", "Ich lerne oft.", "I often study."],
    ],
    samples: [
      s("Der Kurs beginnt um neun Uhr.", "The course begins at nine o'clock.", "Der Kurs beginnt ___ neun Uhr.", "um", "Der Kurs beginnt am neun Uhr.", "exact clock times use um."),
      s("Am Montag arbeite ich zu Hause.", "On Monday I work from home.", "___ Montag arbeite ich zu Hause.", "Am", "Im Montag arbeite ich zu Hause.", "days use am; the verb remains second."),
      s("Wir fahren im August nach Berlin.", "We are travelling to Berlin in August.", "Wir fahren ___ August nach Berlin.", "im", "Wir fahren am August nach Berlin.", "months use im."),
      s("Die Praxis ist von acht bis zwölf geöffnet.", "The clinic is open from eight to twelve.", "Die Praxis ist ___ acht ___ zwölf geöffnet.", "von bis", "Die Praxis ist seit acht um zwölf geöffnet.", "von … bis marks a bounded range."),
      s("Ich lerne seit einem Jahr Deutsch.", "I have been learning German for a year.", "Ich lerne seit ___ Jahr Deutsch. (a)", "einem", "Ich lernte für ein Jahr Deutsch.", "seit takes dative and a present tense for an ongoing duration."),
      s("Mia geht jeden Morgen spazieren.", "Mia goes for a walk every morning.", "Mia geht ___ Morgen spazieren. (every)", "jeden", "Mia geht jeder Morgen spazieren.", "repeated masculine accusative time uses jeden Morgen."),
      s("Wir treffen uns zweimal pro Woche.", "We meet twice per week.", "Wir treffen uns ___ pro Woche. (twice)", "zweimal", "Wir treffen uns zwei Malen pro Woche.", "zweimal is the standard frequency adverb."),
      s("Er kommt manchmal zu spät.", "He sometimes arrives late.", "Er kommt ___ zu spät. (sometimes)", "manchmal", "Er manchmal kommt zu spät.", "the frequency adverb belongs in the middle field."),
      s("In der Nacht ist es ruhig.", "It is quiet at night.", "___ Nacht ist es ruhig. (in the)", "In der", "Am Nacht ist es ruhig.", "Nacht commonly uses in der, not am."),
      s("Wie lange bleibst du?", "How long are you staying?", "___ bleibst du? (how long)", "Wie lange", "Wann lange bleibst du?", "Wie lange asks for duration."),
    ],
    memoryTip: "Sort time into four questions: exact time, calendar time, frequency, or duration. Then choose um, am/im, an adverb, or seit/von–bis.",
  }),
  blueprint({
    id: "a1-4-5",
    lead: "Coordinating conjunctions join equal words, phrases, or complete clauses without pushing the verb to the end. und adds, aber contrasts, oder offers alternatives, and denn gives a reason.",
    pattern: "clause + und/aber/oder/denn + subject + finite verb + …",
    notes: [
      "A coordinating conjunction connects elements of equal grammatical status. When it joins two full clauses, each clause keeps normal main-clause word order.",
      "und and oder can connect single words without repeating the entire sentence. aber and denn often connect full ideas and require a clear logical relationship.",
      "The conjunction occupies position zero: it does not count as the first sentence element. After it, a subject can stand first and the conjugated verb remains second.",
      "Use denn for a reason with main-clause order. This contrasts with weil, introduced at A2, which sends the finite verb to the end.",
    ],
    forms: [
      ["und", "addition", "Ich lerne und arbeite.", "I study and work."],
      ["aber", "contrast", "Er kommt, aber er bleibt nicht.", "He comes, but he does not stay."],
      ["oder", "alternative", "Tee oder Kaffee?", "Tea or coffee?"],
      ["denn", "reason", "Ich gehe, denn ich bin müde.", "I am leaving because I am tired."],
    ],
    samples: [
      s("Mia lernt Deutsch und Tom lernt Englisch.", "Mia studies German and Tom studies English.", "Mia lernt Deutsch ___ Tom lernt Englisch.", "und", "Mia lernt Deutsch und lernt Tom Englisch.", "each full clause keeps subject–verb order after und."),
      s("Ich bin müde, aber ich arbeite noch.", "I am tired, but I am still working.", "Ich bin müde, ___ ich arbeite noch.", "aber", "Ich bin müde, aber arbeite ich noch.", "aber is position zero; the second clause remains ich arbeite."),
      s("Möchtest du Tee oder Kaffee?", "Would you like tea or coffee?", "Möchtest du Tee ___ Kaffee?", "oder", "Möchtest du Tee aber Kaffee?", "oder presents alternatives."),
      s("Wir bleiben zu Hause, denn es regnet.", "We are staying home because it is raining.", "Wir bleiben zu Hause, ___ es regnet.", "denn", "Wir bleiben zu Hause, denn regnet es.", "denn introduces a reason with normal main-clause order."),
      s("Er kocht und hört Musik.", "He cooks and listens to music.", "Er kocht ___ hört Musik.", "und", "Er kocht und er Musik hört.", "a shared subject does not need to be repeated."),
      s("Der Film ist lang, aber interessant.", "The film is long but interesting.", "Der Film ist lang, ___ interessant.", "aber", "Der Film ist lang, denn interessant.", "aber can contrast adjectives inside one clause."),
      s("Kommst du heute oder bleibst du zu Hause?", "Are you coming today or staying at home?", "Kommst du heute ___ bleibst du zu Hause?", "oder", "Kommst du heute oder du bleibst zu Hause?", "two coordinated questions retain question word order."),
      s("Ich nehme den Bus, denn mein Auto ist kaputt.", "I am taking the bus because my car is broken.", "Ich nehme den Bus, ___ mein Auto ist kaputt.", "denn", "Ich nehme den Bus, denn ist mein Auto kaputt.", "the reason clause after denn has subject then verb."),
      s("Sie spricht langsam und deutlich.", "She speaks slowly and clearly.", "Sie spricht langsam ___ deutlich.", "und", "Sie spricht langsam oder deutlich.", "und combines two compatible manner descriptions."),
      s("Wir wollen kommen, aber wir müssen arbeiten.", "We want to come, but we have to work.", "Wir wollen kommen, ___ wir müssen arbeiten.", "aber", "Wir wollen kommen, aber müssen wir arbeiten.", "the second modal remains in position two after its subject."),
    ],
    memoryTip: "Treat und, aber, oder, and denn as position zero. Start a new normal main clause after them unless the subject is deliberately shared.",
  }),
  blueprint({
    id: "a1-4-6",
    lead: "The perfect tense reports completed events in everyday spoken German. It combines a present-tense form of haben or sein with a past participle placed at the end of the clause.",
    pattern: "haben/sein in position two + past participle at the end",
    notes: [
      "Most verbs form the perfect with haben. Verbs describing movement from one place to another or a change of state often use sein, as do sein, bleiben, and werden.",
      "Regular participles normally use ge- + stem + -t. Verbs ending in -ieren and inseparable verbs do not add ge-. Separable verbs place ge between prefix and stem.",
      "The auxiliary is the conjugated verb and obeys position-two or question rules. The participle closes the clause: Heute habe ich lange gearbeitet.",
      "Many frequent verbs have irregular participles that must be learned as a three-part entry: infinitive, auxiliary, participle—gehen, ist gegangen; sehen, hat gesehen.",
    ],
    forms: [
      ["regular", "ge- + stem + -t", "machen → gemacht", "made"],
      ["irregular", "often ge- + -en", "sehen → gesehen", "seen"],
      ["separable", "prefix + ge + stem", "einkaufen → eingekauft", "shopped"],
      ["inseparable", "no ge-", "besuchen → besucht", "visited"],
      ["-ieren", "no ge-", "studieren → studiert", "studied"],
      ["movement/change", "often sein", "gehen → ist gegangen", "went"],
    ],
    samples: [
      s("Ich habe gestern gearbeitet.", "I worked yesterday.", "Ich habe gestern ___. (arbeiten)", "gearbeitet", "Ich bin gestern gearbeitet.", "arbeiten uses haben and the regular participle gearbeitet."),
      s("Mia hat einen Kuchen gemacht.", "Mia made a cake.", "Mia hat einen Kuchen ___. (machen)", "gemacht", "Mia hat einen Kuchen gemachen.", "machen forms the regular participle gemacht."),
      s("Wir sind nach Berlin gefahren.", "We travelled to Berlin.", "Wir ___ nach Berlin gefahren. (sein)", "sind", "Wir haben nach Berlin gefahren.", "directed movement with fahren normally uses sein."),
      s("Er ist früh aufgestanden.", "He got up early.", "Er ist früh ___. (aufstehen)", "aufgestanden", "Er hat früh geaufstanden.", "aufstehen uses sein and inserts ge after the prefix."),
      s("Hast du den Film gesehen?", "Did you see the film?", "Hast du den Film ___? (sehen)", "gesehen", "Bist du den Film gesehen?", "sehen uses haben and the irregular participle gesehen."),
      s("Sie hat ihre Freundin besucht.", "She visited her friend.", "Sie hat ihre Freundin ___. (besuchen)", "besucht", "Sie hat ihre Freundin gebesucht.", "inseparable be- prevents ge-."),
      s("Ich habe im Supermarkt eingekauft.", "I shopped at the supermarket.", "Ich habe im Supermarkt ___. (einkaufen)", "eingekauft", "Ich habe im Supermarkt geeinkauft.", "separable einkaufen inserts ge between prefix and stem."),
      s("Die Kinder sind eingeschlafen.", "The children fell asleep.", "Die Kinder ___ eingeschlafen. (sein)", "sind", "Die Kinder haben eingeschlafen.", "a change of state with einschlafen uses sein."),
      s("Wir haben lange telefoniert.", "We talked on the phone for a long time.", "Wir haben lange ___. (telefonieren)", "telefoniert", "Wir haben lange getelefoniert.", "verbs ending in -ieren do not add ge-."),
      s("Wann bist du angekommen?", "When did you arrive?", "Wann ___ du angekommen? (sein)", "bist", "Wann hast du angekommt?", "ankommen uses sein and the participle angekommen."),
    ],
    memoryTip: "Store every new past form as a three-part unit: infinitive – auxiliary – participle. Then build a bracket with the auxiliary left and participle right.",
  }),
];

export const A1_MODULE_FOUR_LESSONS = buildGrammarLessons(blueprints);
