import { buildGrammarLessons, quickBlueprint as q, sample as s, type GrammarBlueprint } from "@/app/grammar/lesson-blueprint";

const blueprints: GrammarBlueprint[] = [
  q({ id:"a2-3-1", lead:"The perfect tense is the main spoken past for completed events. Accurate narration requires the correct auxiliary, participle pattern, and sentence bracket.", pattern:"haben/sein + Partizip II", notes:["Most verbs take haben; directed movement and change of state often take sein.","Regular, irregular, separable, inseparable, and -ieren verbs form participles differently.","The auxiliary is finite and the participle closes the clause.","Learn every verb as infinitive–auxiliary–participle."], samples:[
    s("Ich habe gestern lange gearbeitet.","I worked for a long time yesterday.","Ich habe gestern lange ___. (arbeiten)","gearbeitet","Ich bin gestern lange gearbeitet.","arbeiten uses haben and gearbeitet."),
    s("Wir sind nach Hause gegangen.","We went home.","Wir ___ nach Hause gegangen.","sind","Wir haben nach Hause gegangen.","directed movement with gehen uses sein."),
    s("Sie hat ihre Mutter angerufen.","She called her mother.","Sie hat ihre Mutter ___. (anrufen)","angerufen","Sie hat ihre Mutter geanruft.","anrufen forms the irregular separable participle angerufen."),
    s("Er hat in Berlin studiert.","He studied in Berlin.","Er hat in Berlin ___. (studieren)","studiert","Er hat in Berlin gestudiert.","-ieren verbs do not add ge-."),
    s("Wann bist du angekommen?","When did you arrive?","Wann ___ du angekommen?","bist","Wann hast du angekommt?","ankommen uses sein and angekommen."),
  ], memoryTip:"Store auxiliary and participle together, then hold the participle until the right edge of the clause." }),
  q({ id:"a2-3-2", lead:"sein, haben, and modal verbs commonly use the preterite even in conversation. Their compact past forms avoid long perfect constructions.", pattern:"war/hatte/konnte/musste/wollte/durfte/sollte", notes:["sein and haben use war and hatte stems.","Modal preterites lose their umlaut and take regular past endings.","With a second verb, the modal preterite is finite and the infinitive remains final.","Use context and time phrases to anchor past meaning."], samples:[
    s("Ich war gestern krank.","I was ill yesterday.","Ich ___ gestern krank. (sein)","war","Ich bin gestern krank gewesen.","war is the common conversational preterite of sein."),
    s("Wir hatten keine Zeit.","We had no time.","Wir ___ keine Zeit. (haben)","hatten","Wir haben keine Zeit gehabt.","hatten is the compact preterite of haben."),
    s("Sie musste lange arbeiten.","She had to work for a long time.","Sie ___ lange arbeiten. (müssen)","musste","Sie gemusst lange arbeiten.","modal preterite is finite; arbeiten remains final."),
    s("Konntest du kommen?","Were you able to come?","___ du kommen? (können)","Konntest","Könntest du kommen gestern?","past ability uses konnte without an umlaut."),
    s("Die Kinder durften draußen spielen.","The children were allowed to play outside.","Die Kinder ___ draußen spielen. (dürfen)","durften","Die Kinder dürften draußen gespielt.","durften expresses past permission."),
  ], memoryTip:"Remember war, hatte, and modal stem + -te without an umlaut; keep any second action as a final infinitive." }),
  q({ id:"a2-3-3", lead:"German often uses the present tense for scheduled plans and werden + infinitive for predictions, promises, or emphasis on future meaning.", pattern:"present + future time · werden + infinitive", notes:["Use the present when a time phrase makes the plan clear.","Use werden + infinitive for predictions, promises, and less settled future statements.","Conjugated werden stands in position two and the infinitive closes the clause.","Do not overuse werden where a natural present-tense plan is clearer."], samples:[
    s("Morgen fahre ich nach Hamburg.","Tomorrow I am travelling to Hamburg.","Morgen ___ ich nach Hamburg. (fahren)","fahre","Morgen werde ich nach Hamburg gefahren.","a scheduled plan naturally uses present tense."),
    s("Es wird morgen regnen.","It will rain tomorrow.","Es ___ morgen regnen.","wird","Es werden morgen regnen.","a prediction uses wird + infinitive."),
    s("Wir werden dir helfen.","We will help you.","Wir ___ dir helfen.","werden","Wir werden dir geholfen.","a promise uses werden and final infinitive."),
    s("Wann wirst du zurückkommen?","When will you come back?","Wann ___ du zurückkommen?","wirst","Wann du wirst zurückkommen?","werden follows the W-word and zurückkommen remains final."),
    s("Der Kurs beginnt nächste Woche.","The course starts next week.","Der Kurs ___ nächste Woche. (beginnen)","beginnt","Der Kurs wird nächste Woche beginnt.","a fixed timetable uses present tense."),
  ], memoryTip:"Prefer present + clear future time for plans; choose werden when prediction, promise, or future emphasis matters." }),
  q({ id:"a2-3-4", lead:"weil, da, and dass introduce subordinate clauses and send the finite verb to the end. weil/da give reasons; dass introduces reported facts, thoughts, and statements.", pattern:"main clause, weil/da/dass + … + finite verb", notes:["The connector occupies position zero inside the subordinate clause and the finite verb goes last.","weil is the everyday reason connector; da often presents an already known reason.","dass completes verbs of saying, knowing, thinking, hoping, and feeling.","A subordinate clause placed first counts as position one, so the main-clause verb follows the comma."], samples:[
    s("Ich bleibe zu Hause, weil ich krank bin.","I am staying home because I am ill.","Ich bleibe zu Hause, weil ich krank ___.","bin","Ich bleibe zu Hause, weil ich bin krank.","weil sends the finite verb to the end."),
    s("Da es regnet, nehmen wir den Bus.","Since it is raining, we are taking the bus.","Da es regnet, ___ wir den Bus.","nehmen","Da es regnet, wir nehmen den Bus.","a first-position subordinate clause triggers inversion in the main clause."),
    s("Ich weiß, dass du heute arbeitest.","I know that you are working today.","Ich weiß, dass du heute ___.","arbeitest","Ich weiß, dass arbeitest du heute.","dass sends the finite verb to the end."),
    s("Sie sagt, dass sie später kommt.","She says that she is coming later.","Sie sagt, dass sie später ___.","kommt","Sie sagt, sie dass später kommt.","dass introduces the reported content."),
    s("Wir hoffen, dass der Zug pünktlich ist.","We hope that the train is punctual.","Wir hoffen, dass der Zug pünktlich ___.","ist","Wir hoffen, dass ist der Zug pünktlich.","the finite verb closes the dass-clause."),
  ], memoryTip:"Circle weil, da, or dass; draw an arrow to the final verb; after a first-position subordinate clause, put the main verb immediately after the comma." }),
  q({ id:"a2-3-5", lead:"wenn introduces repeated events, present/future conditions, and whenever situations; als introduces one-time events or periods in the past.", pattern:"wenn = repeated/condition · als = one-time past", notes:["Choose by time and repetition, not by one English word 'when'.","wenn handles present, future, conditions, and repeated past events.","als handles one completed past event or past period.","Both are subordinate connectors and send the finite verb to the end."], samples:[
    s("Wenn ich Zeit habe, lese ich.","When I have time, I read.","Wenn ich Zeit ___, lese ich.","habe","Wenn ich habe Zeit, lese ich.","a recurring present situation uses wenn and final verb."),
    s("Wenn es morgen regnet, bleiben wir zu Hause.","If it rains tomorrow, we will stay home.","Wenn es morgen regnet, ___ wir zu Hause.","bleiben","Wenn es morgen regnet, wir bleiben zu Hause.","a condition uses wenn; the main verb follows the comma."),
    s("Als ich zehn war, wohnte ich in Bonn.","When I was ten, I lived in Bonn.","___ ich zehn war, wohnte ich in Bonn.","Als","Wenn ich zehn war, wohnte ich in Bonn.","a one-time past period uses als."),
    s("Immer wenn er kam, brachte er Blumen.","Whenever he came, he brought flowers.","Immer ___ er kam, brachte er Blumen.","wenn","Immer als er kam, brachte er Blumen.","repeated past events use wenn."),
    s("Als der Zug ankam, wartete Mia schon.","When the train arrived, Mia was already waiting.","___ der Zug ankam, wartete Mia schon.","Als","Wann der Zug ankam, wartete Mia schon.","a single completed past event uses als."),
  ], memoryTip:"Ask two questions: Is it past? Did it happen once? Only two yes answers select als; otherwise use wenn." }),
  q({ id:"a2-3-6", lead:"Indirect questions embed a question inside a statement or polite request. W-words remain for information questions; ob introduces yes/no questions, and the finite verb moves to the end.", pattern:"Können Sie sagen, wann … kommt? · Ich weiß nicht, ob … kommt.", notes:["Retain the original W-word when information is missing.","Use ob when the embedded answer would be yes or no.","Indirect questions are subordinate clauses with a final finite verb.","They soften requests and connect uncertainty or knowledge to a complete question."], samples:[
    s("Können Sie mir sagen, wann der Zug kommt?","Can you tell me when the train arrives?","Können Sie mir sagen, wann der Zug ___?","kommt","Können Sie mir sagen, wann kommt der Zug?","the indirect W-question has a final verb."),
    s("Ich weiß nicht, ob er heute arbeitet.","I do not know whether he is working today.","Ich weiß nicht, ___ er heute arbeitet.","ob","Ich weiß nicht, arbeitet er heute.","a yes/no indirect question uses ob."),
    s("Weißt du, wo Mia wohnt?","Do you know where Mia lives?","Weißt du, wo Mia ___?","wohnt","Weißt du, wo wohnt Mia?","the W-word remains and the verb moves last."),
    s("Sie fragt, wie viel das kostet.","She asks how much that costs.","Sie fragt, wie viel das ___.","kostet","Sie fragt, wie viel kostet das.","the embedded question has statement-like subject placement and final verb."),
    s("Ich möchte wissen, ob ein Zimmer frei ist.","I would like to know whether a room is available.","Ich möchte wissen, ob ein Zimmer frei ___.","ist","Ich möchte wissen, ob ist ein Zimmer frei.","ob introduces the yes/no content and ist closes it."),
  ], memoryTip:"Keep a W-word if one exists; otherwise choose ob. Then move the finite verb to the end of the embedded question." }),
  q({ id:"a2-4-1", lead:"Infinitive clauses with zu connect two actions economically when their understood subject is the same or the construction controls an infinitive.", pattern:"verb/adjective/noun + zu + infinitive", notes:["Use zu before a simple infinitive and insert it inside separable verbs.","Do not use zu after modal verbs or common movement verbs in simple combinations.","The infinitive clause normally stands at the end and is often separated by a comma when expanded.","Learn controlling expressions such as versuchen, vergessen, planen, Zeit haben, and wichtig sein."], samples:[
    s("Ich versuche, mehr Deutsch zu sprechen.","I try to speak more German.","Ich versuche, mehr Deutsch ___ sprechen.","zu","Ich versuche, mehr Deutsch sprechen zu.","zu stands directly before a simple infinitive."),
    s("Er hat vergessen, mich anzurufen.","He forgot to call me.","Er hat vergessen, mich ___. (anrufen)","anzurufen","Er hat vergessen, mich zu anrufen.","separable anrufen inserts zu: anzurufen."),
    s("Wir planen, früher aufzustehen.","We plan to get up earlier.","Wir planen, früher ___. (aufstehen)","aufzustehen","Wir planen, früher zu aufstehen.","separable aufstehen becomes aufzustehen."),
    s("Es ist wichtig, genug zu schlafen.","It is important to sleep enough.","Es ist wichtig, genug ___ schlafen.","zu","Es ist wichtig, genug schlafen.","an adjective construction requires zu + infinitive."),
    s("Ich muss heute arbeiten.","I have to work today.","Ich muss heute ___.","arbeiten","Ich muss heute zu arbeiten.","modal verbs take a bare infinitive without zu."),
  ], memoryTip:"Check whether the controlling expression requires zu; place it before a simple infinitive or between prefix and stem in a separable verb." }),
  q({ id:"a2-4-2", lead:"um … zu and damit express purpose. um … zu is compact when both actions share a subject; damit uses a full subordinate clause and allows a different subject.", pattern:"same subject: um … zu · different subject: damit + final verb", notes:["Compare the subjects of action and purpose before choosing the connector.","um opens the purpose phrase and zu marks the final infinitive.","damit introduces a subordinate clause with its own subject and final finite verb.","A comma separates either purpose construction from the main clause."], samples:[
    s("Ich lerne Deutsch, um in Berlin zu arbeiten.","I learn German in order to work in Berlin.","Ich lerne Deutsch, ___ in Berlin zu arbeiten.","um","Ich lerne Deutsch, damit in Berlin zu arbeiten.","the same subject allows um … zu."),
    s("Mia spricht langsam, damit ich sie verstehe.","Mia speaks slowly so that I understand her.","Mia spricht langsam, ___ ich sie verstehe.","damit","Mia spricht langsam, um ich sie verstehe.","different subjects require damit."),
    s("Wir fahren früh los, um pünktlich anzukommen.","We leave early to arrive on time.","Wir fahren früh los, um pünktlich ___. (ankommen)","anzukommen","Wir fahren früh los um pünktlich zu ankommen.","separable ankommen inserts zu and needs a comma."),
    s("Ich schreibe es auf, damit du es nicht vergisst.","I write it down so that you do not forget it.","Ich schreibe es auf, damit du es nicht ___.","vergisst","Ich schreibe es auf, um du es nicht vergisst.","the purpose has subject du, so use damit."),
    s("Sie spart Geld, um eine Reise zu machen.","She saves money in order to take a trip.","Sie spart Geld, um eine Reise ___ machen.","zu","Sie spart Geld damit eine Reise zu machen.","same subject uses um … zu with comma."),
  ], memoryTip:"Compare subjects: same subject chooses um … zu; different subject chooses damit plus a complete verb-final clause." }),
  q({ id:"a2-4-3", lead:"Sentences with both dative and accusative objects follow strong ordering tendencies. Case identifies the roles; pronoun status determines the most natural sequence.", pattern:"noun+noun: dative before accusative · pronoun+noun: pronoun first · pronoun+pronoun: accusative before dative", notes:["Identify receiver as dative and thing as accusative before arranging them.","With two nouns, the dative person normally precedes the accusative thing.","A personal pronoun usually comes before a noun object.","With two pronouns, accusative normally precedes dative: Ich gebe es ihm."], samples:[
    s("Ich gebe dem Kind das Buch.","I give the child the book.","Ich gebe ___ Kind das Buch. (the)","dem","Ich gebe das Buch dem Kind.","neutral noun order places dative receiver before accusative thing."),
    s("Ich gebe ihm das Buch.","I give him the book.","Ich gebe ___ das Buch. (him)","ihm","Ich gebe das Buch ihm.","a dative pronoun comes before a noun object."),
    s("Ich gebe es dem Kind.","I give it to the child.","Ich gebe ___ dem Kind. (it)","es","Ich gebe dem Kind es.","an accusative pronoun comes before a noun object."),
    s("Ich gebe es ihm.","I give it to him.","Ich gebe ___ ihm. (it)","es","Ich gebe ihm es.","with two pronouns, accusative precedes dative."),
    s("Die Lehrerin erklärt den Schülern die Aufgabe.","The teacher explains the task to the pupils.","Die Lehrerin erklärt ___ Schülern die Aufgabe. (the)","den","Die Lehrerin erklärt die Schüler die Aufgabe.","the receiver is plural dative den Schülern."),
  ], memoryTip:"Mark DAT and AKK first. Then apply: pronouns early; two nouns DAT–AKK; two pronouns AKK–DAT." }),
  q({ id:"a2-4-4", lead:"The time–manner–place tendency organizes the German middle field. It is a neutral default, not an unbreakable law, and pronouns or emphasis can alter the order.", pattern:"time → manner → place", notes:["Place known short pronouns early before the full adverbial sequence.","Time answers when, manner how/with what, and place where/where to.","Choose the neutral sequence first, then move one element to position one for emphasis.","Keep the finite verb second and any infinitive, participle, or prefix at the right edge."], samples:[
    s("Ich fahre morgen mit dem Bus nach Berlin.","I travel to Berlin by bus tomorrow.","Ich fahre ___ mit dem Bus nach Berlin. (tomorrow)","morgen","Ich fahre nach Berlin mit dem Bus morgen.","neutral order is time–manner–place."),
    s("Wir lernen abends gemeinsam in der Bibliothek.","We study together in the library in the evenings.","Wir lernen abends ___ in der Bibliothek. (together)","gemeinsam","Wir lernen in der Bibliothek gemeinsam abends.","time precedes manner and place."),
    s("Mia ist gestern schnell nach Hause gegangen.","Mia went home quickly yesterday.","Mia ist gestern ___ nach Hause gegangen.","schnell","Mia ist nach Hause gestern schnell gegangen.","the participle stays final after time–manner–place."),
    s("Morgen fahre ich mit meiner Schwester zum Arzt.","Tomorrow I go to the doctor with my sister.","Morgen ___ ich mit meiner Schwester zum Arzt.","fahre","Morgen ich fahre mit meiner Schwester zum Arzt.","a time-first phrase is followed immediately by the finite verb."),
    s("Ich muss heute wegen des Wetters zu Hause bleiben.","I have to stay home today because of the weather.","Ich muss heute wegen des Wetters zu Hause ___.","bleiben","Ich muss zu Hause bleiben heute wegen des Wetters.","the infinitive closes the clause after the middle field."),
  ], memoryTip:"Label chunks T, M, and P, arrange them neutrally, then check verb-second and the right sentence bracket." }),
  q({ id:"a2-4-5", lead:"deshalb, trotzdem, and sonst connect independent clauses while occupying position one of the new clause. The finite verb must follow immediately.", pattern:"cause, deshalb + verb + subject · contrast, trotzdem + verb + subject · condition, sonst + verb + subject", notes:["These are connective adverbs, not coordinating conjunctions.","deshalb gives a consequence; trotzdem gives an unexpected contrast; sonst gives an alternative consequence.","Because the connector fills position one, the new clause uses inversion.","Use punctuation to separate the independent clauses clearly."], samples:[
    s("Es regnet, deshalb nehme ich den Bus.","It is raining, so I take the bus.","Es regnet, deshalb ___ ich den Bus.","nehme","Es regnet, deshalb ich nehme den Bus.","deshalb occupies position one; the verb follows."),
    s("Er ist müde, trotzdem arbeitet er weiter.","He is tired; nevertheless, he keeps working.","Er ist müde, trotzdem ___ er weiter.","arbeitet","Er ist müde, trotzdem er arbeitet weiter.","trotzdem triggers inversion."),
    s("Beeil dich, sonst verpasst du den Zug.","Hurry, otherwise you will miss the train.","Beeil dich, sonst ___ du den Zug.","verpasst","Beeil dich, sonst du verpasst den Zug.","sonst occupies position one."),
    s("Der Kurs ist voll. Deshalb suche ich einen anderen.","The course is full. Therefore I am looking for another one.","Deshalb ___ ich einen anderen.","suche","Deshalb ich suche einen anderen.","the finite verb follows Deshalb immediately."),
    s("Sie hatte wenig Zeit, trotzdem hat sie geholfen.","She had little time, yet she helped.","Sie hatte wenig Zeit, trotzdem ___ sie geholfen.","hat","Sie hatte wenig Zeit, trotzdem sie hat geholfen.","the auxiliary is the finite verb and follows trotzdem."),
  ], memoryTip:"Treat each connector as position one and place the finite verb directly after it: deshalb nehme, trotzdem arbeitet, sonst verpasst." }),
  q({ id:"a2-4-6", lead:"The present passive focuses on an action or process rather than the person performing it. It uses werden plus a past participle; the actor can be added with von.", pattern:"subject + werden + … + Partizip II", notes:["Turn the active accusative object into the passive nominative subject.","Conjugate werden for the new subject and place the participle at the end.","Omit the actor when unknown or unimportant; add von + dative when relevant.","Distinguish process passive wird geöffnet from state ist geöffnet."], samples:[
    s("Die Tür wird geöffnet.","The door is being opened.","Die Tür ___ geöffnet.","wird","Die Tür ist geöffnet gerade.","process passive uses werden + participle."),
    s("Die Pakete werden morgen geliefert.","The packages will be delivered tomorrow.","Die Pakete ___ morgen geliefert.","werden","Die Pakete wird morgen geliefert.","plural passive subject takes werden."),
    s("Das Essen wird von der Köchin vorbereitet.","The meal is prepared by the cook.","Das Essen wird von ___ Köchin vorbereitet. (the)","der","Das Essen wird durch die Köchin vorbereiten.","the actor uses von + dative; participle stays final."),
    s("Hier wird Deutsch gesprochen.","German is spoken here.","Hier ___ Deutsch gesprochen.","wird","Hier Deutsch wird gesprochen.","the finite verb remains second after place-first Hier."),
    s("Die Tür ist schon geöffnet.","The door is already open.","Die Tür ___ schon geöffnet. (state)","ist","Die Tür wird schon geöffnet seit Stunden.","sein + participle describes a resulting state."),
  ], memoryTip:"Promote the affected thing to nominative, conjugate werden, and send the participle to the end; use sein only for the resulting state." }),
];

export const A2_ADVANCED_LESSONS = buildGrammarLessons(blueprints);
