import { buildGrammarLessons, quickBlueprint as q, sample as s, type GrammarBlueprint } from "@/app/grammar/lesson-blueprint";

const blueprints: GrammarBlueprint[] = [
  q({ id:"b1-3-1", lead:"Konjunktiv II past expresses unreal past conditions, missed opportunities, regrets, and imagined alternatives. It uses hätte or wäre plus a past participle.", pattern:"hätte/wäre + Partizip II · modal: hätte + infinitive + modal infinitive", notes:["Choose hätte or wäre using perfect auxiliary logic.","Place the participle at the end of a simple unreal-past clause.","Use wenn for the unreal condition and Konjunktiv II past in both clauses.","With modal verbs, use the double-infinitive pattern after hätte."], samples:[
    s("Wenn ich mehr gelernt hätte, hätte ich bestanden.","If I had studied more, I would have passed.","Wenn ich mehr gelernt ___, hätte ich bestanden.","hätte","Wenn ich mehr gelernt hatte, würde ich bestanden.","unreal past uses hätte + participle in both clauses."),
    s("Sie wäre gern mitgekommen.","She would have liked to come along.","Sie ___ gern mitgekommen.","wäre","Sie hätte gern mitgekommen.","mitkommen uses sein, so the unreal past uses wäre."),
    s("Ich hätte dich anrufen sollen.","I should have called you.","Ich hätte dich anrufen ___.","sollen","Ich sollte dich angerufen haben.","modal unreal past uses two infinitives after hätte."),
    s("Ohne den Stau wären wir pünktlich angekommen.","Without the traffic jam, we would have arrived on time.","Ohne den Stau ___ wir pünktlich angekommen.","wären","Ohne den Stau hätten wir pünktlich angekommen.","ankommen uses sein/wären."),
    s("Hättest du das anders gemacht?","Would you have done that differently?","___ du das anders gemacht?","Hättest","Würdest du das anders gemacht?","a past counterfactual question uses hättest + participle."),
  ], memoryTip:"Move the perfect tense one step into unreality: hat/ist becomes hätte/wäre, while the participle remains final." }),
  q({ id:"b1-3-2", lead:"wenn and falls introduce real, possible, and hypothetical conditions. Tense and mood show how likely or unreal the speaker considers the condition.", pattern:"wenn = neutral/repeated · falls = possible contingency · Konjunktiv II = hypothetical", notes:["Use wenn for neutral conditions and repeated relationships.","Use falls when emphasising that the condition may or may not occur.","Use Konjunktiv II in unreal or remote conditions and results.","A first-position condition clause is followed by the main-clause finite verb."], samples:[
    s("Wenn es regnet, bleiben wir zu Hause.","If it rains, we stay home.","Wenn es regnet, ___ wir zu Hause.","bleiben","Wenn es regnet, wir bleiben zu Hause.","a real condition uses indicative and main-clause inversion."),
    s("Falls du später kommst, ruf bitte an.","If you happen to come later, please call.","___ du später kommst, ruf bitte an.","Falls","Als du später kommst, ruf bitte an.","falls marks a possible contingency."),
    s("Wenn ich mehr Zeit hätte, würde ich reisen.","If I had more time, I would travel.","Wenn ich mehr Zeit hätte, ___ ich reisen.","würde","Wenn ich mehr Zeit habe, würde ich gereist.","hypothetical present uses Konjunktiv II in condition and result."),
    s("Sollte es Probleme geben, melden Sie sich.","Should there be problems, contact us.","___ es Probleme geben, melden Sie sich.","Sollte","Würde es Probleme gibt, melden Sie sich.","formal conditional inversion can use sollte without wenn."),
    s("Ich komme, es sei denn, ich werde krank.","I will come unless I get ill.","Ich komme, ___, ich werde krank.","es sei denn","Ich komme, außer wenn ich werde krank.","es sei denn introduces an exception condition with main-clause order."),
  ], memoryTip:"Choose real, contingency, or hypothetical first; then select wenn, falls, or Konjunktiv II and check verb-final condition order." }),
  q({ id:"b1-3-3", lead:"obwohl, während, and wohingegen build contrast clauses. obwohl concedes an unexpected fact; während and wohingegen compare opposing situations.", pattern:"obwohl/während/wohingegen + … + finite verb", notes:["Use obwohl for concession: the main result occurs despite the subordinate fact.","Use während for simultaneous time or direct contrast; context disambiguates.","Use wohingegen for explicit formal contrast.","All three are subordinate connectors with final finite verbs."], samples:[
    s("Obwohl es regnete, gingen wir spazieren.","Although it rained, we went for a walk.","Obwohl es regnete, ___ wir spazieren.","gingen","Obwohl es regnete, wir gingen spazieren.","the first subordinate clause triggers main-clause inversion."),
    s("Er arbeitet, obwohl er müde ist.","He works although he is tired.","Er arbeitet, obwohl er müde ___.","ist","Er arbeitet, obwohl er ist müde.","obwohl sends ist to the end."),
    s("Mia fährt gern, während Tom lieber fliegt.","Mia likes driving, whereas Tom prefers flying.","Mia fährt gern, während Tom lieber ___.","fliegt","Mia fährt gern, während fliegt Tom lieber.","contrast während uses subordinate word order."),
    s("Die Stadt wächst, wohingegen das Dorf kleiner wird.","The city is growing, whereas the village is getting smaller.","Die Stadt wächst, ___ das Dorf kleiner wird.","wohingegen","Die Stadt wächst, wohingegen wird das Dorf kleiner.","wohingegen introduces explicit contrast with final verb."),
    s("Trotzdem ging er, obwohl wir ihn gewarnt hatten.","Nevertheless he went, although we had warned him.","Trotzdem ging er, obwohl wir ihn gewarnt ___.","hatten","Trotzdem er ging, obwohl wir hatten ihn gewarnt.","trotzdem triggers main-clause inversion; obwohl takes final auxiliary."),
  ], memoryTip:"Concession selects obwohl; side-by-side opposition selects während or wohingegen. In every case, send the subordinate verb to the end." }),
  q({ id:"b1-3-4", lead:"Time clauses locate events before, after, since, until, or immediately after another event. Connector choice and tense make the sequence explicit.", pattern:"bevor · nachdem · seitdem · bis · sobald + final verb", notes:["Use bevor for the later clause viewed before another action and nachdem for the earlier completed action.","Use seitdem for a starting event that continues to the reference time.","Use bis for an endpoint and sobald for immediate sequence.","With nachdem in past narration, pluperfect often marks the earlier event."], samples:[
    s("Bevor ich gehe, rufe ich dich an.","Before I leave, I will call you.","___ ich gehe, rufe ich dich an.","Bevor","Vor ich gehe, rufe ich dich an.","bevor introduces a verb-final clause."),
    s("Nachdem sie gegessen hatte, ging sie spazieren.","After she had eaten, she went for a walk.","Nachdem sie gegessen ___, ging sie spazieren.","hatte","Nachdem sie hat gegessen, ging sie spazieren.","nachdem marks the earlier event; pluperfect auxiliary is final."),
    s("Seitdem er umgezogen ist, sehen wir uns selten.","Since he moved, we rarely see each other.","___ er umgezogen ist, sehen wir uns selten.","Seitdem","Seit er ist umgezogen, sehen wir uns selten.","seitdem connects a starting event to an ongoing result."),
    s("Warte, bis ich zurückkomme.","Wait until I come back.","Warte, ___ ich zurückkomme.","bis","Warte, bis komme ich zurück.","bis introduces the endpoint with final verb."),
    s("Sobald der Zug ankommt, rufe ich an.","As soon as the train arrives, I will call.","___ der Zug ankommt, rufe ich an.","Sobald","Sofort der Zug ankommt, rufe ich an.","sobald expresses immediate sequence."),
  ], memoryTip:"Draw a timeline: before, earlier completed, continuing since, endpoint, or immediate next. Then choose the connector and tense." }),
  q({ id:"b1-3-5", lead:"Infinitive clauses reduce repeated subjects and create compact written German. zu-clauses, ohne … zu, and statt … zu replace full subordinate clauses when the understood subject matches.", pattern:"zu · ohne … zu · statt … zu · same understood subject", notes:["Confirm that the main and infinitive actions share an understood subject.","Use ohne … zu for an absent accompanying action and statt … zu for an alternative not chosen.","Insert zu inside separable infinitives and before simple infinitives.","Use a full dass/damit/ohne dass clause when subjects differ."], samples:[
    s("Sie ging, ohne sich zu verabschieden.","She left without saying goodbye.","Sie ging, ohne sich ___ verabschieden.","zu","Sie ging, ohne dass sich zu verabschieden.","same subject allows ohne … zu."),
    s("Statt zu arbeiten, surfte er im Internet.","Instead of working, he browsed the internet.","Statt ___ arbeiten, surfte er im Internet.","zu","Statt dass arbeiten, surfte er im Internet.","same subject allows statt … zu."),
    s("Er hofft, die Prüfung zu bestehen.","He hopes to pass the exam.","Er hofft, die Prüfung ___ bestehen.","zu","Er hofft, dass die Prüfung zu bestehen.","same understood subject uses a zu-infinitive."),
    s("Sie verließ das Haus, ohne dass ich es bemerkte.","She left the house without me noticing.","Sie verließ das Haus, ohne ___ ich es bemerkte.","dass","Sie verließ das Haus, ohne ich es zu bemerken.","different subjects require ohne dass."),
    s("Er versprach, pünktlich anzurufen.","He promised to call on time.","Er versprach, pünktlich ___. (anrufen)","anzurufen","Er versprach, pünktlich zu anrufen.","separable anrufen inserts zu."),
  ], memoryTip:"Compare subjects before reducing. Same subject permits zu; different subjects require a full subordinate clause." }),
  q({ id:"b1-3-6", lead:"Paired conjunctions connect balanced alternatives, additions, exclusions, and contrasts. Their two halves must link grammatically parallel elements.", pattern:"sowohl … als auch · weder … noch · entweder … oder · nicht nur … sondern auch · zwar … aber", notes:["Connect the same grammatical category on both sides.","Use sowohl … als auch for addition and weder … noch for double negation.","Use entweder … oder for alternatives and nicht nur … sondern auch for emphatic addition.","zwar … aber concedes one point before presenting a contrast."], samples:[
    s("Sie spricht sowohl Deutsch als auch Englisch.","She speaks both German and English.","Sie spricht sowohl Deutsch ___ auch Englisch.","als","Sie spricht sowohl Deutsch und auch Englisch.","sowohl pairs with als auch."),
    s("Er trinkt weder Kaffee noch Tee.","He drinks neither coffee nor tea.","Er trinkt weder Kaffee ___ Tee.","noch","Er trinkt weder Kaffee oder Tee.","weder pairs with noch and already negates."),
    s("Wir fahren entweder heute oder morgen.","We travel either today or tomorrow.","Wir fahren entweder heute ___ morgen.","oder","Wir fahren entweder heute noch morgen.","entweder pairs with oder."),
    s("Der Kurs ist nicht nur nützlich, sondern auch interessant.","The course is not only useful but also interesting.","Der Kurs ist nicht nur nützlich, ___ auch interessant.","sondern","Der Kurs ist nicht nur nützlich, aber auch interessant.","nicht nur pairs with sondern auch."),
    s("Die Wohnung ist zwar klein, aber sehr hell.","The apartment is small, but very bright.","Die Wohnung ist zwar klein, ___ sehr hell.","aber","Die Wohnung ist zwar klein, sondern sehr hell.","zwar sets up a concession completed by aber."),
  ], memoryTip:"Memorise both halves as one unit and check that the linked words, phrases, or clauses are structurally parallel." }),
  q({ id:"b1-4-1", lead:"Nominalisation turns verbs and adjectives into nouns, allowing denser formal expression. Nominalised infinitives are neuter and capitalised; adjective nouns follow adjective declension.", pattern:"das Lesen · beim Essen · etwas Neues · die Arbeitslosen", notes:["Capitalise every nominalised verb or adjective.","An infinitive used as a noun is neuter and often combines with beim, zum, or nach dem.","Nominalised adjectives keep adjective endings because an understood noun is omitted.","Use nominal style selectively; verbal style is often clearer in speech."], samples:[
    s("Das Lesen hilft beim Lernen.","Reading helps with learning.","Das ___ hilft beim Lernen. (read)","Lesen","Das lesen hilft beim lernen.","nominalised infinitives are capitalised and neuter."),
    s("Beim Essen sprechen wir wenig.","While eating, we speak little.","Beim ___ sprechen wir wenig. (eat)","Essen","Beim essen sprechen wir wenig.","bei dem + nominalised infinitive contracts to beim."),
    s("Ich möchte etwas Neues lernen.","I would like to learn something new.","Ich möchte etwas ___ lernen. (new)","Neues","Ich möchte etwas neues lernen.","nominalised adjective after etwas is capitalised."),
    s("Die Arbeitslosen erhalten Beratung.","The unemployed receive advice.","Die ___ erhalten Beratung. (unemployed)","Arbeitslosen","Die arbeitslose erhalten Beratung.","a plural nominalised adjective is capitalised and declined."),
    s("Vor dem Schlafengehen lese ich.","Before going to sleep, I read.","Vor dem ___ lese ich. (go to sleep)","Schlafengehen","Vor dem schlafen gehen lese ich.","the nominalised compound infinitive is capitalised and written together."),
  ], memoryTip:"If an action or quality occupies a noun slot, capitalise it and supply the article or adjective ending that the noun phrase requires." }),
  q({ id:"b1-4-2", lead:"Present and past participles can function as adjectives and compress relative-clause information inside noun phrases. They then receive normal adjective endings.", pattern:"lachende Kinder · das geschlossene Fenster", notes:["Partizip I is infinitive + -d and expresses an active simultaneous quality.","Partizip II as an adjective often expresses a completed or passive result.","Decline the participle like any other adjective after the determiner.","Expand the phrase into a relative clause to check meaning and participant roles."], samples:[
    s("Die spielenden Kinder sind laut.","The children who are playing are loud.","Die spielend___ Kinder sind laut.","en","Die gespielt Kinder sind laut.","present participle spielend takes the plural adjective ending -en."),
    s("Das geschlossene Fenster bleibt zu.","The closed window remains shut.","Das geschlossen___ Fenster bleibt zu.","e","Das schließend Fenster bleibt zu.","past participle geschlossen describes a resulting state."),
    s("Ein wartender Kunde steht draußen.","A waiting customer is standing outside.","Ein wartend___ Kunde steht draußen.","er","Ein gewarteter Kunde steht draußen.","active simultaneous meaning uses Partizip I + mixed -er."),
    s("Wir reparieren die beschädigte Tür.","We repair the damaged door.","Wir reparieren die beschädigt___ Tür.","e","Wir reparieren die beschädigend Tür.","past participle describes what was damaged and takes -e."),
    s("Die gestern angekommenen Gäste schlafen.","The guests who arrived yesterday are sleeping.","Die gestern angekommen___ Gäste schlafen.","en","Die gestern ankommenden Gäste schlafen gestern.","completed prior arrival uses Partizip II angekommen + -en."),
  ], memoryTip:"Expand mentally: who is doing it → Partizip I; what has been done/resulted → Partizip II. Then add the normal adjective ending." }),
  q({ id:"b1-4-3", lead:"Reported speech can use dass with indicative or common Konjunktiv I forms to mark information as reported rather than personally confirmed.", pattern:"Er sagt, dass er kommt. · Er sagt, er komme.", notes:["dass + indicative is normal in everyday reporting.","Konjunktiv I is common in news and formal reports to signal distance.","The most visible forms are sei, habe, werde, könne, müsse, and third-person -e forms.","If Konjunktiv I matches indicative, formal German may use Konjunktiv II to keep distance visible."], samples:[
    s("Sie sagt, dass sie später kommt.","She says that she is coming later.","Sie sagt, dass sie später ___.","kommt","Sie sagt, dass kommt sie später.","everyday dass-reporting uses final verb."),
    s("Er sagt, er sei krank.","He says that he is ill.","Er sagt, er ___ krank.","sei","Er sagt, er ist krank laut ihm.","Konjunktiv I sei marks reported information."),
    s("Die Firma erklärt, sie habe alles geprüft.","The company states that it has checked everything.","Die Firma erklärt, sie ___ alles geprüft.","habe","Die Firma erklärt, sie hat alles geprüft worden.","Konjunktiv I habe marks a reported perfect."),
    s("Der Sprecher sagt, die Preise würden steigen.","The spokesperson says prices will rise.","Der Sprecher sagt, die Preise ___ steigen.","würden","Der Sprecher sagt, die Preise werden stiegen.","Konjunktiv II can replace an indistinct plural Konjunktiv I."),
    s("Sie behauptet, sie könne das Problem lösen.","She claims she can solve the problem.","Sie behauptet, sie ___ das Problem lösen.","könne","Sie behauptet, sie kann das Problem gelöst.","Konjunktiv I modal form könne signals reported ability."),
  ], memoryTip:"Choose everyday dass + indicative or formal distance with Konjunktiv I; keep the original speaker and your own certainty separate." }),
  q({ id:"b1-4-4", lead:"German object order balances case, pronoun status, definiteness, and information structure. Short unstressed pronouns normally precede full noun phrases.", pattern:"pronouns early · two nouns DAT–AKK · two pronouns AKK–DAT", notes:["Identify every object's case before arranging it.","A personal pronoun usually precedes a noun object regardless of case.","With two pronouns, accusative normally precedes dative.","Negation and emphasis can shift positions, but the neutral pattern is the safest production base."], samples:[
    s("Ich gebe dem Kollegen die Unterlagen.","I give the colleague the documents.","Ich gebe ___ Kollegen die Unterlagen. (the)","dem","Ich gebe die Unterlagen den Kollege.","two noun objects normally use dative before accusative."),
    s("Ich gebe ihm die Unterlagen.","I give him the documents.","Ich gebe ___ die Unterlagen.","ihm","Ich gebe die Unterlagen ihm.","a dative pronoun precedes a noun object."),
    s("Ich gebe sie dem Kollegen.","I give them to the colleague.","Ich gebe ___ dem Kollegen. (them)","sie","Ich gebe dem Kollegen sie.","an accusative pronoun precedes a noun object."),
    s("Ich gebe sie ihm.","I give them to him.","Ich gebe ___ ihm. (them)","sie","Ich gebe ihm sie.","two pronouns normally use accusative before dative."),
    s("Heute habe ich es ihm nicht erklärt.","Today I did not explain it to him.","Heute habe ich ___ ihm nicht erklärt. (it)","es","Heute ich habe ihm es erklärt nicht.","short pronouns precede nicht; auxiliary remains second and participle final."),
  ], memoryTip:"Label DAT and AKK, circle pronouns, then apply pronouns-first and AKK-pronoun-before-DAT-pronoun." }),
  q({ id:"b1-4-5", lead:"Cohesion links sentences into a readable text through pronouns, demonstratives, connective adverbs, repetition control, and clear reference chains.", pattern:"noun → pronoun/demonstrative · idea → da-compound/das · relation → connector", notes:["Introduce a referent clearly before replacing it with a pronoun.","Use demonstratives when ordinary pronouns would be ambiguous.","Use da-compounds to refer back to ideas governed by prepositions.","Choose connectors by logical relation and preserve their word-order pattern."], samples:[
    s("Mia kaufte ein Fahrrad. Sie benutzt es täglich.","Mia bought a bicycle. She uses it daily.","Mia kaufte ein Fahrrad. Sie benutzt ___ täglich.","es","Mia kaufte ein Fahrrad. Es benutzt sie täglich.","es clearly refers back to neuter Fahrrad."),
    s("Der Plan ist teuer. Trotzdem unterstützen wir ihn.","The plan is expensive. Nevertheless we support it.","Der Plan ist teuer. Trotzdem ___ wir ihn.","unterstützen","Der Plan ist teuer. Trotzdem wir unterstützen ihn.","trotzdem triggers inversion and ihn refers to Plan."),
    s("Wir warten auf eine Antwort. Darauf kommt es jetzt an.","We are waiting for an answer. That is what matters now.","Wir warten auf eine Antwort. ___ kommt es jetzt an.","Darauf","Wir warten auf eine Antwort. Auf sie es kommt an.","darauf links the prepositional idea across sentences."),
    s("Lena sprach mit Mia. Diese hatte die Nachricht schon gelesen.","Lena spoke with Mia. The latter had already read the message.","Lena sprach mit Mia. ___ hatte die Nachricht schon gelesen.","Diese","Lena sprach mit Mia. Sie hatte die Nachricht gelesen.","Diese disambiguates the nearer feminine referent Mia."),
    s("Zuerst prüfen wir die Daten. Anschließend schreiben wir den Bericht.","First we check the data. Afterwards we write the report.","Zuerst prüfen wir die Daten. ___ schreiben wir den Bericht.","Anschließend","Zuerst prüfen wir die Daten. Anschließend wir schreiben den Bericht.","connective adverb anschließend occupies position one."),
  ], memoryTip:"For every pronoun or connector, point to its exact referent or logical relation. If two readings remain possible, name the noun again." }),
  q({ id:"b1-4-6", lead:"Commas reveal German clause structure, while formal register shapes pronouns, vocabulary, sentence openings, and politeness. Accurate punctuation and consistent tone make B1 writing credible.", pattern:"comma before subordinate/relative/infinitive clauses · formal Sie/Ihr · neutral precise wording", notes:["Separate subordinate and relative clauses with commas.","Use commas with expanded infinitive groups introduced by um, ohne, statt, als, or abhängig expressions.","Capitalise formal Sie, Ihnen, and Ihr forms consistently.","Avoid conversational fillers and abrupt imperatives in formal messages; use clear subject lines, openings, requests, and closings."], samples:[
    s("Ich komme später, weil mein Zug Verspätung hat.","I will come later because my train is delayed.","Ich komme später___ weil mein Zug Verspätung hat.",",","Ich komme später weil, mein Zug Verspätung hat.","the comma precedes the subordinate weil-clause."),
    s("Der Kurs, den ich gebucht habe, fällt aus.","The course I booked is cancelled.","Der Kurs___ den ich gebucht habe___ fällt aus.",", ,","Der Kurs den ich gebucht habe fällt aus.","commas frame the relative clause."),
    s("Ich schreibe Ihnen, um einen Termin zu vereinbaren.","I am writing to arrange an appointment.","Ich schreibe Ihnen___ um einen Termin zu vereinbaren.",",","Ich schreibe ihnen um einen Termin vereinbaren.","formal Ihnen is capitalised and um-zu group is separated by a comma."),
    s("Könnten Sie mir bitte die Unterlagen senden?","Could you please send me the documents?","___ Sie mir bitte die Unterlagen senden?","Könnten","Senden Sie mir die Sachen sofort!","Konjunktiv II creates an appropriate formal request."),
    s("Mit freundlichen Grüßen\nMia Klein","Kind regards, Mia Klein.","Mit freundlich___ Grüßen\nMia Klein","en","Liebe Grüße! Mia","the standard formal closing uses dative plural -en and conventional capitalisation."),
  ], memoryTip:"Read for clause boundaries first and add commas; then read again only for register—formal pronouns, request tone, and conventional opening/closing." }),
];

export const B1_ADVANCED_LESSONS = buildGrammarLessons(blueprints);
