import { buildGrammarLessons, quickBlueprint as q, sample as s, type GrammarBlueprint } from "@/app/grammar/lesson-blueprint";

const blueprints: GrammarBlueprint[] = [
  q({ id:"b1-1-1", lead:"The complete adjective-ending system distributes grammatical information between determiner and adjective. Strong, weak, and mixed patterns become predictable when case, gender, number, and determiner type are identified in order.", pattern:"no article = strong · der-word = weak · ein-word = mixed", notes:["Identify case/gender/number before examining the determiner.","Without an article, the adjective carries the strong der-word signal.","After der-words, use -e in five cells and -en elsewhere; after ein-words, supply missing -er/-es.","Apply the same ending to every coordinated adjective and check dative plural noun -n."], samples:[
    s("Frischer Kaffee schmeckt gut.","Fresh coffee tastes good.","Frisch___ Kaffee schmeckt gut.","er","Frische Kaffee schmeckt gut.","without an article, masculine nominative takes strong -er."),
    s("Ich trinke kaltes Wasser.","I drink cold water.","Ich trinke kalt___ Wasser.","es","Ich trinke kalte Wasser.","no-article neuter accusative takes strong -es."),
    s("Der neue internationale Kurs beginnt.","The new international course begins.","Der neu___ internationale Kurs beginnt.","e","Der neuer internationale Kurs beginnt.","after der in masculine nominative, adjectives take weak -e."),
    s("Sie kauft einen warmen roten Mantel.","She buys a warm red coat.","Sie kauft einen warm___ roten Mantel.","en","Sie kauft einen warmer roten Mantel.","masculine accusative after an ein-word takes -en."),
    s("Mit gutem deutschem Brot schmeckt es besser.","It tastes better with good German bread.","Mit gut___ deutschem Brot schmeckt es besser.","em","Mit guten deutschem Brot schmeckt es besser.","no-article neuter dative adjectives take strong -em."),
  ], memoryTip:"Run four checks: case, gender/number, determiner class, ending. Never guess from the noun alone." }),
  q({ id:"b1-1-2", lead:"The genitive marks possession and relationships and follows several formal prepositions. Mastery requires article forms, masculine/neuter noun endings, and agreement inside expanded noun phrases.", pattern:"des/eines + -(e)s · der/einer · trotz/während/wegen + genitive", notes:["Ask Wessen? and identify the possessor phrase.","Masculine and neuter nouns normally add -s or -es; feminine and plural do not.","Adjectives after genitive determiners take -en.","Use genitive after wegen, trotz, während, außerhalb, innerhalb, and statt in careful standard German."], samples:[
    s("Wegen des schlechten Wetters bleiben wir zu Hause.","Because of the bad weather, we are staying home.","Wegen des schlecht___ Wetters bleiben wir zu Hause.","en","Wegen dem schlechten Wetter bleiben wir zu Hause.","standard wegen takes genitive; adjective is weak -en."),
    s("Die Meinung meiner neuen Kollegin ist wichtig.","My new colleague's opinion is important.","Die Meinung meiner neu___ Kollegin ist wichtig.","en","Die Meinung meine neue Kollegin ist wichtig.","feminine genitive possessive is meiner and adjective takes -en."),
    s("Während des Gesprächs klingelte das Telefon.","During the conversation, the phone rang.","Während ___ Gesprächs klingelte das Telefon. (the)","des","Während dem Gespräch klingelte das Telefon.","während takes genitive des Gesprächs."),
    s("Trotz großer Schwierigkeiten machte sie weiter.","Despite major difficulties, she continued.","Trotz groß___ Schwierigkeiten machte sie weiter.","er","Trotz großen Schwierigkeiten machte sie weiter.","without an article, plural genitive adjective takes strong -er."),
    s("Das Dach des alten Hauses wird repariert.","The roof of the old house is being repaired.","Das Dach des alt___ Hauses wird repariert.","en","Das Dach dem alten Haus wird repariert.","genitive des requires noun -es and adjective -en."),
  ], memoryTip:"Build the genitive as one package: preposition or Wessen?, article, adjective -en, and masculine/neuter noun -(e)s." }),
  q({ id:"b1-1-3", lead:"Advanced relative clauses use dative, genitive, and prepositional relative pronouns. The antecedent gives gender/number; the role and governing preposition inside the clause give case.", pattern:"dem/der/denen · dessen/deren · preposition + relative pronoun", notes:["Determine the pronoun's job entirely inside the relative clause.","Use dem/der/denen for dative and dessen/deren for possession.","A required preposition stands directly before the relative pronoun.","The finite verb remains final and commas frame the clause."], samples:[
    s("Der Mann, dem ich geholfen habe, ist mein Nachbar.","The man whom I helped is my neighbour.","Der Mann, ___ ich geholfen habe, ist mein Nachbar.","dem","Der Mann, den ich geholfen habe, ist mein Nachbar.","helfen requires masculine dative dem."),
    s("Die Kollegin, mit der ich arbeite, kommt aus Wien.","The colleague with whom I work comes from Vienna.","Die Kollegin, mit ___ ich arbeite, kommt aus Wien.","der","Die Kollegin, die ich mit arbeite, kommt aus Wien.","mit governs dative and precedes feminine der."),
    s("Das Kind, dessen Fahrrad fehlt, weint.","The child whose bicycle is missing is crying.","Das Kind, ___ Fahrrad fehlt, weint.","dessen","Das Kind, dem Fahrrad fehlt, weint.","neuter possessive relative is dessen."),
    s("Die Frau, deren Sohn studiert, ist Ärztin.","The woman whose son studies is a doctor.","Die Frau, ___ Sohn studiert, ist Ärztin.","deren","Die Frau, dessen Sohn studiert, ist Ärztin.","feminine possessive relative is deren."),
    s("Die Leute, von denen wir sprechen, sind hier.","The people we are talking about are here.","Die Leute, von ___ wir sprechen, sind hier.","denen","Die Leute, von die wir sprechen, sind hier.","plural dative relative is denen after von."),
  ], memoryTip:"Draw the relative-clause gap, insert the antecedent mentally, apply its verb/preposition, then choose the matching relative form." }),
  q({ id:"b1-1-4", lead:"N-declension affects a group of masculine nouns referring mainly to people and animals. They add -(e)n in every case except nominative singular.", pattern:"der Student · den/dem/des Studenten", notes:["Recognise common weak masculine endings such as -e, -ant, -ent, -ist, -oge, and -at.","Keep the bare form only in nominative singular.","Add -n or -en in accusative, dative, genitive, and plural.","Learn irregular members such as der Herr–Herrn and der Name–Namen."], samples:[
    s("Ich sehe den Studenten jeden Tag.","I see the student every day.","Ich sehe den ___. (Student)","Studenten","Ich sehe den Student.","weak masculine accusative adds -en."),
    s("Wir helfen dem Kollegen.","We help the colleague.","Wir helfen dem ___. (Kollege)","Kollegen","Wir helfen dem Kollege.","weak masculine dative adds -n."),
    s("Das Büro des Präsidenten ist oben.","The president's office is upstairs.","Das Büro des ___ ist oben. (Präsident)","Präsidenten","Das Büro des Präsidents ist oben.","weak masculine genitive adds -en rather than -s."),
    s("Der Kunde wartet draußen.","The customer is waiting outside.","___ Kunde wartet draußen. (the)","Der","Der Kunden wartet draußen.","nominative singular keeps the base form."),
    s("Bitte sprechen Sie mit Herrn Klein.","Please speak with Mr Klein.","Bitte sprechen Sie mit ___ Klein. (Herr)","Herrn","Bitte sprechen Sie mit Herr Klein.","Herr has the special oblique form Herrn."),
  ], memoryTip:"If a masculine person noun belongs to the weak group, add -(e)n everywhere except nominative singular." }),
  q({ id:"b1-1-5", lead:"da- and wo-compounds combine prepositions with reference to things, ideas, or clauses. They avoid repetitive preposition + pronoun combinations and form natural questions.", pattern:"darauf/worauf · damit/womit · daran/woran", notes:["Use wo(r)+preposition for questions about things and da(r)+preposition for answers/references.","Insert r before a vowel: woran, darauf, darüber.","Use preposition + personal pronoun for people, not da-compounds.","A da-compound can anticipate or refer back to an entire clause."], samples:[
    s("Worauf wartest du?","What are you waiting for?","___ wartest du? (what for)","Worauf","Auf was wartest du?","standard questions about things use worauf."),
    s("Ich warte darauf, dass der Bus kommt.","I am waiting for the bus to come.","Ich warte ___, dass der Bus kommt.","darauf","Ich warte auf es, dass der Bus kommt.","darauf anticipates the dass-clause."),
    s("Womit fährst du zur Arbeit?","What do you travel to work with?","___ fährst du zur Arbeit?","Womit","Mit was fährst du zur Arbeit?","womit asks about a thing or means."),
    s("Ich denke oft daran.","I often think about it.","Ich denke oft ___.","daran","Ich denke oft an es.","daran replaces an + thing/idea."),
    s("Mit wem sprichst du?","Who are you speaking with?","Mit ___ sprichst du?","wem","Womit sprichst du?","people require preposition + personal question pronoun."),
  ], memoryTip:"Thing or idea: wo-/da-compound. Person: preposition + wem/wen or personal pronoun. Add r before vowel-initial prepositions." }),
  q({ id:"b1-1-6", lead:"Indefinite pronouns refer to nonspecific people, things, amounts, or absence. Their case forms and agreement let speakers generalise without naming a precise noun.", pattern:"man · jemand/niemand · etwas/nichts · alle/manche/einige", notes:["man is always a third-person singular subject and has object forms einen and einem.","jemand and niemand may take case endings, especially in careful writing.","etwas and nichts refer to nonspecific things and do not decline.","Plural pronouns such as alle, manche, einige, wenige take plural verb agreement."], samples:[
    s("Man muss hier leise sein.","One must be quiet here.","___ muss hier leise sein.","Man","Mann muss hier leise sein.","indefinite man is lowercase and takes singular agreement."),
    s("Kann mir jemand helfen?","Can someone help me?","Kann mir ___ helfen?","jemand","Kann mich jemandem helfen?","jemand is the nominative subject; mir is dative."),
    s("Ich habe niemanden gesehen.","I saw nobody.","Ich habe ___ gesehen. (nobody)","niemanden","Ich habe niemand gesehenen.","accusative niemand commonly takes -en."),
    s("Möchtest du etwas trinken?","Would you like something to drink?","Möchtest du ___ trinken?","etwas","Möchtest du jemand trinken?","etwas refers to a nonspecific thing."),
    s("Einige sind schon gegangen.","Some have already left.","___ sind schon gegangen. (some)","Einige","Einiges sind schon gegangen.","a plural people reference uses einige and plural sind."),
  ], memoryTip:"Classify the missing reference as generic person, specific unknown person, thing, or plural group; then apply case and agreement." }),
  q({ id:"b1-2-1", lead:"The narrative preterite is central to written stories, reports, and biographies. Regular verbs use -te; irregular verbs change stem; mixed verbs combine both patterns.", pattern:"regular stem + -te · irregular past stem · mixed past stem + -te", notes:["Use the preterite consistently in sustained written narration.","Regular verbs take -te endings; irregular verbs use a memorised stem and no -te.","Mixed verbs such as bringen and denken change stem and add -te.","Time clauses and adverbs organise the sequence while verb-second remains active."], samples:[
    s("Sie öffnete die Tür und wartete.","She opened the door and waited.","Sie ___ die Tür und wartete. (öffnen)","öffnete","Sie öffnete die Tür und gewartet.","regular narrative preterite uses stem + -te."),
    s("Er ging nach Hause.","He went home.","Er ___ nach Hause. (gehen)","ging","Er gehte nach Hause.","gehen has the irregular preterite ging."),
    s("Der Zug kam pünktlich an.","The train arrived on time.","Der Zug ___ pünktlich an. (kommen)","kam","Der Zug kommte pünktlich an.","kommen has the irregular preterite kam; prefix stays final."),
    s("Mia brachte einen Kuchen mit.","Mia brought a cake along.","Mia ___ einen Kuchen mit. (bringen)","brachte","Mia bringte einen Kuchen mit.","bringen is mixed: brachte."),
    s("Plötzlich sah er ein Licht.","Suddenly he saw a light.","Plötzlich ___ er ein Licht. (sehen)","sah","Plötzlich er sah ein Licht.","sehen has past stem sah; after adverb-first, verb remains second."),
  ], memoryTip:"Group verbs as regular, irregular, or mixed and learn frequent irregulars in complete narrative sentences." }),
  q({ id:"b1-2-2", lead:"The pluperfect marks an event completed before another past event. It combines hatte or war with a past participle and clarifies past-before-past sequence.", pattern:"hatte/war + Partizip II", notes:["Choose hatte or war using the same auxiliary logic as the perfect.","The participle closes the pluperfect clause.","Use nachdem or schon to make the earlier event relationship explicit.","The later narrative event normally appears in preterite or perfect depending on register."], samples:[
    s("Ich hatte gegessen, bevor ich ging.","I had eaten before I left.","Ich ___ gegessen, bevor ich ging.","hatte","Ich habe gegessen, bevor ich ging.","pluperfect hatte marks the earlier past event."),
    s("Nachdem sie angekommen war, rief sie an.","After she had arrived, she called.","Nachdem sie angekommen ___, rief sie an.","war","Nachdem sie war angekommen, rief sie an.","movement verb uses war and the auxiliary closes the subordinate clause."),
    s("Der Film hatte schon begonnen.","The film had already begun.","Der Film ___ schon begonnen.","hatte","Der Film war schon begonnen.","beginnen uses haben, so pluperfect uses hatte."),
    s("Wir waren eingeschlafen, als das Telefon klingelte.","We had fallen asleep when the phone rang.","Wir ___ eingeschlafen, als das Telefon klingelte.","waren","Wir hatten eingeschlafen, als das Telefon klingelte.","change of state einschlafen uses sein/war."),
    s("Sie fand den Schlüssel, den sie verloren hatte.","She found the key that she had lost.","Sie fand den Schlüssel, den sie verloren ___.","hatte","Sie fand den Schlüssel, den hatte sie verloren.","the relative-clause pluperfect auxiliary is final."),
  ], memoryTip:"Place yourself at a past reference point; anything already completed before it takes hatte/war + participle." }),
  q({ id:"b1-2-3", lead:"werden expresses future events and present assumptions. Context, adverbs, and tense distinguish a prediction from a probability judgement.", pattern:"werden + infinitive = future · werden + wohl + infinitive = assumption", notes:["Use present tense for fixed plans and werden for prediction or emphasis.","Use wohl, wahrscheinlich, or sicher to grade probability.","For assumptions about the present, werden still carries present forms.","Keep the infinitive or perfect infinitive at the right edge."], samples:[
    s("Die Preise werden weiter steigen.","Prices will continue to rise.","Die Preise ___ weiter steigen.","werden","Die Preise werden weiter gestiegen.","future prediction uses werden + infinitive."),
    s("Er wird jetzt zu Hause sein.","He is probably at home now.","Er ___ jetzt zu Hause sein.","wird","Er ist wird jetzt zu Hause.","werden can mark a present assumption."),
    s("Sie wird wohl später kommen.","She will probably come later.","Sie wird ___ später kommen. (probably)","wohl","Sie wohl wird später kommen.","wohl grades the assumption inside the sentence bracket."),
    s("Morgen treffen wir den Kunden.","Tomorrow we meet the client.","Morgen ___ wir den Kunden. (meet)","treffen","Morgen werden wir den Kunden getroffen.","a fixed arrangement naturally uses present tense."),
    s("Er wird den Termin vergessen haben.","He will probably have forgotten the appointment.","Er wird den Termin vergessen ___.","haben","Er wird haben den Termin vergessen.","an assumption about a completed action uses perfect infinitive at the end."),
  ], memoryTip:"Ask whether werden places an event later or evaluates probability now; use context and wohl, then preserve the right-edge infinitive." }),
  q({ id:"b1-2-4", lead:"The process passive can be narrated in present and past. werden changes tense while the lexical past participle remains at the clause end.", pattern:"wird gemacht · wurde gemacht · ist gemacht worden", notes:["Promote the affected object to nominative and conjugate werden.","Use wurde/wurden for narrative past passive and ist/sind … worden for conversational perfect passive.","Add an actor with von + dative and a means/cause with durch + accusative.","Do not confuse passive auxiliary worden with lexical geworden."], samples:[
    s("Die Straße wird repariert.","The road is being repaired.","Die Straße ___ repariert.","wird","Die Straße ist repariert gerade.","present process passive uses wird."),
    s("Die Straße wurde gestern gesperrt.","The road was closed yesterday.","Die Straße ___ gestern gesperrt.","wurde","Die Straße geworden gestern gesperrt.","preterite passive uses wurde + participle."),
    s("Die Pakete sind geliefert worden.","The packages have been delivered.","Die Pakete sind geliefert ___.","worden","Die Pakete haben geliefert geworden.","perfect passive uses sein + participle + worden."),
    s("Der Text wurde von der Autorin geschrieben.","The text was written by the author.","Der Text wurde von ___ Autorin geschrieben. (the)","der","Der Text wurde durch die Autorin geschreibt.","actor uses von + dative; participle is geschrieben."),
    s("Das Fenster wurde durch den Sturm beschädigt.","The window was damaged by the storm.","Das Fenster wurde durch ___ Sturm beschädigt. (the)","den","Das Fenster wurde von den Sturm beschädigt.","an impersonal cause uses durch + accusative."),
  ], memoryTip:"Keep the lexical participle fixed and change only werden for time: wird, wurde, ist … worden." }),
  q({ id:"b1-2-5", lead:"German often avoids the passive with man, active constructions, lassen, sein + zu, or sich lassen. These alternatives change emphasis and register while preserving process meaning.", pattern:"man + active · sich lassen + infinitive · sein + zu + infinitive", notes:["Use man when a general human actor is natural.","Use sich lassen to express possibility or feasibility.","Use sein + zu + infinitive for necessity or possibility in formal language.","Choose an alternative only when its meaning matches the passive, not as a mechanical rewrite."], samples:[
    s("Man repariert die Straße.","They are repairing the road.","___ repariert die Straße. (general people)","Man","Mann repariert die Straße.","man provides an unspecified human actor."),
    s("Das Problem lässt sich lösen.","The problem can be solved.","Das Problem lässt ___ lösen.","sich","Das Problem lässt gelöst werden sich.","sich lassen + infinitive expresses feasibility."),
    s("Die Aufgabe ist heute zu erledigen.","The task must be completed today.","Die Aufgabe ist heute ___ erledigen.","zu","Die Aufgabe ist heute erledigen.","sein + zu + infinitive expresses formal necessity."),
    s("Das Buch verkauft sich gut.","The book sells well.","Das Buch verkauft ___ gut.","sich","Das Buch wird sich gut verkauft.","reflexive active can describe a general passive-like property."),
    s("Wir können den Termin verschieben.","We can postpone the appointment.","Wir ___ den Termin verschieben.","können","Der Termin kann wir verschieben.","an active subject is clearest when the actor is known and relevant."),
  ], memoryTip:"Choose by emphasis: unknown people → man; feasibility → sich lassen; formal necessity → sein + zu; relevant actor → active." }),
  q({ id:"b1-2-6", lead:"Konjunktiv II present expresses politeness, wishes, advice, hypotheses, and unreal present situations. würde + infinitive is productive; wäre, hätte, and modal forms are preferred when available.", pattern:"würde + infinitive · wäre/hätte/könnte/müsste/sollte/dürfte", notes:["Use würde + infinitive for most lexical verbs.","Prefer wäre, hätte, and common modal subjunctives over würde sein/haben/können.","An wenn-clause states the condition; the result clause uses another subjunctive form.","Polite questions often use könnte, würde, or hätte gern."], samples:[
    s("Ich würde gern länger bleiben.","I would like to stay longer.","Ich ___ gern länger bleiben.","würde","Ich wurde gern länger bleiben.","würde with umlaut marks hypothetical/polite meaning."),
    s("Wenn ich Zeit hätte, käme ich mit.","If I had time, I would come along.","Wenn ich Zeit ___, käme ich mit.","hätte","Wenn ich Zeit hatte, komme ich mit.","unreal present condition uses hätte."),
    s("Könnten Sie mir helfen?","Could you help me?","___ Sie mir helfen?","Könnten","Konnten Sie mir helfen morgen?","könnten expresses a polite request."),
    s("An deiner Stelle würde ich warten.","In your place, I would wait.","An deiner Stelle ___ ich warten.","würde","An deiner Stelle werde ich warten.","würde gives hypothetical advice."),
    s("Es wäre besser, früher zu gehen.","It would be better to leave earlier.","Es ___ besser, früher zu gehen.","wäre","Es würde sein besser, früher zu gehen.","prefer the direct subjunctive wäre."),
  ], memoryTip:"Use würde for most actions, but reach first for wäre, hätte, könnte, müsste, sollte, and dürfte." }),
];

export const B1_FOUNDATION_LESSONS = buildGrammarLessons(blueprints);
