// Rules are original paraphrases. These primary references support the content;
// CEFR and examination links support the scope, not official lesson certification.
export const GRAMMAR_SOURCES: Record<string, { title: string; url: string }> = {
  cefr: {title:'Council of Europe — CEFR range, accuracy and cohesion',url:'https://www.coe.int/en/web/common-european-framework-reference-languages/table-3-cefr-3.3-common-reference-levels-qualitative-aspects-of-spoken-language-use'},
  goetheB2: {title:'Goethe-Institut — B2 examination materials',url:'https://www.goethe.de/de/spr/prf/ueb/pb2.html'},
  goetheC1: {title:'Goethe-Institut — C1 examination materials',url:'https://www.goethe.de/de/spr/prf/ueb/pc1.html'},
  valency: {title:'IDS grammis — Valenz',url:'https://grammis.ids-mannheim.de/terminologie/275'},
  agreement: {title:'IDS grammis — Agreement patterns',url:'https://grammis.ids-mannheim.de/fragen/3150'},
  control: {title:'IDS grammis — Infinitive interpretation and control',url:'https://grammis.ids-mannheim.de/systematische-grammatik/1555'},
  verbChains: {title:'IDS grammis — Ersatzinfinitiv',url:'https://grammis.ids-mannheim.de/systematische-grammatik/1615'},
  time: {title:'IDS grammis — Dynamic tense interpretation',url:'https://grammis.ids-mannheim.de/systematische-grammatik/270'},
  passive: {title:'IDS grammis — Passive types and constraints',url:'https://grammis.ids-mannheim.de/terminologie/183'},
  reporting: {title:'IDS grammis — Direct and indirect reported speech',url:'https://grammis.ids-mannheim.de/systematische-grammatik/544'},
  modals: {title:'IDS grammis — Epistemic modal verbs',url:'https://grammis.ids-mannheim.de/systematische-grammatik/1552'},
  subjunctive: {title:'IDS grammis — Konjunktiv and würde forms',url:'https://grammis.ids-mannheim.de/sgt/2233'},
  connectors: {title:'IDS grammis — Connector relations and syntax',url:'https://grammis.ids-mannheim.de/systematische-grammatik/366'},
  attributes: {title:'IDS grammis — Attributes and apposition',url:'https://grammis.ids-mannheim.de/vggf/2267'},
  nouns: {title:'IDS grammis — Noun and mixed declension',url:'https://grammis.ids-mannheim.de/progr@mm/5229'},
  nominal: {title:'IDS grammis — Nominalisation',url:'https://grammis.ids-mannheim.de/vggf/2249'},
  relatives: {title:'IDS grammis — Relative elements',url:'https://grammis.ids-mannheim.de/systematische-grammatik/368'},
  es: {title:'IDS grammis — Functions of es',url:'https://grammis.ids-mannheim.de/kontrastive-grammatik/3750'},
  wordFormation: {title:'IDS grammis — Word formation',url:'https://grammis.ids-mannheim.de/systematische-grammatik/484'},
  fields: {title:'IDS grammis — Word order and sentence fields',url:'https://grammis.ids-mannheim.de/systematische-grammatik/748'},
  negation: {title:'IDS grammis — Negation scope and focus',url:'https://grammis.ids-mannheim.de/systematische-grammatik/6360'},
  particles: {title:'IDS grammis — Modal particles',url:'https://grammis.ids-mannheim.de/systematische-grammatik/392'},
  functional: {title:'IDS grammis — Functional-verb constructions',url:'https://grammis.ids-mannheim.de/terms/view/85'},
  commas: {title:'Official spelling rules 2024 — §73: subordinate clauses and infinitives',url:'https://grammis.ids-mannheim.de/rechtschreibung/6203'},
  capitals: {title:'Official spelling rules — Nominalisation and capitals',url:'https://grammis.ids-mannheim.de/rechtschreibung/6194'},
  quotations: {title:'Official spelling rules — Quotation marks',url:'https://grammis.ids-mannheim.de/rechtschreibung/6211'},
  semicolon: {title:'Official spelling rules — Semicolon',url:'https://grammis.ids-mannheim.de/rechtschreibung/6206'},
  verbSpelling: {title:'Official spelling rules — Verb combinations',url:'https://grammis.ids-mannheim.de/rechtschreibung/6153'},
  orthography: {title:'Rat für deutsche Rechtschreibung — Official 2024 rules',url:'https://www.rechtschreibrat.com/regeln-und-woerterverzeichnis/'},
};
