export const GRAMMAR_REFERENCE = [
{ id:'cases',title:'Cases and complements',headers:['Decision','Pattern','Example'],rows:[
['Nominative subject','wer/was? · der/die/das','Der Kollege hilft.'],
['Accusative object','verb frame, not English word order','Ich unterstütze den Kollegen.'],
['Dative object','helfen / danken / widersprechen + Dat.','Ich helfe dem Kollegen.'],
['Genitive and mixed nouns','des Namens · des Herzens · des Studenten','Die Bedeutung des Namens ist klar.'],
['Two-way location versus destination','location: Dat. · directed destination: Akk.','Ich laufe im Park. / Ich laufe in den Park.'],
['Verb/adjective/noun valency','sich beziehen auf · interessiert an · Interesse an','Ich beziehe mich auf den Bericht.'],
]},
{ id:'time',title:'Tense and relative time',headers:['Meaning','Form','Example'],rows:[
['Current / ongoing / scheduled','Präsens + contextual time','Seit Montag arbeitet sie hier.'],
['Past narrative / conversation','Präteritum / Perfekt','Er las den Bericht. / Er hat den Bericht gelesen.'],
['Before a past reference','Plusquamperfekt','Als er ankam, hatte ich gegessen.'],
['Future / inference','werden + infinitive','Sie wird morgen kommen. / Sie wird zu Hause sein.'],
['Completion by deadline / past inference','werden + participle + haben/sein','Bis Freitag wird sie fertig geworden sein.'],
['Perfect infinitive','completion before a reference point','Ich hoffe, bis Freitag alles erledigt zu haben.'],
]},
{ id:'chains',title:'Verb brackets and infinitive chains',headers:['Construction','Pattern','Example'],rows:[
['Main statement','one first-field constituent + finite verb','Den Bericht haben wir gelesen.'],
['Ordinary subordinate clause','connector + … + final finite verb','weil sie heute kommen kann'],
['Modal perfect','haben + lexical infinitive + modal infinitive','Sie hat länger arbeiten müssen.'],
['Subordinate modal perfect','finite haben before Ersatzinfinitiv group','weil sie hat arbeiten müssen'],
['Passive counterfactual chain','hätte + participle + werden + modal','Die Akte hätte geprüft werden müssen.'],
['Post-field','long clause after right bracket','Wir haben gehört, dass sie kommt.'],
]},
{ id:'voice',title:'Voice and participant roles',headers:['Perspective','Construction','Example'],rows:[
['Process','werden + participle','Die Tür wird geöffnet.'],
['Completed process','sein + participle + worden','Die Tür ist geöffnet worden.'],
['Resulting state','sein + participle','Die Tür ist geöffnet.'],
['Impersonal activity','singular verb; dative remains dative','Hier wird gearbeitet. / Ihm wird geholfen.'],
['Recipient','bekommen + accusative thing + participle','Sie bekommt den Ablauf erklärt.'],
['Feasibility / requirement','sich lassen / sein zu, context controls modality','Das lässt sich lösen. / Die Regel ist zu beachten.'],
]},
{ id:'mood',title:'Mood, reporting and evidence',headers:['Purpose','Pattern','Example'],rows:[
['Present hypothetical','wäre / hätte / könnte / würde + infinitive','Wenn ich Zeit hätte, käme ich mit.'],
['Past counterfactual','hätte/wäre + participle','Wenn ich gefragt hätte, hätte ich es gewusst.'],
['Mixed time','past condition + present result','Wenn ich gelernt hätte, wäre ich jetzt sicherer.'],
['Attributed statement','Konjunktiv I; replacement if ambiguous','Sie sagt, sie sei müde. / Sie hätten zugestimmt.'],
['Past reported process','sei + participle + worden','Sie sagt, die Datei sei gelöscht worden.'],
['Inference versus hearsay','muss / dürfte / könnte · soll / will','Er muss gegangen sein. / Er soll gegangen sein.'],
]},
{ id:'clauses',title:'Clause relationships',headers:['Relationship','Connectors','Neutral model'],rows:[
['Reason / added grounds','weil / da / zumal · denn + main order','Wir helfen, zumal die Aufgabe schwierig ist.'],
['Consequence versus purpose','sodass / so … dass · damit / um … zu','Es regnet, sodass wir drinnen bleiben.'],
['Means / missing or replaced action','indem / dadurch, dass · ohne / statt','Sie spart, indem sie weniger verbraucht.'],
['Condition / exception / limit','wenn / sofern / es sei denn / soweit','Wir kommen, es sei denn, der Zug fällt aus.'],
['Concession versus contrast','obwohl / wenngleich / selbst wenn · wohingegen','Selbst wenn er käme, bliebe das Problem.'],
['Time / proportional change','nachdem / bevor / bis / sobald · je … desto','Je mehr du übst, desto sicherer wirst du.'],
]},
{ id:'nouns',title:'Attributes, reference and word formation',headers:['Decision','Pattern','Example'],rows:[
['Adjective ending','article + gender + number + case','mit einem neuen Kollegen'],
['Extended participle','internal modifiers + participle with ending','die gestern veröffentlichte Studie'],
['Required / possible action','zu + Partizip I + ending','die zu prüfenden Daten'],
['Free and sentence relatives','wer/wen/wem · was · wo-compound','Wer hilft, lernt. / Sie kam, was uns freute.'],
['Compound head / derivation','final head sets gender; lexical restrictions','das Arbeitszimmer · die Entscheidung'],
['Explicit nominal roles','patient genitive + agent durch','die Prüfung der Daten durch das Team'],
]},
{ id:'scope',title:'Information structure and scope',headers:['Check','Contrast','Model'],rows:[
['Focus particle attachment','only subject versus only object','Nur Anna liest den Bericht. / Anna liest nur den Bericht.'],
['Partial versus universal negation','nicht alle ≠ niemand','Nicht alle Gäste sind gekommen.'],
['Referential versus placeholder es','subject agreement is independent','Es kamen Gäste. / Heute kamen Gäste.'],
['Pronoun reference','one identifiable antecedent','Die Studie ist neu; ihr Ergebnis überrascht uns.'],
['Agreement with quantities','formal and semantic variation can coexist','Eine Reihe von Fragen ist/sind offen.'],
['Modal particle context','shared knowledge, expectation, attitude','Du kennst doch die Regel.'],
]},
{ id:'writing',title:'Punctuation, spelling and revision',headers:['Check','Current rule / qualification','Example'],rows:[
['Subordinate boundaries','finite and clause-like infinitive clauses take commas','Sie hofft, den Kurs abzuschließen.'],
['Integrated predicate / bare infinitive','no split in integrated predicates; bare word-group readings allow variation','Du brauchst nicht zu warten. / Sie versucht(,) abzunehmen.'],
['Inserted clauses','frame with two commas','Der Text, den ich lese, ist neu.'],
['Direct quotation with following report','close quotation, then outer reporting comma','„Ich komme“, sagte sie.'],
['Nominalisation / formal address','capitals mark grammatical function','etwas Neues · beim Lesen · ich danke Ihnen'],
['Revision order','meaning → roles/time → clauses → inflection → spelling','State who does what, when, and whose claim it is.'],
]},
] as const;
